### ISSUE TITLE
Текущая версия не работает

### ISSUE THREAD

**Issue by vsuh** [xDrivenDevelopment/1c-syntax#10]

**Comment by nixel2007** [comment]
Все в порядке? :)

**Comment by vsuh** [comment]
недопроверил еще.
заменил скаченным `.tmLanguage` файлом свой старый и получил ошибку
парсинга *The mode has failed while tokenizing the input* вернул старый
файл взад - то же самое.
Скорее всего у меня какая-то проблема. Буду смотреть.

С уважением,
Сухих Валерий Юрьевич
тел. моб. +79636755975
mailto:vsukhikh@gmail.ru

2015-12-04 14:11 GMT+03:00 Nikita Gryzlov <notifications@github.com>:

**Comment by vsuh** [comment]
Вобщем, проблема кОнцептуальная. Нужно определиться с тэгом языка. У меня в `package.json` язык определен как `onescript`, соответственно, в файле `onescript.tmLanguage` все лексемы имеют расширение `.onescript` типа:

	<string>string.other.onescript</string>
	</dict>
	<dict>
    ....
			<key>name</key>
	<string>support.function.onescript</string>

В лежащем в репозитории файле тег языка определен как 1c причем, видимо с последним символом в теге постоянно возникают непонятки, поэтому, скаченный файл `1c.tmLanguage` у меня сразу вызвал ошибку разбора.

**Comment by nixel2007** [comment]
> В лежащем в репозитории файле тег языка определен как 1c причем, видимо с последним символом в теге постоянно возникают непонятки, поэтому, скаченный файл 1c.tmLanguage у меня сразу вызвал ошибку разбора.
Исправлено в efcaf7a004d89191b064f6c1b935b915270e9a0d

**Comment by nixel2007** [comment]
> Вобщем, проблема кОнцептуальная. Нужно определиться с тэгом языка.

Я за тег `1c`. Проблемы идентификаторов можно отловить какими-нибудь тестами, а глобально - это все же описание встроенного языка 1С, который используется одним из сторонних механизмов, таким как onescript. Именно то onescript тут только директива `#Использовать`. Мне бы хотелось иметь пакет, связанный именно с 1С как с системой, описание его (1с) синтаксиса, его же сниппеты. 
Про расширение для onescript (директива, инструменты запуска и отладки) можно написать отдельно в описании пакета/readme.

@xDrivenDevelopment/1c-syntax что думаете?

**Comment by EvilBeaver** [comment]
Я за тег bsl. Именно так будут называться файлы исходников в Eclipse. Называть 1С не хотелось бы, поскольку есть еще и onescript, который будет тоже редактироваться в VSCode и прочих, а он не может применять торговые марки 1С.

bsl - это неизвестное нечто, но именно так 1С называет свой язык (именно язык, как набор синтаксических правил) Он же реализован в 1Script и на синтаксисы языков копирайты не распространяются.

**Comment by nixel2007** [comment]
@EvilBeaver да, bsl имеет смысл.
Что с названием пакетов? Люди будут искать 1с, а не bsl.
Для Atom рекомендуется использовать название пакета "language-<имя языка>".
Для ST явной рекомендации нет, проверил package control - используется как "language-<имя языка>", так и "<имя языка>-language"
Правила именования для VCS не смотрел.

Что мы будем использовать в имени пакета?

**Comment by vsuh** [comment]
`bsl-1c-1Script`

**Comment by EvilBeaver** [comment]
И еще момент - называть с цифры не очень хорошо. Подозреваю проблемы с какой-нибудь программой, которая не понимает теги, начинающиеся с цифры.

Насчет имени пакета вопрос хороший. Конечно же люди будут искать

**Comment by EvilBeaver** [comment]
@vsuh bsl-1c мне нравится. 1Script смысла упоминать нет, т.к. это *языковой пакет*, а 1Script - это реализация *существующего* языка, он не сам по себе.

**Comment by nixel2007** [comment]
как насчет такой раскладки:
имя пакета: `language-1c-bsl`
идентификатор в грамматике и прочих конфигах: `bsl`
?

**Comment by EvilBeaver** [comment]
> имя пакета: language-1c-bsl
> идентификатор в грамматике и прочих конфигах: bsl

@nixel2007 не возражаю

**Comment by vsuh** [comment]
за

С уважением,
Сухих Валерий Юрьевич
тел. моб. +79636755975
mailto:vsukhikh@gmail.ru

2015-12-04 17:44 GMT+03:00 Andrei Ovsiankin <notifications@github.com>:

**Comment by artbear** [comment]
Я также за

пт, 4 Дек 2015, 18:18, vsuh <notifications@github.com>:

**Comment by nixel2007** [comment]
Поменял идентификатор на bsl. Думаю, можно закрывать issue?
