### ISSUE TITLE
Класс функций и процедур

### ISSUE THREAD

**Issue by ebugusey** [xDrivenDevelopment/1c-syntax#100]
Для процедур и функций для ключевого слова `Функция/Процедура` определен класс `storage.type.bsl`. Из-за этого в некоторых темах оно выглядит как обычный текст. И сам класс не отражает сути ключевого слова. Нужно что-то типа такого `meta.function.type.bsl`. Ну и про `КонецФункции/Процедуры` не забыть.

Я использую Solirized Dark, если что.

**Comment by nixel2007** [comment]
Storage.type было взято с официальной документации TextMate, раздел Naming conventions http://manual.macromates.com/en/language_grammars#naming_conventions

Из личного опыта знаю, что многие темы вообще не раскрашивают meta.*, так как они больше разметочные, чем описательные. Однако же есть темы, которые наоборот не соблюдают naming conventions. Я наткнулся на это при разработке грамматики языка запросов и определении #Область. 

Тут нужно аккуратно, чтобы не поломать имеющееся.

**Comment by ebugusey** [comment]
Важная часть здесь, на самом деле, `function`, так что можно `storage.type.function.bsl`.

**Comment by nixel2007** [comment]
В Atom в Solirized Dark нормально подсвечивает "Функция/Процедура". Какой редактор используете? В какой теме наблюдаются проблемы?

**Comment by ebugusey** [comment]
Да, действительно, в Атоме эта тема выглядит по-другому. Я это обнаружил в VSC.

**Comment by nixel2007** [comment]
Я бы даже сказал **очень** по-разному.
Слева vs code, справа Atom.

![default](https://cloud.githubusercontent.com/assets/1132840/13354035/6344039c-dca9-11e5-8ede-52068aa7355c.PNG)

Вспоминая их проблемы в 0.10.5, вызванные сменой токенайзера, которые они расхлебывают до сих пор, предполагаю, что это проблема на стороне vs code.

Sublime выглядит тоже по-другому - что-то близкое к VS code, но "процедура" подсвечивается корректно.
![default](https://cloud.githubusercontent.com/assets/1132840/13354100/e335d5f8-dca9-11e5-96bc-80012aecff12.PNG)

**Comment by ebugusey** [comment]
Тогда, наверное, лучше оставить как есть. Авось к релизу разгребут.
