### ISSUE TITLE
[Atom] Не работает проверка синтаксиса (lint) при установке продукта по-умолчанию

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/1c-syntax#103]
Проблема в том, что у нашего пакета нет зависимости от пакета linter
Как только ставишь этот пакет, проверка синтаксиса работает.
@nixel2007 добавишь зависимость в наш пакет?

**Comment by nixel2007** [comment]
Хм. Вроде есть же зависимость
 https://github.com/xDrivenDevelopment/atom-language-1c-bsl/blob/master/package.json#L18

Проверю.

**Comment by artbear** [comment]
+ Только что ставил Атом с нуля, пакет линтер не поставился.
поставил пакет linter-coffeelint, пакет линтер подтянулся и синтакс-проверка заработала.
+ ИМХО нужно в [инструкции](https://github.com/xDrivenDevelopment/atom-language-1c-bsl/wiki/%D0%98%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BB%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D0%B0) описать зависимость от этого пакета.

**Comment by artbear** [comment]
У тебя прописана зависимость `"atom-linter": "^3.1.1",`
а у меня используется пакет с другим именем https://atom.io/packages/linter
Где неточность?

Пакета https://atom.io/packages/atom-linter не существует :)

**Comment by nixel2007** [comment]
Есть подозрение, что это зависимость на уровне npm, а не apm. Потому что у неё даже номер версии ощутимо так отличается.

**Comment by nixel2007** [comment]
Исправлено в 1.3.1
