### ISSUE TITLE
Atom: Перейти к определению для метода скрипта не переходит сразу на определение, а сначала выдается окно с двумя дублями с именем метода

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/1c-syntax#104]
Например, редактируем файл [gitsync.os](https://github.com/EvilBeaver/oscript-library/blob/develop/src/gitsync/src/gitsync.os)
В коде метода `РазобратьАргументыКоманднойСтроки` ставим курсор на `ИнициализироватьПарсерАргументов` и вызываем `Перейти к определению`
Получаем окно с дублями.
Выбор любого из дублей выполняет переход к одному и тому же определению.

**Comment by artbear** [comment]
После перезагрузки Атома проблема исчезла :)

**Comment by artbear** [comment]
Слегка дополнил [инструкцию по Перейти к определению](https://github.com/xDrivenDevelopment/atom-language-1c-bsl/wiki/%D0%9F%D0%B5%D1%80%D0%B5%D0%B9%D1%82%D0%B8-%D0%BA-%D0%BE%D0%BF%D1%80%D0%B5%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D1%8E), вставив следующий текст:

### Известные проблемы

Если при выполнении операции `Перейти к определению` немедленного перехода не происходит, а появляется  с дублями имен, значит, вы только что установили пакет Goto. Просто перезапустите Atom и проблема исчезнет

**Comment by nixel2007** [comment]
@artbear дубли могут возникнуть из-за повторения процедур в разных файлах. не на это наткнулся? там внизу приписка с именем файла
