### ISSUE TITLE
Запуск тестов atom-grammar-test при коммите в репо 1c-syntax

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#116]
Сейчас грамматические тесты выполняются автоматически при коммите в репо atom-language-1c-bsl, что затрудняет мгновенное получение обратной связи при обычном редактировании грамматики в YAML в рамках текущего репо.

Предложение - настроить travis_ci и appveyor, модифицировав файлы конфига из atom-language-1c-bsl так, чтобы:
- происходила установка последней версии oscript
- скачивался репозиторий atom-language-1c-bsl
- запускался `oscript -encoding=utf-8 build.os -bsl -sdbl`
- запускался `oscript -encoding=utf-8 publish.os` (сейчас он не умеет копировать файлы только одного пакета, понадобится добавить флаги, например `-atom`)
- запускались spec-тесты Атома

Т.к. я полный ноль в настройке контейнерного окружения на линуксе и мак ос, то вешаю help_wanted, авось кому будет скучно :)

**Comment by EvilBeaver** [comment]
А при чем тут контейнерное окружение?

**Comment by nixel2007** [comment]
@EvilBeaver ну, travis и appvayor же где-то (шепотом) **там**, в облаке, да и вроде в докере.
а я только gitlab ci на локальной машине настраивал)

**Comment by nixel2007** [comment]
9 месяцев потребовалось на формализацию идеи и её воплощение. 
А потом ещё кто-то говорит, что код - это не детище.

**Comment by awa15** [comment]
А программист не женщина))
