### ISSUE TITLE
Regex для литералов даты не учитывает все варианты

### ISSUE THREAD

**Issue by rgistzev** [xDrivenDevelopment/1c-syntax#121]
Предлагаю исправить regex для литералов на этот:
`\'((\d{4}[^\d\']*\d{2}[^\d\']*\d{2})([^\d\']*\d{2}[^\d\']*\d{2}([^\d\']*\d{2})?)?)\'`

Почему:
1. Платформа корректно преобразует в дату варианты литералов, где между частями даты стоят любые разделители. В типовых часто даты указывают в формате '0001-01-01'.
2. После нескольких экспериментов с частями даты выяснилось, что можно указывать либо ДДДДММГГ, либо ДДДДММГГччмм, либо ДДДДММГГччммсс.

Что интересно, что для функции Дата() передаваемая строка контролируется более жестко: варианты частей даты такие же, но указание разделителей запрещено.

Пулл реквест делать?

**Comment by nixel2007** [comment]
Пулл-реквест - это всегда хорошо.

Можешь приложить к PR сразу текст теста со всеми добавленными вариантами?
Вот формат: https://github.com/xDrivenDevelopment/atom-language-1c-bsl/blob/master/spec/fixtures/grammar/syntax_test_bsl.bsl#L99

**Comment by nixel2007** [comment]
Еще бы хорошо проверить, что строки с `'` внутри строк `"` не поломается

**Comment by rgistzev** [comment]
Done.
Запустить тест не могу: Sublime Text 3, похоже, не поддерживает scope selectors с префиксами `not:`. А запустить на Atom у меня, к сожалению, не получается.

**Comment by nixel2007** [comment]
@rgistzev 
> Запустить тест не могу: Sublime Text 3, похоже, не поддерживает scope selectors с префиксами not:

да, это фишка, добавленная в atom-grammar-test.

А что не получилось с atom? `npm install` в каталоге пакета сделал?

**Comment by rgistzev** [comment]
Хотел использовать portable-версию Atom. Но в ней, похоже, есть проблемы с доустановкой зависимостей. atom-grammar-test так и не установился, поэтому не работало.
На официальном Atom все работает, как должно.

**Comment by nixel2007** [comment]
atom-grammar-test это не зависимость atom. Это nodejs пакет, и его надо ставить через npm

**Comment by nixel2007** [comment]
Закрыто #122
