### ISSUE TITLE
Поиск ссылок на процедуру в теле модуля

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#129]
Find all references не находит вызова в теле модуля.

**Comment by pumbaEO** [comment]
Исправил https://github.com/xDrivenDevelopment/vsc-language-1c-bsl/commit/733afb4b53091201a7ccbbe7da9a55f1a96a5f50

**Comment by nixel2007** [comment]
:+1:

**Comment by nixel2007** [comment]
Переоткрываю. Процедуру находит только один раз.
@pumbaEO 

Пример - Конструктор_СоответствиеКаталоговПакетов из build.os

**Comment by nixel2007** [comment]
Имхо, вот тут как-то слишком жадно: https://github.com/xDrivenDevelopment/vsc-language-1c-bsl/blob/1e0f458a228e62676fa840bf756f06f7a2ce8c78/src/global.ts#L191
