### ISSUE TITLE
Переход к определению на неэкспортных процедурах

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#139]
типовой метод:
`Обработки.ИмяОбработки.Создать()`

По f12 идет переход в какой-то рандомный модуль, где есть процедура Создать(), причем не экспортная

**Comment by pumbaEO** [comment]
может добавить условие, если больше 2х точек и не найден модуль, тогда открывать... модуль объекта? Или модуль менеджера?

**Comment by nixel2007** [comment]
По Обработки.ИмяОбработки.Создать() надо открывать модуль менеджера, да.
А в более хардкорном варианте надо бы модуль объекта:
```
ОбработкаОбъект = Обработки.ИмяОбработки.Создать();
ОбработкаОбъект.Метаданные(); <---
```

Но вторая ситуация у нас вроде пока вообще невозможна :)

**Comment by nixel2007** [comment]
Ох ты как, он еще совершил переход к экспортной процедуре модуля формы (но корректного объекта)
