### ISSUE TITLE
Как можно проверить правильность грамматик?

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/1c-syntax#14]
Как можно проверить правильность грамматик?
Какие есть инструменты и рекомендации?

**Comment by nixel2007** [comment]
В теории можно обратиться к движку ST/Atom/VSC, открыв некий тестовый файлик с кодом и проверять к какому классу соотнесен тот или иной текст из этого файла. Atom и VSC в силу своего движка оборачивают текст в дивы с указанием классов, прописанных в грамматике. Т.е. если мы точно знаем, что `&НаКлиенте` должно рендерится как `keyword.other.bsl` (например, описав это в неком файле-эталоне), мы можем открыть файл в редакторе (или вставив в файл кодом строку из этого эталона), сделать выделение и прочитать имя класса из свойства дива.

Таким образом можно разработать единый механизм запуска тестов (т.к. грамматики общие, по крайней мере пока) и 3 коннектора к каждому из редакторов.

Другой вопрос - зачем это делать. Класс может не определиться по двум причинам:
* баг в регэкспе
* баг в самом редакторе

Регэкспы потихоньку набирают сложности, поэтому проверка того, что изменение в одной части грамматики не порушило все остальные регэкспы может быть полезным.  
Баг в редакторе... Остаётся его только репортить, но вроде версии редакторов более-менее стабильные в этом плане, не думаю, что мы на это наткнемся.

Пока же... Проверка визуально (с)

**Comment by vsuh** [comment]
Никита, добавьте в скайп `vscraft`

**Comment by nixel2007** [comment]
Вот пример spec-тестов под atom для пакета language-python https://github.com/atom/language-python/blob/master/spec/python-spec.coffee

**Comment by nixel2007** [comment]
Один из замеченных ништяков Атома - в нем есть встроенный запускальщик spec-тестов разрабатываемого пакета.

**Comment by artbear** [comment]
Как выполнить этот запускальщик в Атоме?

вс, 6 дек. 2015 г. в 16:08, Nikita Gryzlov <notifications@github.com>:

**Comment by nixel2007** [comment]
@artbear View - Developer - Run Package Specs (Alt + Ctrl + P)

**Comment by nixel2007** [comment]
`https://github.com/gandm/language-babel/pull/146`

**Comment by nixel2007** [comment]
Грамматику теперь можно проверить локально и на сервере сборки.
Локально проверяется через Атом командой Run package specs.
Сервера сборки выполняют проверку при коммите в репо atom-language-1c-bsl
