### ISSUE TITLE
Работа с rootPath и рекурсивный поиск

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#140]
@pumbaEO @bambr1975

Сейчас, если не задан параметр rootPath, то он инициализируется корнем репозитория, вместо `src/cf`.

Но бог с ним, это можно было бы и поправить.
@bambr1975 предлагает переосмысление этого параметра.

По умолчанию искать от корня репозитория жадным поиском вида
`vscode.workspace.findFiles("**/*.bsl", "", 10000);`
Тогда он рекурсивно обходит и все вложенные подкаталоги (не надо руками обрабатывать всякие Ext и Forms) и кэширует все bsl.

При этом сам параметр rootPath можно оставить для, скажем, ускорения поиска, или если кому-то не нужен поиск по всем модулям, дав возможность ограничить пространство поиска конкретной папкой.

Какие проблемы это может решить:
* распарсятся все bsl, независимо от структуры каждого конкретного метаданного
* получим поддержку линейной выгрузки конфигурации (причем и в новом и в старом формате)
* можно будет открывать сразу каталог с конфой, а не каталог с репо, где обязательно должна быть src/cf

Проблемы, которые это может принести:
* количество обрабатываемых файлов увеличится. Но вроде теперь async и с этим должно быть попроще
* могут начать определяться лишние BSL - это и плюс и минус одновременно. Надо посмотреть, нормально ли будет себя вести автокомплит и f12

Атом и ST по другим языкам делает такой же "жадный" поиск и вроде это всех устраивает.

**Comment by pumbaEO** [comment]
rootPath нужен в основном для редактирования внешних обработок, тогда нормально отрабатывает автокомплит для этой обработки.
Локально можно rootPath определять как корень с файлом Configuration.xml и содержимым "<MetaDataObject xmlns=" .

**Comment by nixel2007** [comment]
Поясни по поводу обработок - что должно быть в rootPath для того, чтобы работал автокомплит? корень разобранной обработки? прекоммитом или 8.3.8?
И какого рода автокомлит? из модуля обработки... что? конфа-то где-то сборку лежит.

Для конфигурации хочется вообще от rootPath отказаться, пускай он все парсит.
