### ISSUE TITLE
Неверно обрабатывает "Область" (VSC)

### ISSUE THREAD

**Issue by JohnyDeath** [xDrivenDevelopment/1c-syntax#143]
Вот такое на VSC 1.0 и 1c-syntax 1.4.7
![image](https://cloud.githubusercontent.com/assets/5936030/14539532/67bf9e62-0289-11e6-81e7-9855f0e6baf7.png)

**Comment by nixel2007** [comment]
Дай угадаю. Ты раскрасил файл txt? 
Это сообщение от oscript -check 
Линтер по умолчанию хавает в себя все, что ему дают, кроме bsl - для этого отдельная настройка :)

**Comment by JohnyDeath** [comment]
Да, txt. 
А выбора типа подсветки не хватает? Или там жестко к расширению прикручено и от этого никуда не уйти?

**Comment by nixel2007** [comment]
@JohnyDeath не совсем понял тебя :)
включение подсветки как раз и включает работу линтера.
По умолчанию он отсекает только расширение bsl. Возможно стоит придумать более интеллектуальный алгоритм :)
Но в любом случае, пока от линтера для обычных файлов модулей толку мало - имена модулей он не найдет, с метаданными работать не сможет.
Плюс текущая версия oscript не умеет обрабатывать инструкции препроцессору (в том числе #область), но такую задачку я уже повесил на битбакете

**Comment by JohnyDeath** [comment]
Теперь я тебя понял. Спасибо. Закрываем.
