### ISSUE TITLE
[vsc]: hoverProvider

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#144]
Низкий приоритет. Успеем - хорошо. Не успеем - в след релиз.

**Comment by JohnyDeath** [comment]
а что это вообще?

**Comment by pumbaEO** [comment]
Подсказка по параметрам функции или процедуры.

2016-04-15 11:29 GMT+03:00 Evgeny Martynenkov <notifications@github.com>:

> а что это вообще?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/xDrivenDevelopment/1c-syntax/issues/144#issuecomment-210358946>
>



-- 
З повагою Сосна Євген,
mailto:shenja@sosna.zp.ua
skype:shenjasosna
+380933897103

**Comment by nixel2007** [comment]
Вплывающая при наведении.
![default](https://cloud.githubusercontent.com/assets/1132840/14555955/4b13e7ee-02fe-11e6-9582-f4b2e80292c3.gif)

Идеи как реализовать есть, вопрос во времени :)

**Comment by nixel2007** [comment]
Доделать: подсказка по параметрам процедур общих модулей и модулей менеджеров.
В идеале - еще и с комментариями.

**Comment by nixel2007** [comment]
Готово
