### ISSUE TITLE
Автодополнение процедур модулей по части имени

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#149]
![image](https://files.gitter.im/nixel2007/tsport/yWJn/______________.gif)

**Comment by artbear** [comment]
А Атом?

**Comment by nixel2007** [comment]
@artbear работы по портированию в Атом начнутся только после стабилизации версии VSC.
Выпущены же эти версии будут одновременно.

**Comment by nixel2007** [comment]
Решено.
