### ISSUE TITLE
Нет раскраски инструкций препроцессору

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#15]
Из обсуждения https://github.com/xDrivenDevelopment/1c-syntax/pull/13#issuecomment-162316372

На данный момент инструкции препроцессору объявлены как `meta.preprocessor.bsl`.
Для `meta` по умолчанию нет раскраски.

> Атом, например, вроде позволяет инлайнить кусочки стилей в основной стиль

Либо поступить таким же образом (предусмотреть решение для всех редакторов), либо придумать что-то другое.

**Comment by bambr1975** [comment]
Согласно https://manual.macromates.com/en/language_grammars
c помощью наименования ```meta```  маркируются большие части документа:
> is generally used to markup larger parts of the document. 

Я это к тому, что для него не просто так нет раскраски. Только это наименование области позволяет использовать ключ ```captures``` (только при его использовании этот ключ начинает работать). 
> used in scope selectors for activation of bundle items.

Может, все-таки переименовать ? (например, в ```keyword.preprocessor.bsl``` или еще как-то)

**Comment by nixel2007** [comment]
А по сути это же и есть большая часть документа: между #Если и #КонецЕсли - кусок модуля, который компилируется в том или ином приложении.

**Comment by nixel2007** [comment]
Да и для наименований областей используется `entity.name.section`.
К чему это я: как обычно хочется всего и сразу. И сказать, что это именно некая область внутри, и теги подкрасить =(

**Comment by bambr1975** [comment]
Я имею в виду, что раскрашивается только строка с директивой (и с ее концом)
Разметка ```meta``` используется для того, чтобы подсветить другими цветами некоторые ее части, которые будут обозначены группами регулярок (при использовании ключа ```captures```)

**Comment by nixel2007** [comment]
Запланировано в 1.0.1
