### ISSUE TITLE
Поддержка 8.3.8

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#150]
Релизнулась, пора делать.

* [x] Обновить грамматику
* [x] Обновить глобальные свойства/функции для автокомплита
* [x] Проверить шаблоны текста

**Comment by awa15** [comment]
@nixel2007 , тебе для этого нужна база Типы1С, заполненная из 8.3.8.1652?

**Comment by nixel2007** [comment]
@awa15 да, очень поможет :)

**Comment by awa15** [comment]
https://yadi.sk/d/MFrtoLtNrD2Zd

**Comment by nixel2007** [comment]
Спасибо большое! 

Отправлено с моего HTC

----- Ответное сообщение -----
От: "Valeriy Ageev" <notifications@github.com>
Кому: "xDrivenDevelopment/1c-syntax" <1c-syntax@noreply.github.com>
Копия: "Nikita Gryzlov" <nixel2007@gmail.com>, "Mention" <mention@noreply.github.com>
Тема: [xDrivenDevelopment/1c-syntax] Поддержка 8.3.8 (#150)
Дата: пт, апр. 22, 2016 16:08

https://yadi.sk/d/MFrtoLtNrD2Zd

&mdash;You are receiving this because you were mentioned.Reply to this email directly or view it on GitHub

**Comment by nixel2007** [comment]
Еще https://wonderland.v8.1c.ru/blog/rasshirenie-moduley/

**Comment by JohnyDeath** [comment]
О! А давно у зазеркалья появился отдельный поддомен?

**Comment by nixel2007** [comment]
@JohnyDeath сегодня от @allustin в гугл плюсе узнал

**Comment by allustin** [comment]
@nixel2007 я вчера на партнерке увидел.

**Comment by EvilBeaver** [comment]
@nixel2007 а чего там нового в глобальных контекстах и грамматике?

**Comment by nixel2007** [comment]
@EvilBeaver четыре новых класса, обновлена справка у десятка методов, новые директивы компиляции &Перед, &После и &Вместо

**Comment by nixel2007** [comment]
> Еще https://wonderland.v8.1c.ru/blog/rasshirenie-moduley/

а, тьфу, это ж в 8.3.9

/cc @EvilBeaver
