### ISSUE TITLE
Не работает "Перейти к определению" и Ctrl+R в Атоме

### ISSUE THREAD

**Issue by EvilBeaver** [xDrivenDevelopment/1c-syntax#155]
Атом 1.7.2, пакет языка 1.4.7

Не работает переход к определению (F12) и переход к процедуре (Ctrl+R показывает пустой список и No symbols found) Кажется, что это звенья одной цепи.

**Comment by nixel2007** [comment]
Пакет goto стоит?

**Comment by nixel2007** [comment]
@EvilBeaver ping

**Comment by EvilBeaver** [comment]
После выходных уточню
