### ISSUE TITLE
Ложные срабатывания линтера при разработке модульных приложений 1script

### ISSUE THREAD

**Issue by EvilBeaver** [xDrivenDevelopment/1c-syntax#158]
Если редактируем приложение 1script, состоящее из нескольких модулей, то линтер ругается на глобальные свойства, объявленные где-то вне текущего файла (что верно, т.к. он не знает про них)

### Поддержка со стороны 1Script. 
Коммитом https://github.com/EvilBeaver/OneScript/commit/2372dc71560bdfb8abf23dfe120e53b07e2b2d49 реализован дополнительный параметр, задающий точку входа, определяющую окружение.

### Требуется

Реализовать ответную поддержку со стороны линтера

**Comment by EvilBeaver** [comment]
Реализовано в vsc: https://github.com/xDrivenDevelopment/vsc-language-1c-bsl/pull/14

**Comment by nixel2007** [comment]
Сделано в vsc tsport.

/cc @EvilBeaver - смотри коммит https://github.com/xDrivenDevelopment/vsc-language-1c-bsl/commit/d307bab453cbdc470e54c54668566a95dd5cb886
