### ISSUE TITLE
[VSC] Переход к определению и обратно

### ISSUE THREAD

**Issue by JohnyDeath** [xDrivenDevelopment/1c-syntax#164]
Неверно отрабатывает переход "назад" после перехода "к определению". Часто возвращается не в ту же строку, а на несколько строк вперед/назад.
Независимо от того как именно осуществляю переход: горячими клавишами или через меню.
Причем поведение может быть корректным. Закономерности установить так и не смог.

Текст модуля, на котором тренировался:

```
Процедура Основная()
    к = 1;    
КонецПроцедуры

Процедура Вспомогательная()
    СтрокаПроизвольная = "Строка произвольная";
КонецПроцедуры // Вспомогательная()

Процедура Вторая()

    Основная();

    Вспомогательная();

    Если Ложь Тогда
        в = "";
    Иначе
    КонецЕсли;
КонецПроцедуры
```

VSC версии 1.1.0. "Подсветка" версии 1.4.8

Гифка:
![aninf12](https://cloud.githubusercontent.com/assets/5936030/15177542/49205ef6-1779-11e6-926f-07893e29fded.gif)

**Comment by nixel2007** [comment]
Какие переносы строк установлены в файле?

**Comment by nixel2007** [comment]
Вешаю wontfix, так как это явно проблема редактора, а не пакета - пакет не переопределяет какие-либо position или range при переходе назад

**Comment by nixel2007** [comment]
Возможно стоит посмотреть исходники самой vsc.

**Comment by JohnyDeath** [comment]
![image](https://cloud.githubusercontent.com/assets/5936030/15177722/3a0d445a-177a-11e6-8431-f67f0f20aece.png)

**Comment by nixel2007** [comment]
Если выбрать LF и пересохранить файл - повторяется такое поведение?

**Comment by JohnyDeath** [comment]
Да, повторяется.
Вот как точно можно воспроизвести:

1. Встаем на процедуру, к определению к которой хочу перейти
1. F12 (переходи к определению)
1. Alt+назад (переход обратно). Вернулись в правильное место (чаще всего)
1. Два раза нажимаем "вниз" и два раза "вверх" (в итоге стоим на той же процедуре)
1. Повторяем первые два шага. Оказываемся на строчку ниже!

**Comment by JohnyDeath** [comment]
На 1c-syntax версии 1.5.0 поведение не изменилось.
Проверял на трех разных компьютерах. Странно, что больше ни у кого не проявляется...

**Comment by nixel2007** [comment]
У меня воспроизводится в описанной последовательности действий.

**Comment by bambr1975** [comment]
сейчас в описанной последовательности действий не воспроизводится

**Comment by nixel2007** [comment]
@JohnyDeath можешь проверить на 1.9?

**Comment by JohnyDeath** [comment]
Остается, но немного по-другому.

- [x]  Встаем на строку 11 -> "F12" -> перескакиваем к определению "Основная"
- [x]  "Alt+ Left" -> вернулись на строку 11
- [x] Переходим курсором на строку 13 -> "F12" -> перескакиваем к определению "Вспомогательная"
- [ ] "Alt+ Left" -> вернулись на строку 11, А должны были на 13

**Comment by bambr1975** [comment]
не воспроизводится. сделай видео, пожалуйста (так, чтобы было видно версию vs code)

**Comment by JohnyDeath** [comment]
https://www.screencast.com/t/6VOp0KoYWe

**Comment by bambr1975** [comment]
Прикольно. В сохраненном файле не воспроизводится, а в несохраненном - воспроизводится)))

**Comment by JohnyDeath** [comment]
Да, если сохранить файл, то все нормально.
Даже если потом модифицировать и не сохранять - тоже нормально

**Comment by nixel2007** [comment]
Говорят, пофиксили в VSC 1.17.0. Ждем релиза.
