### ISSUE TITLE
[Wiki] Обсуждение

### ISSUE THREAD

**Issue by vsuh** [xDrivenDevelopment/1c-syntax#17]
Раз в самой вики обсуждения нет, давайте здесь обсуждать.
Нужны ли еще две страницы с описанием ручной установки синтаксиса в `Atom` и `Sublime text`?
Или там будет только описание процедуры запуска установочных пакетов.

**Comment by nixel2007** [comment]
Мое видение - процедуры установки синтаксиса в редакторах будут описаны в профильных репозитариях. Например, как вот здесь - https://github.com/colinta/SublimeFileDiffs

В wiki данного репо должна быть информация по разработке грамматик, сбору пакетов, ROADMAP и все такое.

**Comment by nixel2007** [comment]
@vsuh  может процесс установки пакета отразить в  Readme?  Как это сделано в репо для 
Sublime text.

**Comment by vsuh** [comment]
@nixel2007 я зря ST __3__ в вики написал?
В `Readme` версия не указана. Наш пакет на 2-м тоже работает?

**Comment by nixel2007** [comment]
@vsuh не тестировал, если честно.
Вообще tmLanguage в ST2 тоже поддерживался, так что синтаксис должен работать и там и там. На packagecontrol.io я версию тоже не указывал.
