### ISSUE TITLE
[Atom] Публикация пакета

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#18]
Ссылка на гайд по публикации: https://atom.io/docs/v1.2.4/hacking-atom-package-word-count#publish-your-package

Действия, которые необходимо выполнить для публикации пакета:

* [x] В файле [package.json](https://github.com/xDrivenDevelopment/atom-language-1c-bsl/blob/master/package.json) есть поля `name`, `description` и `repository`.
* [x] В файле [package.json](https://github.com/xDrivenDevelopment/atom-language-1c-bsl/blob/master/package.json) есть поле `version` со значением "0.0.0".
* [x] В файле [package.json](https://github.com/xDrivenDevelopment/atom-language-1c-bsl/blob/master/package.json) есть поле `engines`, содержащую указание версий Atom, например  `"engines": {"atom": ">=0.50.0"}`.
* [x] В вашем пакете есть файл [README.md](https://github.com/xDrivenDevelopment/atom-language-1c-bsl/blob/master/README.md) в корне репозитория. (необходимо наполнение файла)
* [x] Ваш пакет - это репозиторий git, который был опубликован на GitHub.

**Comment by nixel2007** [comment]
@xDrivenDevelopment/1c-syntax Категорически поздравляю нас с готовым релизом под Atom

https://atom.io/packages/language-1c-bsl

**Comment by vsuh** [comment]
нету

**Comment by vsuh** [comment]
йес!

**Comment by EvilBeaver** [comment]
Урааа!!! Парни, это реально круто же!

**Comment by EvilBeaver** [comment]
Кстати, а вот это что https://atom.io/packages/language-1c ?

**Comment by artbear** [comment]
>Урааа!!! Парни, это реально круто же!

Ага, я пока болел/болею, тащусь с подвижек :)

**Comment by nixel2007** [comment]
> Кстати, а вот это что https://atom.io/packages/language-1c ?

а это у меня их деплой-утилита в середине упала -_-
Надо сделать unpublish.
