### ISSUE TITLE
[Atom] Не работает переход по ошибкам

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/1c-syntax#182]
что-то регулярное выражения для поиска ошибок из .atom-build.json не работает 
```json
"errorMatch": [
  "^\\{Модуль (?<file>.+) / Ошибка в строке: (?<line>[0-9]+) / (?<message>.*)\\}$"
]
```
не работает переход по ошибкам по хоткеям из пакета build

> @nixel2007 надо хромовским отладчиком залезать в код пакета build

**Comment by bambr1975** [comment]
Не нужны символы ^ и $ - их можно использовать только при многострочном режиме регекспов, который в данном случае не включен (и мы его включить не сможем). Если их убрать - все работает

**Comment by artbear** [comment]
@bambr1975 Я проверял без этих символов, у меня не работало.Проверю еще раз.
А ты сама проверяла?

**Comment by bambr1975** [comment]
перезагрузить атом надо

**Comment by artbear** [comment]
@bambr1975 я знаю, что нужно его перегрузить.
Ты скажи - сама проверяла?

**Comment by bambr1975** [comment]
Артур, я тебе когда-нибудь что-нибудь непроверенное присылала?

**Comment by artbear** [comment]
лады, ответ понял :) сейчас проверю

**Comment by artbear** [comment]
@nixel2007 
Совместно с @bambr1975 выявили правильное выражение
```json
"errorMatch": [
  "{Модуль (?<file>[^/]+) / Ошибка в строке: (?<line>[0-9]+) / (?<message>.*)"
]
```

Где-то, кроме документации, что-нибудь нужно править?

Возможно, в VSC или ST также можно поправить регулярку?

**Comment by nixel2007** [comment]
В ST и VSC работает

**Comment by artbear** [comment]
Вики для Атома также поправил.
