### ISSUE TITLE
Добавить скрипты для упрощения редактирования кода

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/1c-syntax#185]
Народ, подскажите, как можно сделать всякие аналоги скриптов замены кода, которые мы делали в Снегопате.

Например, хочется, чтобы при вводе `++` слева от идентификатор сразу получалось выражение присваивания.
Т.е. вместо `Объект++` можно было получить `Объект = Объект + 1`

Подскажите и в Атоме, и в VSC, и в ST
Может быть, знаете полезные плагины, которые уже делают какую-то подобную работу для текстов на других языках?

Мне, главное, понять, где и что ковырять, дальше уже попробую разобраться.

@nixel2007 @bambr1975 @pumbaEO @kuntashov @vsuh помогите :)

**Comment by bambr1975** [comment]
Мне кажется, можно реализовать автозамену наподобие Emmet, чтобы срабатывало при нажатии Tab. Автоматически заменять, мне кажется, не нужно.

**Comment by artbear** [comment]
bambr1975 Подскажи, где/как можно пример поведения, которое ты предлагаешь, посмотреть?

**Comment by bambr1975** [comment]
в vs code emmet  встроенный, ему расширвение не нужно, он просто реагирует на tab  и разворачивает любую из конструкций http://docs.emmet.io/cheat-sheet/
Правда, он подключен только для расширений  'html', 'razor', 'css', 'less', 'scss', 'xml', 'xsl', 'jade', 'handlebars', 'ejs', 'hbs', 'jsx', 'tsx', 'erb', 'php', 'twig'

**Comment by bambr1975** [comment]
для sublime и atom есть расширение Emmet - работает аналогично

**Comment by artbear** [comment]
Да, я уже закачал себе Emmet, посмотрю.
А как нам для os-bsl-файлов такое заюзать?

**Comment by bambr1975** [comment]
надо делать перехватчик таба))) Артур, это не быстро. Но идея такая уже обсуждалась)))

**Comment by artbear** [comment]
А без таба, автоматом можно? ++ и -- удобнее автоматом, другие нужно изучать.
или по хоткею хотя бы

**Comment by bambr1975** [comment]
хоткей - это таб. Разве нет?

**Comment by artbear** [comment]
я думал, какая-то сложность именно с табом :)
А в целом, без разницы какой хоткей выбирать.

**Comment by artbear** [comment]
Так что можно сделать? с чего начать?

**Comment by bambr1975** [comment]
ты сам хочешь делать?

**Comment by bambr1975** [comment]
никакой сложности. Делай

**Comment by artbear** [comment]
Так я не знаю, с чего начать, поэтому и прошу небольших подсказок, куда идти и что смотреть.
может быть, есть исходники примеров обработки текущего выделения

**Comment by bambr1975** [comment]
динамические шаблоны в vs code оборачивают текущее выделение. Если тебе нужно именно это - пользуйся ими

**Comment by artbear** [comment]
А в Атоме?

**Comment by bambr1975** [comment]
не знаю. Смотри, как расширение emmet реализовано

**Comment by nixel2007** [comment]
@artbear выше все уже @bambr1975 рассказала. Для VSC сейчас есть динамические шаблоны. но они срабатывают только по выделенному тексту и по нажатию ctrl-q. За автозамену отвечает плагин emmet (вроде есть для всех трех редакторов), но я его не ковырял.

**Comment by ret-Phoenix** [comment]
Артур, в ST есть макросы. Запись действий пользователя Ctrl + Q. Потом можно назначить хоткей на макрос. Пример работы прилагаю (do++)
`[
	{
		"args":
		{
			"by": "words",
			"extend": true,
			"forward": false
		},
		"command": "move"
	},
	{
		"args": null,
		"command": "copy"
	},
	{
		"args":
		{
			"by": "characters",
			"forward": true
		},
		"command": "move"
	},
	{
		"args":
		{
			"characters": " ="
		},
		"command": "insert"
	},
	{
		"args":
		{
			"characters": " "
		},
		"command": "insert"
	},
	{
		"args": null,
		"command": "paste"
	},
	{
		"args":
		{
			"characters": " + 1;"
		},
		"command": "insert"
	}
]
`
+ вызов макроса по хоткею: [
	{ "keys": ["Ctrl+3"], "command": "run_macro_file", "args": {"file": "Packages/User/do++.sublime-macro"} }
]

**Comment by artbear** [comment]
@ret-Phoenix Спасибо, но меня интересует Атом и VSC
