### ISSUE TITLE
Форматирование текста по Alt-Shift-F

### ISSUE THREAD

**Issue by vsuh** [xDrivenDevelopment/1c-syntax#189]
очень полезная, я считаю, функция.

**Comment by nixel2007** [comment]
Пока повешу метку VSC, потому что в остальных редакторах есть такая функциональность хотя бы для отступов.

**Comment by anatolean** [comment]
Прошу прощения... 
TAB-а, на мой взгляд, вполне достаточно.

**Comment by artbear** [comment]
Руками выравнивать - это 20 век.
В 21 веке хочется уже автоматически

**Comment by nixel2007** [comment]
уже реализовано. На тестировании.

2016-06-21 16:04 GMT+03:00 Artur Ayukhanov <notifications@github.com>:
