### ISSUE TITLE
[ST] Публикация пакета

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#19]
In progress...

Документация по разработке пакетов:
* Sublime text
  * Официальная https://www.sublimetext.com/docs/3/packages.html
  * Неофициальная, с примерами http://code.tutsplus.com/tutorials/how-to-create-a-sublime-text-2-plugin--net-22685
  * Дистрибуция https://packagecontrol.io/docs/submitting_a_package

**Comment by nixel2007** [comment]
Запрос на добавление пакета в package control на рассмотрении.
https://github.com/wbond/package_control_channel/pull/5038

**Comment by nixel2007** [comment]
В ST описанием пакета является Description из репозитория.
@artbear Можешь, добавить описание в репо https://github.com/xDrivenDevelopment/sublime-language-1c-bsl ? Например `Syntax defenition rules for 1C:Enterpise 8` (у меня прав не хватает)

**Comment by artbear** [comment]
@nixel2007 Не пойму, что у тебя не получается.
Права выданы.
Жду подробностей

**Comment by nixel2007** [comment]
@artbear 
вот скрин моего репо, есть кнопка Edit у описания.
![1](https://cloud.githubusercontent.com/assets/1132840/11659075/63b1d982-9dd7-11e5-80fd-e76743969d7b.PNG)

Для проверки - скрин репо с пустым описанием:
![3](https://cloud.githubusercontent.com/assets/1132840/11659102/88a777e2-9dd7-11e5-97ff-c5a5137b56d6.PNG)

А вот из xDD:
![2](https://cloud.githubusercontent.com/assets/1132840/11659080/6831297c-9dd7-11e5-8ebb-74c135a71e8c.png)

**Comment by artbear** [comment]
Поправил

**Comment by artbear** [comment]
ИМХО вместо `Syntax defenition rules for 1C:Enterpise 8` 
нужно писать `Syntax definition rules for 1C:Enterpise 8` 
def **I** nition

**Comment by nixel2007** [comment]
@artbear поправил, спасибо.

**Comment by nixel2007** [comment]
Запрос на добавление пакета в репозиторий принят. Ждем обновления на сайте Package control (деплоя?)

**Comment by nixel2007** [comment]
@xDrivenDevelopment/1c-syntax Пакет для ST опубликован! 
https://packagecontrol.io/packages/Language%201C%20(BSL)

VSC на очереди.

**Comment by bambr1975** [comment]
>вместо Syntax defenition rules for 1C:Enterpise 8 
нужно писать Syntax definition rules for 1C:Enterpise 8 

Честно говоря, к https://github.com/xDrivenDevelopment/1c-syntax это тоже относится)))

**Comment by nixel2007** [comment]
@bambr1975 на этот репо у меня тоже прав нет :D 
@artbear дай похожие права, пожалуйста :)

**Comment by artbear** [comment]
До работы доеду, права выдам

пн, 21 Дек 2015, 11:07, Nikita Gryzlov <notifications@github.com>:
