### ISSUE TITLE
Поставка СП для стандартных библиотек (и не только)

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#194]
Есть идея включать публичное АПИ библиотек в стандартный СП для VSC.

Делать это можно как статически - при сборе пакета language-1c-bsl, так и динамически - через настройку путей к исходникам библиотек и описаниям АПИ.

**Comment by nixel2007** [comment]
Возможно так потребуется некий скрипт (как часть стандартной библиотеки, например), который будет формировать описание апи автоматически.

**Comment by nixel2007** [comment]
Дабы обсуждение не потерялось, а все же приходило бы на почту письмами счастья (:smile:), я залинкую:
@artbear 
@dmpas
@EvilBeaver 
@kuntashov 
@pumbaEO 
@ret-phoenix
@vsuh

**Comment by kuntashov** [comment]
Стандартную библиотеку можно включить как есть статично, но для приватных библиотек нужна поддержка динамического формирования.
