### ISSUE TITLE
Иконки для BSL-файлов

### ISSUE THREAD

**Issue by JohnyDeath** [xDrivenDevelopment/1c-syntax#200]
В VSC версии 1.5.0 [появилась возможность](https://code.visualstudio.com/updates#_workbench) ассоциировать и отображать иконки к типам файлов. За основу взят репозиторий: https://github.com/jesseweed/seti-ui , который также используется и в Atom.
Предлагаю создать иконку для BSL файлов и продвинуть ее в этот репозиторий и, соответственно, в VSC

**Comment by EvilBeaver** [comment]
дадада. и для односкрипта. Кто тут художник, подать его!

**Comment by JohnyDeath** [comment]
Да, про OS я что-то совсем забыл. Хотя в голове приоритет был именно у него

**Comment by Kirill** [comment]
Почему про ST забыли?

**Comment by EvilBeaver** [comment]
@Kirill насколько я знаю, в нем оказалось сложнее все расширять и реализовывать. Можете, например, взять себе и сопровождать. Думаю, @nixel2007 будет только рад.

**Comment by kuntashov** [comment]
Написал своему медиагеройскому дизайнеру, она нарисует свой вариант иконки для BSL под SetiUI, если народу понравится - предложим в качестве контрибьюшена)

**Comment by nixel2007** [comment]
@Kirill 

> Почему про ST забыли?

Под ST тяжело портировать наработки из VSC. Нельзя использовать node_modules, сильно другая логика работы с API, отсутствие нужных расширений и вообще там питон О_о

**Comment by nixel2007** [comment]
@kuntashov отличные новости, спасибо :)
Предлагаю что-нибудь минималистичное. Вроде букв 1C или os, как это сделано для JS, например.

**Comment by kuntashov** [comment]
@nixel2007 да, я такую установку и дал

**Comment by artbear** [comment]
>и вообще там питон О_о
@nixel2007 Эта фраза напомнила недавное воспоминание @kuntashov в Г+ про пхп и 1сник-а :)

**Comment by EvilBeaver** [comment]
@kuntashov а нельзя ему еще заказать логотип односкрипта в качестве контрибьюта?

**Comment by kuntashov** [comment]
@EvilBeaver у тебя есть какие-то идеи/пожелания по поводу логотипа?

**Comment by awa15** [comment]
\<troll>
![](http://25mb.ru/img/picture/Oct/02/22cf05a157b9c92cd1bd6361c9a9f05c/3.jpg)
\</troll>

**Comment by EvilBeaver** [comment]
@awa15 - убил! ))))))
@kuntashov есть, мне нравятся простые логотипы геометрические.

http://blog.iteedee.com/wp-content/uploads/2014/01/gradle-logo.png
https://www.lua.org/images/logo.gif

в таком духе

**Comment by kuntashov** [comment]
@EvilBeaver принято, попробуем

**Comment by awa15** [comment]
Воры! Украли название http://sl.rosbizinfo.ru/products/1.html

**Comment by kuntashov** [comment]
Критикуйте )
Мне нравится самый первый вариант - просто, узнаются очертания лого 1С, есть желтый, но ровно столько, чтобы не раздражать.

![ico-01](https://cloud.githubusercontent.com/assets/1042299/18444719/084c955a-7923-11e6-94dd-5a1daaa11d08.jpg)

**Comment by nixel2007** [comment]
Боюсь нам задницу-то надерут с таким лого :(

**Comment by kuntashov** [comment]
А какие варианты? Просто "1С" любым шрифтом написать - может быть претензия все равно.

**Comment by awa15** [comment]
Меня в свое время Доржи просил сменить логотип Tool_1CD, так как там тоже этот стиль использовался. И ещё, как будет выглядеть первый значок на светлом фоне?

**Comment by awa15** [comment]
Вариант - написать не 1С, а 1S))

**Comment by kuntashov** [comment]
Это все лукавство и формальность. Еще вариант - ждать официальной иконки, а потом все равно просить ее использовать в темах редакторов. А, имхо, самый правильный, попросить разрешения 1С - написать Аристархову, Грибанову. @allustin как ты думаешь, реально?

В конце концов, тут речь не о том, чтобы на бренде 1С заработать, а о том, чтобы наоборот, сделать его узнаваемым в среде, мало знакомой с 1С.

**Comment by nixel2007** [comment]
@kuntashov 
> просто, узнаются очертания лого 1С, есть желтый, но ровно столько, чтобы не раздражать.

я почему-то думал, что он будет оранжевый. Видимо, каждодневное видение иконки запуска 8.2/8.3 накладывает свое.

**Comment by kuntashov** [comment]
В данном случае как я понимаю, взят оттенок желтого, используемый во всем наборе (сравни с JS).

**Comment by pumbaEO** [comment]
мне нравится первый.

**Comment by nixel2007** [comment]
Управление Seti-UI особенно никому не передашь) максимум пулл-реквест с откатом или другой картинкой

**Comment by awa15** [comment]
Это иконки для bsl, для os предполагаются другие?

**Comment by JohnyDeath** [comment]
Мне тоже первый больше по душе, если конечно он будет нормально смотреться на светлом фоне.
А os пока безликий?

**Comment by pumbaEO** [comment]
@nixel2007 тогда спор считаю закрытым, если им надо будет пусть своих дизайнеров привлекают и пулл-реквест делают

**Comment by kuntashov** [comment]
По поводу .OS - имеет смысл сначала придумать/нарисовать логотип (выше с @EvilBeaver этот вопрос немного обсуждали), а потом уже на его основе - иконку.

Либо, есть такая идея: для 1Script'а на иконке использовать как раз `1S`.

У кого какие идеи?

Что касается *.bsl можно еще на иконке БГ нарисовать, вот отсюда заимствовать 
![vk_qc4wq](https://cloud.githubusercontent.com/assets/1042299/18450569/4614090e-793c-11e6-8b70-4db14a323495.png) (c) https://twitter.com/nburaliev

**Comment by EvilBeaver** [comment]
Мне нравится первый. С копирайтами неясно

**Comment by kuntashov** [comment]
> я почему-то думал, что он будет оранжевый. Видимо, каждодневное видение иконки запуска 8.2/8.3 накладывает свое.

Уточнил. Цвета в данной теме ограничены автором темы, примеры цветов здесь: https://github.com/jesseweed/seti-ui#more-colors

**Comment by allustin** [comment]
@EvilBeaver можно попробовать официально спросить, @kuntashov - ближайшая партнерка через несколько дней. Там можно будет задать вопрос о официальном логотипе языка в виде иконки.

Еще у нас есть официальный аватар //cc @1C-Company - https://avatars1.githubusercontent.com/u/11886198?v=3&s=400

Есть кстати виндовые иконки

![image](https://cloud.githubusercontent.com/assets/55323/18453167/ac028452-7946-11e6-914b-0dfcb822ebea.png)

но они ресурсы в рамках платформы, а значит их добыча связана с дизассемблированием.

Учитывая что вышла 1.3.0 - https://github.com/1C-Company/dt-demo-configuration/commit/a500777884b81bfc7b6602e51b84580d3c3b303e

Я бы предложил использовать вот это

![image](https://cloud.githubusercontent.com/assets/55323/18453239/f6f8d718-7946-11e6-9e78-35b8951e04ca.png)

На мой взгляд это совпадает с понятием добросовестное использование - https://en.wikipedia.org/wiki/File:1C_Company_-_Logo_(English_Version).jpg

https://en.wikipedia.org/wiki/Fair_use

P.S. Но я задачу понял - спрошу обязательно

**Comment by kuntashov** [comment]
> Я бы предложил использовать вот это

Такую в SetiUI врядли автор этого набора примет, тк. цвета не соответствуют, в readme темы написано явно:

> While, you can add additional colors to styles/ui-variables.less, but please do not do this unless you find it absolutely necessary. If you do add another color, please make sure that matches the general feel of the other colors. **If you add something really bright or really pale, your pull request will likely be declined**.

(выделено мной)

**Comment by JohnyDeath** [comment]
Да, текущая официальная аватарка 1С на гитхабе плохо подходит для иконки файлов, особенно для SetiUI

**Comment by allustin** [comment]
задал вопрос на партнерском форуме https://partners.v8.1c.ru/forum/topic/1525441

пока задавал вопрос - вспомнил что у нас есть еще MDO файлы и это не совсем BSL - хотя иконка будет скорее всего той же.

дополнительно погуглил - а что там на тему официального логотипа языка ABAP... Сходу не нашел.

**Comment by kuntashov** [comment]
MDO - это суть xml, а потому наверное логично, если у этого расширения будет иконка как у xml

> задал вопрос на партнерском форуме https://partners.v8.1c.ru/forum/topic/1525441

Спасибо! Единственное, есть опасение на вопрос "Будут ли...?" будет дан ответ "Пока такая возможность не рассматривалась, но мы запишем как пожелание".

Может быть переформулировать на "Можно ли... ?" 
Так или иначе, крайне сомневаюсь, что 1С возьмется рисовать иконки специально под какие-то сторонние редакторы и тем более под отдельные темы.

В общем, я предлагаю использовать ту иконку, которая нам нравится.

Даже гипотетически не могу представить, какие и на основании чего могут быть за это какие-то санкции. Прямого отношения Seti UI и какая бы то ни было другая тема для редактора кода к 1С не имеет. Какие-то негативные маркетинговые последствия от того, что появится такая иконка, сложно представить.   

Мне попросить дизайнера оформить результат работы, чтобы его можно было использовать для PR в Seti UI (экспортнуть в SVG и т.п.) или подождем ответа от 1С?

**Comment by pumbaEO** [comment]
Поддерживаю Сашу:
1. я против MDO
2. готовить pull, т.к. будет "мы подготовили письменное обоснование (хотя есть для этого документооборот) и оно находится у руководства на согласовании"  и фиг его поймешь, есть ли у руководства KPI по показателям "количество висящих к согласованию документом <1 дня, > 7 дней и т.д. "

**Comment by EvilBeaver** [comment]
@kuntashov а можно я в качестве оффтопика спрошу, есть ли надежда на логотип 1скрипт?

**Comment by kuntashov** [comment]
@EvilBeaver попробуем конечно, сегодня оформит по иконке все необходимое (там надо в нескольких форматах выгрузить, в CSS-ках прописать все как нужно) и я тогда попрошу набросать варианты по лого для 1скрипту

**Comment by artbear** [comment]
Согласен с Сашей (смайлик-руку добавил).
Нужно брать ту иконку, что нравится нам, и не заимствована из официальных знаков 1С.

**Comment by allustin** [comment]
@kuntashov в целом я поддерживаю и согласен с @pumbaEO - готовить pull request

наш пул-реквест согласно GitHub и законодательства США будет подразумевать добросовестное использование, в противном случае существует кнопка Report Abuse для не согласных.

**Comment by JohnyDeath** [comment]
Еще вот сюда можно запулить? https://github.com/robertohuertasm/vscode-icons

**Comment by nixel2007** [comment]
Можно, конечно :)

**Comment by JohnyDeath** [comment]
А потом еще и вот сюда строку? https://github.com/robertohuertasm/vscode-icons/blob/master/src/build/supportedExtensions.js )

**Comment by kuntashov** [comment]
@EvilBeaver по цветам логотипа у тебя есть какие-то предпочтения или наоборот, цвета которые ты бы категорически не хотел использовать?

**Comment by EvilBeaver** [comment]
@kuntashov я готов рассматривать любые варианты. Хотя люблю сдержанные цвета. Типа зеленого, как на кнопке Скачать в oscript.io. Но это не обязательно, пусть творит свободно )

**Comment by kuntashov** [comment]
@EvilBeaver принято!

**Comment by nixel2007** [comment]
Поступила информация, что 1С через пару дней нам предоставит официальные иконки для использования на правах fair-use.

@kuntashov Спасибо тебе и твоему дизайнеру за помощь! Но svg-верстку bsl-иконки можно пока притормозить

**Comment by kuntashov** [comment]
Ок, спасибо, что предупредил.

**Comment by pumbaEO** [comment]
Подождем до понедельника :)

**Comment by allustin** [comment]
официально утвержденные иконки - прислал Петр Грибанов. можно вставлять.

**Comment by JohnyDeath** [comment]
@allustin а где они?

**Comment by nixel2007** [comment]
@JohnyDeath у меня в почте. Попробую запилить.

**Comment by nixel2007** [comment]
Включены в SETI и в file-icons.
В VSC видимо скоро обновятся
