### ISSUE TITLE
Различается отображение директив компиляции и инструкций препроцессору

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#203]
Хотя по факту это одно и то же.

**Comment by nixel2007** [comment]
Исправлено в #202

**Comment by EvilBeaver** [comment]
@nixel2007 чойто вдруго это одно и то же? Первое препроцессор, второе атрибут метода. К цветам отношения не имеет, конечно)

**Comment by nixel2007** [comment]
Понимаешь в чем дело... И то и то влияет на то, какой в итоге получится
модуль. Директива может ещё лишать и давать форменный контекст, но это
можно обыграть как отдельный модуль с ограниченной областью видимости...

Ключевой вопрос тут был является ли директива storage.modifier или это же
все же ближе к препроцессору с его keyword.other.

Хотелось бы услышать твоё мнение на этот счёт, как человека, который
занимается лексерами и грамматиками (оскрипт).

Может быть ещё Валерий (@awa15) что-то сможет сказать на этот счёт. (у меня
сформировалось мнение, что Валерий может вообще всё :) )

25 сент. 2016 г. 10:16 PM пользователь "Andrei Ovsiankin" <
notifications@github.com> написал:
>
> @nixel2007 чойто вдруго это одно и то же? Первое препроцессор, второе
атрибут метода. К цветам отношения не имеет, конечно)

**Comment by EvilBeaver** [comment]
storage.modifier это что вообще? Что им рекомендуется помечать, какой именно storage?

@awa15 может даже больше, чем все. Мы привыкли.

**Comment by nixel2007** [comment]
@EvilBeaver я думал, ты эту страницу успел выучить наизусть в том году)

**Comment by EvilBeaver** [comment]
@nixel2007 возраст, знаете ли. Сам себя-то порой не помню, не то чтоб модифаеры всякие со сторэйджами.

**Comment by awa15** [comment]
@nixel2007 , @EvilBeaver , спасибо за столь лестное мнение обо мне. Придётся отвечать))
По сути, с помощью директив компиляции, также как и с помощью инструкций препроцессора в одном исходном модуле описываются сразу несколько модулей. Один модуль исполняется на клиенте, другой на сервере, третий на сервере без контекста. Я когда-то с этим немного разбирался, подробностей сейчас не помню, но, как мне помнится, для каждой директивы компиляции (а их всего 5) 1С компилирует отдельный модуль. Увидеть это можно на примере cf-файла мобильного приложения, а также файла 1cema.xml. Формат cf мобильного приложения немного отличается от формата обычного cf. Одно из отличий состоит в том, что в cf мобильного приложения все модули хранятся без исходных текстов, в скомпилированном виде. Даже модули управляемых форм. И хранятся скомпилированные модули управляемых форм в 4-х отдельных файлах, по одному скомпилированному модулю для каждой из 4-х доступных для управляемых форм директив компиляции (&НаКлиенте, &НаСервере, &НаСервереБезКонтекста, &НаКлиентеНаСервереБезКонтекста).
Собственно, из всего вышесказанного я делаю вывод, что директивы компиляции - это другая форма инструкций препроцессора. Как конкретно 1С внутри себя реализовала обработку директив компиляции, на стадии препроцессинга или на стадии компиляции - не так уж и важно, имхо. Главное, что смысл директив компиляции, но мой взгляд, тот же, что и у инструкций препроцессора.

**Comment by nixel2007** [comment]
@awa15 спасибо за столь развернутый ответ :)

**Comment by rsyuzyov** [comment]
Не могу удержатся... "Ходят слухи, что один человек уже написал 1Cv9, но злые маги Боринур и Сергенур наложили чары, которые рассеются только через несколько лет, и только тогда 1Cv9 увидят люди..." @awa15, признавайтесь, это Вы!?

**Comment by awa15** [comment]
Это суровый ОФФ, Поэтому, прошу прощения.
@rsyuzyov , давайте рассуждать логически. Какие версии 1С мы знаем?
6.0
7.0
7.5
7.7
8.0
8.1
8.2
8.3
(8.4 пока есть только превью)
Время между каждой версией где-то 3-5 лет, эта тенденция примерно сохраняется, а вот дельта между версиями постоянно уменьшается. Экстраполируя такое поведение, до 9.0 мы можем и не дожить. Есть мнение, что конец света будет сразу после выхода 1С 8.8. Так что нет, это не я))

**Comment by CryptedSky** [comment]
Заголовок не совсем точно отображает суть, вернее было б "Различается отображение директив компиляции и прочих ключевых слов (Знач, Экспорт)";

А если оффтопить про отличие от инструкций сопроцессора, то 
мне кажется, что 1С ввели директивы, только для удобства разработчиков, чтобы не пришлось процедуры формы описывать как
```
#Если Сервер тогда
Процедура ХХХ() Экспорт; Контекст; //привет 7.7
...
#КонецЕсли;
```
Кстати, одинэсный хайлайтер их не различает.

**Comment by nixel2007** [comment]
@CryptedSky одинесный хайлайтер много чего не различает...

**Comment by EvilBeaver** [comment]
Я позволю себе дополнить @awa15 

Препроцессор в 1С - это реальный препроцессор, который является фильтром лексем, поступающих в парсер языка. Директивы же, это инструкции уже парсера (компилятора). Де-факто, это получается "дополнение" к препроцессору, поскольку на выходе получаются разные модули.

Препроцессором мы можем кромсать код как угодно, например:

    #Если Клиент Тогда
        Процедура
    #Иначе 
        Функция
    #КонецЕсли
    МояПроцедуроФункция() Экспорт

т.е. мы формируем текст, который будет отдан компилятору. А тот, в свою очередь, сделает N исполняемых модулей, согласно директивам, "разбрасывающим" синтаксические конструкции по контекстам выполнения.

**Comment by nixel2007** [comment]
@EvilBeaver 
> #Если Клиент Тогда
    Процедура
#Иначе 
    Функция
#КонецЕсли
МояПроцедуроФункция() Экспорт

как тебе только в голову такое пришло... 

Я с тобой согласен по поводу роли инструкций препроцессору и директив компиляции (а еще появились аннотации, хей-хей!). Вопрос-то... это keyword.other или storage.modifier?)

**Comment by EvilBeaver** [comment]
@nixel2007 ну, поскольку, аннотации это не разу уже не keyword, а целая синтаксическая конструкция со скобками и параметрами, то, пожалуй, storage подойдет больше.

**Comment by nixel2007** [comment]
@EvilBeaver а препроцессор - куда он на твой взгляд?

**Comment by EvilBeaver** [comment]
Гдянь в сишарпе или плюсах, куда отнесен

**Comment by nixel2007** [comment]
В плюсах препроцессор относен к keyword.control.
В `до-диез-мажоре` - к directive.preprocessor - но это пространство имен не поддерживается стандартными цветовыми темами Sublime Text.
Заодно заглянул в java и ее аннотации - они расцениваются как `storage.type.annotation.java`

В связи с этим мне видится такое решение:
1) Препроцессор - keyword.other.preprocessor (как сейчас)
2) Директивы компиляции - откатить до storage.modifier
3) Аннотации - перевести на storage.modifier или storage.type, по аналогии с java.

discuss?

**Comment by EvilBeaver** [comment]
agreed. За до-мажор отдельный респект )
