### ISSUE TITLE
Определить в файле 1c-query.YAML-tmLanguage доступные расширения для файлов

### ISSUE THREAD

**Issue by andreevlex** [xDrivenDevelopment/1c-syntax#216]
Есть ли стандартное расширение для файлов 1C(Query)?
**Пример 1**
Расширение файла `*.txt`
Atom - не определяет по первой строке
Sublime text - определяет по первой строке
VS code - не определяет по первой строке
**Пример 2**
Расширение файла `*.sdbl`
Atom - опредедяет по расширению
Sublime text - определяет по расширению и первой строке
VS code - не определяет по расширению и первой строке

**Comment by nixel2007** [comment]
Официального стандартного расширения нет, 1с не сохраняет файлы запросов отдельно от bsl. Как вариант можно использовать sdbl. 

Какой сценарий использования? Сохраняете тексты запросов в отдельных файлах?

**Comment by andreevlex** [comment]
Думаю получение данных через `ComConnector`, самое частое применение.
Да можно `sdbl`, а если какое другое расширение, то тут пользователь сам пусть выбирает тип файла.

**Comment by nixel2007** [comment]
> В настройках VSC увидел, что 1C(Query) определяет по расширению файлов .query, тоже вариант подходящий.

Это обход какого-то из багов vsc. Без него файл вообще не сохранялся :)
