### ISSUE TITLE
Инструкция разработчика

### ISSUE THREAD

**Issue by EvilBeaver** [xDrivenDevelopment/1c-syntax#22]
Нужно пошаговое описание - как настроить окружение разработчика, который захочет внести правки в пакеты. Как собрать пакеты, как отладить и т.п.

**Comment by nixel2007** [comment]
Первым делом как раз хочу этим заняться.

**Comment by EvilBeaver** [comment]
@nixel2007 ну так ты ведешь проект, тебе и приоритеты расставлять.

**Comment by nixel2007** [comment]
Добавил инструкцию по редактированию грамматики в ST.
@EvilBeaver Доступно или еще что-то добавить?

**Comment by EvilBeaver** [comment]
>git push
>git tag "v<version>"
>git push origin "v<version>"

Может первая команда это pull?

**Comment by nixel2007** [comment]
@EvilBeaver `git pull` сейчас выполняется в рамках билдера (т.к. билдер сейчас еще и коммит делает).

Откорректирую этот кусок как поправлю билдер (#23)

**Comment by nixel2007** [comment]
Добавил информацию по настройке окружения и сборке.

**Comment by nixel2007** [comment]
Обновил блок разработки пакетов под Атом.
/cc @artbear

**Comment by artbear** [comment]
@nixel2007 
>Обновил блок разработки пакетов под Атом.

>* Выполните команду `apm develop language-1c-bsl`
* Перейдите в папку
`%userprofile%\.atom\dev\packages\language-1c-bsl`
* При необходимости переключитесь на нужную ветку репозитория `git`
* Выполните команду `apm install` для установки зависимостей пакета
* Откройте папку пакета в Atom в режиме разработчика или выполните команду
`atom --dev .`

Попробовал по этой инструкции
1 Ошибка на `apm install` (у меня Windows 7)
```
C:\Users\ayukhanov\.atom\dev\packages>apm install
Installing modules failed
npm ERR! install Couldn't read dependencies
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\ayukhanov\\AppData\\Local\\atom\\app-1.3.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\ayukhanov\\AppData\\Local\\atom\\app-1.3.2\\resources\\app\\apm\\node_modu
les\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\ayukhanov\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\ayukhanov\\.atom\\.apmrc" "install" "--target=0.34.3" "--arch=ia32" "--msvs_v
ersion=2013"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! path C:\Users\ayukhanov\.atom\dev\packages\package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno 34

npm ERR! package.json ENOENT, open 'C:\Users\ayukhanov\.atom\dev\packages\package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.
```

2 Далее открываю Atom в режиме разработчика, вижу наш package в Dev.packages, а package для основного режима удален
Все красиво, есть описание, ссылки и прочее, но активна кнопка Enable (т.е. сейчас плагин неактивен) и при открытии *.os никакой расцветки не происходит.

Что не так?

**Comment by nixel2007** [comment]
1. amp install надо выполнять в папке пакета `dev/packages/language-1c-bsl`
2. Возможно из-за неустановленных зависимостей как раз. Попробуй

**Comment by artbear** [comment]
1 Ты прав, я выходил из папки. apm install отработало верно.
2 здесь ничего не изменилось - активна кнопка Enable (т.е. сейчас плагин неактивен) и при открытии *.os никакой расцветки не происходит.

**Comment by artbear** [comment]
Странно - нажимал Enable несколько раз, не работало, написал на Гитхаб, вернулся в Atom и еще несколько раз понажимал и заработало :)
Раскраска появилась.

**Comment by artbear** [comment]
@nixel2007 В `CONTRIBUTING.md` я добавил 
`В открывшемся окне настройке нужно найти раздел Development packages, далее найти наш пакет language-1c-bsl и разрешить его (нажать кнопку Enable), если эта кнопка активна`

**Comment by nixel2007** [comment]
@artbear ок, спасибо!

**Comment by nixel2007** [comment]
В целом доделал.
