### ISSUE TITLE
Создать скрипт сборки пакетов для редакторов в Linux

### ISSUE THREAD

**Issue by andreevlex** [xDrivenDevelopment/1c-syntax#224]

**Comment by nixel2007** [comment]
OneScript кроссплатформенный. Apm и vsce - вроде тоже. Что ещё нужно?

**Comment by andreevlex** [comment]
скрипт `build.os` использует следующий код
`Процесс = СоздатьПроцесс("cmd.exe /C " + ОбернутьВКавычки(КомандаЗапуска), РабочийКаталог, Истина, , КодировкаТекста.UTF8);`
Вот это мне кажется не кроссплатформенно.

**Comment by nixel2007** [comment]
Согласен надо перетащить из гитраннера реализацию

**Comment by andreevlex** [comment]
Пробую переделать реализацию под linux скрипта build.os.
В командах еще используется `\` характерный для Windows, тоже не кроссплатформенно.

**Comment by nixel2007** [comment]
@andreevlex https://github.com/nixel2007/gitrunner/blob/develop/src/Классы/ГитРепозиторий.os#L504

**Comment by andreevlex** [comment]
Надо еще написать в документацию, что в linux исполняемый файл называется `nodejs` и для того, чтобы можно было вызывать как `node` надо поставить пакет `sudo apt install nodejs-legacy`

**Comment by andreevlex** [comment]
#228 оптимизировал код немного

**Comment by nixel2007** [comment]
Закрываю, решено
