### ISSUE TITLE
Переименовать 1c-scrypt в 1c-syntax (1c-script?) в CONTRIBUTING.md

### ISSUE THREAD

**Issue by kuntashov** [xDrivenDevelopment/1c-syntax#24]
Нужно переименовать `1c-scrypt` судя по смыслу текста в `1c-syntax` (по имени репо проекта) в [CONTRIBUTING.md](https://github.com/xDrivenDevelopment/1c-syntax/blob/master/CONTRIBUTING.md), если это опечатка (есть подозрение, что это так).

Ну и имена других реп в тексте отличаются от реальных имен.

**Comment by nixel2007** [comment]
Исправлено, спасибо!
