### ISSUE TITLE
Лицензирование

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#25]
По умолчанию пакеты для редакторов лицензируются под MIT.
Часть продуктов xDD лицензируется под Apache, vanessa-stack вообще под BSD (хотя это  продукт silverbulleters и к организации xDD относится постольку-поскольку).

Что выберем?

**Comment by vsuh** [comment]
MIT короче

**Comment by allustin** [comment]
@nixel2007 тут вопрос цели, лицензия выбирается "под цель". ;-).

То есть отчего хочешь защититься и что хочешь разрешить. Собственно MIT если мне не изменяет память, как и Apache и BSD разрешительные лицензии. С небольшими оговорками каждая.

http://choosealicense.com/licenses/

для vanessa-stack мы выбрали New BSD только для того, чтобы некоторые нехорошие товарищи не могли использовать наши имена в качестве "собственной рекламы", а то надоели уже - даже в LinkeIn начали вставлять без разрешения. 

MIT самая простая - разрешает использование и не предоставляет гарантий "ибо нефиг"
Apache - разрешает использование в сторонних патентах в отличии от MIT и BSD, но требует использования торговых марок ;-)
BSD - не дает право использования в сторонних патентах, и запрещает использование торговых марок.

но это все открытые лицензии, так что вопрос выбора только в мелочах "защиты" - чего ты (вы) не хотите чтобы произошло.

**Comment by nixel2007** [comment]
Можно поподробнее про ситуацию с Апачем? Могут возникнуть конфликты с родительской 1С?  
Если да, то BSD в этом плане еще суровее?

Я, в свою очередь, хочу нескольких вещей:
* соблюдение (но это и так никто не отнимет) и указание авторских прав, как собственных, так и всей команды xDD/1c-syntax
*  Стимуляцию развития родительского пакета в данном репозитории, хотя бы через ссылки в информации и обнародование модифицированных исходников (в идеале с указанием значительных изменений, как это делает Apache, но этот пункт не обязателен).

**Comment by nixel2007** [comment]
Хотя требование публикации - это уже лицензии уровня GPL, если мне память не изменяет.
Сложно все это :(

Хотелось бы услышать мнения @artbear и @EvilBeaver.
@vsuh высказался за MIT.

**Comment by allustin** [comment]
@nixel2007 если коротко, то Apache разрешает Patent Use Code для стороннего товарища. То есть я могу запатентовать технологию в которую добавлю исходный код продукта Apache другого вендора то есть тебя - именно поэтому кстати Apache требует вставки лицензии в каждый файл исходного кода.

Что касается твоих желаний, то первое достижимо с помощью Apache и BSD
Второе - это больше похоже на BSD лицензию, чем на Apache.

MIT ни первого ни второго не даёт - насколько я знаю и меня консультировали юристы.

P.S. И еще - ни в одной лицензии нет понятия команда - либо организация, либо автор. Организация - это либо что-то некоммерческое и общественное, требующее регистрации. Либо юридическое - требующее регистрации. Мы уже на это нарвались.

**Comment by nixel2007** [comment]
> P.S. И еще - ни в одной лицензии нет понятия команда - либо организация, либо автор

Возможен ли список авторов?  

Спасибо за разъяснение!

**Comment by artbear** [comment]
@allustin 
>если коротко, то Apache разрешает Patent Use Code для стороннего товарища. То есть я могу запатентовать технологию в которую добавлю исходный код продукта Apache другого вендора то есть тебя - именно поэтому кстати Apache требует вставки лицензии в каждый файл исходного кода.

Очень кстати всплыл вопрос о лицензионной чистоте и вставке лицензий!

Напоминаю, что в исходниках vanessa-ХХХ нет никакого указания на Apache-лицензии от xUnitFor1C (файлы лицензий xUnitFor1C не вставлены, в коде нет указания лицензии) Т.е. вы явно нарушаете лицензионное соглашение Apache от нашего продукта!

Я уже неоднократно сообщал об этом тебе и sb, писал issue, но воз и ныне там, ты не хочешь вставить лицензии из каких-то личных соображений!

Так что говоря о "нехороших" людях, помни в первую очередь о себе и своей честности.

**Comment by allustin** [comment]
@artbear я не тебя имел ввиду, чего это ты на свой счет воспринял ? Хотя ты и пытался использовать моё имя в докладе на Инфостарте без согласования со мной, в данном контексте я использовал других товарищей из двух буквенных компаний.

Что касается обсуждения лицензионной чистоты xUnitFor1C и её кода - я уже неоднократно тебе отвечал на твои претензии. И как ты помнишь - все остались при своём "до лучших" времен.

Если уж хочешь получить очередную торпеду - то вставь в каждый файл исходного кода в шапку текст лицензии Apache чтобы на неё ссылаться https://github.com/xDrivenDevelopment/xUnitFor1C/blob/develop/src/xddTestRunner/ObjectModule.txt  
Это как бы требование ;-) Поэтому мы кстати и отказались от Apache.

@nixel2007 я только сейчас понял - что у вас же "организация", сделаешь что-нибудь для вас - потом проблем не оберешься.

**Comment by allustin** [comment]
@artbear здесь я поделился своим опытом по лицензионной чистоте и защите авторского кода, а также защите контрибьюции не связанного напрямую с кодом.

последняя оказывается также защищается - чтобы не получить проблем такие как у меня с Артуром - существует специальное соглашение (используется самим GitHub https://cla.github.com/)

**Comment by artbear** [comment]
>@artbear я не тебя имел ввиду, чего это ты на свой счет воспринял ? Хотя ты и пытался использовать моё имя в докладе на Инфостарте без согласования со мной, в данном контексте я использовал других товарищей из двух буквенных компаний.

Я не про себя вспоминал, а именно по нерешенной проблеме лицензионной чистоты с использованием кода xUnitFor1C

>Что касается обсуждения лицензионной чистоты xUnitFor1C и её кода - я уже неоднократно тебе отвечал на твои претензии. И как ты помнишь - все остались при своём "до лучших" времен.

Если считать, что ты ничего не сделал, дабы соблюсти лицензию, тогда, да, все остались при своём :(

>Если уж хочешь получить очередную торпеду - то вставь в каждый файл исходного кода в шапку текст лицензии Apache чтобы на неё ссылаться https://github.com/xDrivenDevelopment/xUnitFor1C/blob/develop/src/xddTestRunner/ObjectModule.txt
Это как бы требование ;-) Поэтому мы кстати и отказались от Apache.

Это неполное требование. Можно выбрать либо положить в код исходника либо положить в корень проекта файл лицензии от заимствованного продукта или включать лицензию в файл `notice`
Как раз чтобы не вставлять в каждый файл лицензию.

**Comment by allustin** [comment]
@artbear мои комментарии в данном задаче используют лицензию ![Лицензия Creative Commons"](https://i.creativecommons.org/l/by-nc-nd/4.0/80x15.png)

Буду теперь вставлять всегда ;-)

**Comment by allustin** [comment]
@artbear - ты мне лучше напомни как дела с добавлением моей фамилии в текст лицензии xUnit 
![Лицензия Creative Commons"](https://i.creativecommons.org/l/by-nc-nd/4.0/80x15.png)

**Comment by artbear** [comment]
>@artbear - ты мне лучше напомни как дела с добавлением моей фамилии в текст лицензии xUnit 
Впервые слышу, что нужно тебя вставить.
ты же дистанцировался от проекта?

Согласен, нужно тебя добавить. 

но хотелось бы решить в 2стороннем порядке - исправляем лицензию xUnitFor1C и исправляем лицензии на использование xUnitFor1C в продуктах vanessa-ХХХ
тогда вопросов по лицензионной чистоте ни у кого не останется и мы, наконец-то, закроем этот вопрос.

Что скажешь?

**Comment by allustin** [comment]
@artbear сделал мой день. Умудрился испортить отношения на ровном месте. С тобой поделились исследованиями - безвозмездно и граблями на которые уже нарвались, а ты в ответ что ?

(с) Ну и сиди "как дура без подарка".

![Лицензия Creative Commons"](https://i.creativecommons.org/l/by-nc-nd/4.0/80x15.png)

**Comment by artbear** [comment]
@allustin >Умудрился испортить отношения на ровном месте

Я же уже писал
>Если считать, что ты ничего не сделал, дабы соблюсти лицензию, тогда, да, все остались при своём :(

Ситуация повторяется :(

Я предложил тебе нормальные варианты решения проблемы, но

Опять от тебя общие слова и уход от ответов.

**Comment by nixel2007** [comment]
Оставлен mit
