### ISSUE TITLE
Удалить из регулярных выражений 1C(SDBL) "\s+"  в ключевых полях состоящих из нескольких слов

### ISSUE THREAD

**Issue by andreevlex** [xDrivenDevelopment/1c-syntax#252]
Например в выражении `В\s+ИЕРАРХИИ` надо заменить на `В\sИЕРАРХИИ` и так же в остальных лексемах.

**Comment by nixel2007** [comment]
Почему? Разве там не может быть несколько пробелов или даже перевод строки?

**Comment by andreevlex** [comment]
Действительно редактор запроса в конфигураторе позволяет внести несколько пробелов. 
Выглядит странно, но да ладно.
