### ISSUE TITLE
[Atom] oscript-запускатель

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#26]
Для разработки запускателя oscript в Atom, видимо, так же потребуется описывать часть процедур по запуску в `coffee` файлах внутри пакета.  
Пример пакета, работающего по ctrl+r https://github.com/lsegal/atom-runner

**Comment by vsuh** [comment]
@EvilBeaver Андрей, shebang будет обрабатываться?
Сейчас текст

```bsl
    #!c:/progra~2/onescript/bin/oscript.exe
    Функция тест()
      Сообщить("Привет!");
    КонецФункции
    тест();
```

выводит:


`{Модуль E:\_git_\test\test.os / Ошибка в строке: 2 / Неизвестная директива: !(!c:/progra~2/onescript/bin/oscript.exe)}`

**Comment by nixel2007** [comment]
@vsuh а шебанг на win-системах вообще имеет смысл?4
Да и отличие в путях к oscript на win и *nix напрягает
Atom-runner я привел в качестве примера реализации команд, не обязательно привязываться к шебангу :)

**Comment by EvilBeaver** [comment]
Шебанги только без бом метки если

-----Исходное сообщение-----
От: "vsuh" <notifications@github.com>
Отправлено: ‎10.‎12.‎2015 13:58
Кому: "xDrivenDevelopment/1c-syntax" <1c-syntax@noreply.github.com>
Копия: "Andrei Ovsiankin" <ovsiankin.aa@gmail.com>
Тема: Re: [1c-syntax] [Atom] oscript-запускатель (#26)

@EvilBeaver Андрей, shebang будет обрабатываться?
Сейчас текст
    #!c:/progra~2/onescript/bin/oscript.exe
    Функция тест()
      Сообщить("Привет!");
    КонецФункции
    тест();
выводит:
{Модуль E:\_git_\test\test.os / Ошибка в строке: 2 / Неизвестная директива: !(!c:/progra~2/onescript/bin/oscript.exe)}

**Comment by vsuh** [comment]
ух ты! работает

**Comment by nixel2007** [comment]
Билдер и создание билд-провайдера - пакет [atom-build](https://github.com/noseglid/atom-build)

**Comment by nixel2007** [comment]
Реализован запускатель с помощью atom-script.
Необходимо описать работу на wiki.

**Comment by nixel2007** [comment]
Добавлено описание на вики. Добавлена ссылка в ридми.
Готово к релизу
