### ISSUE TITLE
Перевод строки после строкового литетала с // добавляет комментарий на новую строку 

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#260]

**Comment by nixel2007** [comment]
Вероятно регулярка не учитывает нахождение внутри строки. 
Проверить для остальных редакторов.

**Comment by EvilBeaver** [comment]
А еще раздражает, когда в конце функции стоит камент с ее именем (так делают шаблоны). Добавляешь ентер и оно каменты пишет.

**Comment by nixel2007** [comment]
Оно вообще дожно работать только по шифт-энтеру вроде  :(

**Comment by kuntashov** [comment]
> А еще раздражает, когда в конце функции стоит камент с ее именем (так делают шаблоны). Добавляешь ентер и оно каменты пишет.

На всякий случай напомню.

В ОпенКонфе с плагином keyboard было сделано очень удобно: нажатие `Enter` в конце строки-комментария приводило к добавлению новой строки, начинающейся с символа комментария, а если нажать повторно, оставив коммент в текущей строке пустым, то удаляло символы комментария и новую строку не добавляло больше. Т.е. работало вот так (символом `|` обозначена позиция курсора):

1. Исходное состояние:

```bsl
...
КонецФункции // МояФункция() |
```
2. Нажимаю `Enter`, получаю:

```bsl
...
КонецФункции // МояФункция() 
// |
```
3. Нажимаю `Enter` повторно, получаю:

```bsl
...
КонецФункции // МояФункция() 
|
```

Нажатие Shift+Enter позволяло вставить новый коммент независимо от того, что в текущей строке коммент пустой:

4. Если в состоянии 2 нажимаю `Shift+Enter`, то получаю:

```bsl
...
КонецФункции // МояФункция() 
//
// |
```
