### ISSUE TITLE
[VSC] Добавить генерацию шаблонного tasks.json c наиболее популярными задачами

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/1c-syntax#262]
Предлагаю добавить генерацию шаблонного tasks.json c наиболее популярными задачами
А еще проще - просто подставлять шаблонный файл.

Сейчас у нас уже фактически устоялся набор задач для разработчика скриптов
+ запуск скрипта через oscript, компиляция, проверка (уже есть в генерилке)
+ 2 вида тестирования через 1testrunner (полное + текущий файл теста)
+ несколько видов тестирования через 1bdd + генерирование шагов через 1bdd
+ сборка пакета для opm

И в разные проекты приходится копировать один и тот же шаблонный файл.

В качестве шаблона предлагаю взять https://github.com/artbear/1commands/blob/master/.vscode/tasks.json
Этот файл уже проверен на нескольких проектах.

PS а когда перейдем на команды opm, тогда просто заменим текст шаблонного файла, т.к. набор задач все равно не изменится.

**Comment by JohnyDeath** [comment]
Вот здесь оно и должно быть ;)

**Comment by nixel2007** [comment]
Принято.
