### ISSUE TITLE
[VSC] language-1c-bsl.expandAbbreviation вызывает проблемы при смене отступов

### ISSUE THREAD

**Issue by ebugusey** [xDrivenDevelopment/1c-syntax#263]
#### Последовательность действий
1. Открыть файл `*.bsl`.
2. Изменить отступы на пробелы.
3. Нажать `Tab`.
#### Что получилось
Вводятся табы.
#### Ожидаемый результат
Если текущий режим отступов пробелы, то должны вводится пробелы при нажатии `Tab`.
#### Примечание
Проблема в настройке `language-1c-bsl.expandAbbreviation`, которая по умолчанию назначена на `Tab`.

**Comment by nixel2007** [comment]
Спасибо за репорт. Проглядели
