### ISSUE TITLE
[ST] oscript-запускатель

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#27]
На первый взгляд, для разработки запускателя oscript под ST потребуется просто добавить пару конфиг-файлов в пакет.

Подробнее: http://docs.sublimetext.info/en/latest/reference/build_systems.html

**Comment by nixel2007** [comment]
Готова и описана билд-система, добавлена информация по использованию на wiki.
Готово к релизу.

**Comment by JohnyDeath** [comment]
А без такой жесткой вставки аргументов в файл можно как-то обойтись? Желательно так, чтобы параметры можно было бы задавать в момент запуска (как в NppExec для N++) ?

**Comment by kuntashov** [comment]
@JohnyDeath штатными средствами никак
Можно написать плагин.

**Comment by JohnyDeath** [comment]
Ясно. Значит на данный момент пальму лидерства несет Atom

**Comment by nixel2007** [comment]
@JohnyDeath во всех вопросах на форумах/стэковерфлоу я находил  
два типа ответа - либо свой плагин (не такой уж  и сложный на самом деле), либо своя билд система через файл проекта, как и описано на вики

**Comment by EvilBeaver** [comment]
@JohnyDeath на самом деле задавать параметры каждый раз при старте - оно не так уж часто надо. Достаточно описать 2-3 билд-системных шага. У меня это обычно "протестировать текущий файл" и "запустить текущий файл". Каждый раз значения аргументов я не задаю (или задаю очень редко)
