### ISSUE TITLE
Подсветка текста запроса в строках, где запроса и нет

### ISSUE THREAD

**Issue by andreevlex** [xDrivenDevelopment/1c-syntax#271]
![default](https://cloud.githubusercontent.com/assets/20382553/26484987/bf082df6-41fd-11e7-8b92-7da6f61568d6.png)

**Comment by nixel2007** [comment]
Есть такая бодяга. к сожалению, никак не разобрать. даже "Выбрать Истина" - это валидный запрос

**Comment by andreevlex** [comment]
да, но можно сделать подсветку запроса вкл/выкл? Я так для vim буду делать.

**Comment by nixel2007** [comment]
насколько я понимаю - нет. грамматика запроса безусловно включается в грамматику встроенного языка. и как этим управлять на уровне tmLanguage я даже не знаю =/

**Comment by andreevlex** [comment]
Жаль.
