### ISSUE TITLE
Автоподхват односкриптовых тасков новым апи

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#273]
Preview: Tasks version 2.0
You can opt into the new tasks version 2.0.0 but please note that this version is currently a preview and still under active development. We make it available in order to get early feedback.

To enable the tasks preview, set the version attribute to "2.0.0" :

{
  "version": "2.0.0"
}
With version 2.0.0 enabled, the tasks from different task runners like Gulp or Grunt are automatically detected and you can run them with the Run Task command. Tasks are currently auto detected from the task runners Gulp, Grunt, Jake, and from the scripts section in package.json files. We will provide an API so that you can contribute task detection for other task runners. This API has been further polished during this iteration, but we left in in the proposed state for this release (see vscode.proposed.d.ts).

**Comment by artbear** [comment]
Ага, было бы очень удобно

**Comment by nixel2007** [comment]
https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L4790-L4791
https://github.com/Microsoft/vscode/blob/master/extensions/npm/src/main.ts
