### ISSUE TITLE
Добавление подсветки синтаксиса для системы GitLab

### ISSUE THREAD

**Issue by karnilaev** [xDrivenDevelopment/1c-syntax#28]
Совместим ли данный проект с механизмом подсветки синтаксиса в [GitLab'е](https://github.com/gitlabhq/gitlabhq)?
Если да, скажите как прикрутить к GitLab'у

**Comment by nixel2007** [comment]
Совместимость с гитлабом не проверялась. 
Github для определения синтаксиса использует внешнюю библиотеку. Библиотека в свою очередь использует  TextMate-бандлы, на которых и основана наша подсветка. 
Если гитлаб использует похожий подход, то можно попробовать прикрутить. 

Нужна дополнительная информация.

**Comment by karnilaev** [comment]
Gitlab использует для этого [rouge](https://github.com/jneen/rouge) судя по тому, что у них написано в [этой issue](https://github.com/gitlabhq/gitlabhq/issues/9403). А вот этот проект как именно делает подсветку я пока не анализировал. Поразбираюсь в теме на досуге.

**Comment by nixel2007** [comment]
rouge, судя по описанию, использует свой собственный формат описания грамматики языка. 
Проект `1c-syntax` и подчиненные проекты-пакеты используют формат описания [Text mate](http://manual.macromates.com/en/language_grammars), конвертируя файлы под требования разных редакторов (YAML -> CSON для Atom, YAML -> tmLanguage для ST и VSC).

Поэтому надо либо пытаться написать конвертер, либо портировать описание из формата Text mate в формат rouge.

**Comment by karnilaev** [comment]
Ясно, спасибо.

**Comment by nixel2007** [comment]
Задал вопрос на своем корявеньком английском. посмотрим, что скажет автор.
`https://github.com/jneen/rouge/issues/351`

**Comment by karnilaev** [comment]
Круто! Подождем ответа.

**Comment by allustin** [comment]
@karnilaev GitLab отказался в свое время от higthligth.js в пользу rouge и таким образом возможность подсветки 1С исчезла.

Хуже того у rouge наблюдаются странности с активностью https://github.com/jneen/rouge/pulse/monthly

по этой причине в том числе от GitLab пришлось отказываться, а также по причине того что GitLab не выдерживает больших конфигураций 1С. Архитектурно.

**Comment by karnilaev** [comment]
@allustin, а на что перешли с GitLab'a? Есть решение, в котором этих недостатков нет?

**Comment by allustin** [comment]
@karnilaev решения пока нет. Всё "отстой". Поэтому стоят и GitLab и еще несколько серверов GIT.

На самом деле - по серьзному: платный GitHub сейчас спасает достаточно хорошо.

**Comment by karnilaev** [comment]
У нас конфигурации пока не на столько большие, чтобы GitLab не справлялся. Единственное неудобство - нет подсветки синтаксиса, но и в GitHub'е синтаксис 1С так же не подсвечивается.

**Comment by nixel2007** [comment]
https://github.com/karnilaev/1c-syntax-for-GitLab
