### ISSUE TITLE
[VSCode] Генерация описания всех экспортных процедур из текущего модуля/файла

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/1c-syntax#282]
Хотелось бы предложить добавить следующую фичу:
сделать описания всех экспортных процедур из текущего модуля/файла, а не только для текущего метода.

Мой сценарий - я подготовил экспортное АПИ модуля 1С/скрипта 1скрипта с кучей экспортных методов
не хочется автоматом генерить описание для каждого метода отдельно, а получить шаблоны описания скопом
а уже потом отдельно допилить каждое описание

Я подозреваю, что @bambr1975 это сделать не очень сложно :grinning:

Что скажете?

**Comment by artbear** [comment]
@bambr1975 Получится у тебя сделать?

**Comment by nixel2007** [comment]
Сделаем, как руки дойдут.

**Comment by bambr1975** [comment]
да, сделаю

**Comment by artbear** [comment]
Ага, спасибо. Жду с нетерпением.

Я лично часто юзаю такой сценарий:
+ копирую модуль из 1С в новый временный файл VSC, устанавливаю язык 1С BSL,
+ и выполняю команду по генерации описания нужных/всех методов.
+ А затем вставляю полученный модуль обратно.

Очень удобно и быстро

**Comment by artbear** [comment]
@bambr1975 я готов отдельный vsix протестить

**Comment by nixel2007** [comment]
@artbear отправил сборку

**Comment by artbear** [comment]
То, что нужно, теперь намного проще будет рефакторить :)

**Comment by artbear** [comment]
Есть мелкие проблемы:
формируется неверный сдвиг для `Возвращаемое значение:`
должно быть на уровне `Параметры`, а это не так
```
// <Описание функции>
//
// Параметры:
//   ИмяСвойства - <Тип.Вид> - <описание параметра>
//
//  Возвращаемое значение:
//   <Тип.Вид> - <описание возвращаемого значения>
```

**Comment by artbear** [comment]
Экспортные методы, у которых уже есть хоть какой-комментарий, прилегающий сверху к определению метода, пропускаются. И это хорошо!

**Comment by artbear** [comment]
Очень удобная функция, наслаждаюсь.
Когда в релиз пойдет?

**Comment by nixel2007** [comment]
Думаю, вместе с генерилкой маркдауна на днях.
