### ISSUE TITLE
[VSC] Как сделать сниппет/шаблон Геркин-фичи ?

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/1c-syntax#293]
Например, чтобы включить базовый текст аналогично генерируемому VB/ADD ?

```gherkin
# language: ru

Функциональность: ...

Как ...
Я хочу ...
Чтобы ...

Контекст:
    Допустим ...

Сценарий: ...
    Допустим ...
    Когда ...
    Тогда ...
```

**Comment by artbear** [comment]
Вопрос от обучаемых!

**Comment by nixel2007** [comment]
Для сниппетов на геркине, есть плагины для поддержки геркина. Так же сниппеты можно добавлять для конкретного пользователя в vsc. Возможно подойдут динамические сниппеты из всц
