### ISSUE TITLE
[VSC] OScript запускатель

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#3]
By @vsuh

таки, определились с репозиторием? тогда сюда.
При редактировании в **vsc** `*.os` файла нажать `F1` написать `task` и нажать `Enter`

Попадаем в инструмент **Tasks: Configure task runner** который реализован в виде файла `tasks.json` в специальном каталоге `.vscode` текущего проекта. Вставить туда следующий текст:

**tasks.json**

    {
	"version": "0.1.0",
	"windows": {
		"command": "oscript.exe"
	},
	"linux": {
		"command": "/opt/bin/oscript"
	},
	"isShellCommand": true,
	// Show the output window only if unrecognized errors occur.
	"showOutput": "silent",
	"args": [
		"-encoding=utf-8"
	],
	"tasks": [
		{
			"taskName": "Compile",
			"args": [
				"-compile",
				"${file}"
			],
			"echoCommand": true,
			"showOutput": "always",
			"suppressTaskName": true,
			"isBuildCommand": true
		},
		{
			"taskName": "Run",
			"args": [
				"${file}"
			],
			//"echoCommand": true,
			"showOutput": "always",
			"suppressTaskName": true,
                	 "problemMatcher": "$gulp-tsc",
			"isBuildCommand": true
		}
	]
    }

В результате в списке задач появится две задачи `Compile` и `Run` вызвать их можно опять же комбинацией `F1` `tasks: run task` или назначить комбинацию клавиш командой `File -> Preferences -> Keyboard Shortcuts` на команду `workbench.action.tasks.runTask`.

Кстати, выражение `"isBuildCommand": true` в задаче `Compile` обозначает, что ее можно запустить комбинацией `Ctrl-Shift-B`

Текст написан по мотивам [официальной документации на VSC](https://code.visualstudio.com/Docs/editor/tasks)

В следующий раз, уважаемые читатели, мы поговорим о настройке блока `problemMatcher`, которая позволит нам переходить к выражению в коде, вызвавшему ошибку.

**Comment by vsuh** [comment]
Прошу прощенья, не знаю как в вики сохранять картинки, поэтому засуну здесь:
![image](https://cloud.githubusercontent.com/assets/12156293/11623913/25cecf54-9ce1-11e5-9c99-697cc6416373.png)

**Comment by nixel2007** [comment]
А что это? :) Пример раскраски из VSC?

**Comment by vsuh** [comment]
да
для вики

**Comment by EvilBeaver** [comment]
@nixel2007 @vsuh еще раз спасибо за пакеты, действительно классно!
Теперь нужны прочие плюшки, в первую очередь "запускалка" на всех редакторах.

**Comment by nixel2007** [comment]
Сразу после contributing.md :)

**Comment by artbear** [comment]
Ага, запускалки нужны.
Мне лично Atom интересен.

**Comment by artbear** [comment]
@nixel2007  `contributing.md` что хочешь в нем указать?

**Comment by nixel2007** [comment]
@artbear как минимум:
* ссылки на документацию к каждому редактору
* как изменять грамматики и отлаживать (в том числе, в случае установленного пакета)
* как создавать и публиковать новые версии пакетов - для этого нужно еще дописать билдер, сейчас там еще остались ручные операции.

**Comment by nixel2007** [comment]
offtopic:
Редактор markdown и встроенный markdown preview в Атоме просто божественен -_-
Я тащусь.

**Comment by EvilBeaver** [comment]
@artbear насколько я знаю, VSCode это тот же Атом, только вид сбоку

**Comment by nixel2007** [comment]
@vsuh 
```
// Show the output window only if unrecognized errors occur.
"showOutput": "silent",
```

Это не будет мешать смотреть информационные сообщения при отладке?

**Comment by vsuh** [comment]
@nixel2007 Отладки (`debug`) в __VSC__ нет.
смотреть не мешает, окно открывается в любом случае.

**Comment by vsuh** [comment]
@nixel2007 про редактор markdown в __VSC__.
Все плюшки сделаны на сниппетах, по `Ctrl-Shift-V` запускается адекватный превью.

**Comment by nixel2007** [comment]
@vsuh 
> Отладки (debug) в VSC нет.

Как таковая она там есть :) с точками останова, табло переменных и прочими плюшками.

**Comment by vsuh** [comment]
@nixel2007 Прошу прощения, для `bsl` отладки в `vsc` нет.

**Comment by nixel2007** [comment]
@vsuh @evilbeaver я правильно понимаю, что для работы отладки в интерпретаторе onescript должна быть поддержка REPL из консольного режима?

**Comment by vsuh** [comment]
@artbear @nixel2007 

!! холивар
Atom
![image](https://cloud.githubusercontent.com/assets/12156293/11708982/be94bd58-9f24-11e5-8bcd-ba680be1b12f.png)
VSC
![image](https://cloud.githubusercontent.com/assets/12156293/11709004/eadd8f98-9f24-11e5-92d6-21b0193e3d1a.png)

**Comment by nixel2007** [comment]
Видимо, я пропустил пробел)

**Comment by nixel2007** [comment]
Просмотр [документации VSC](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributescommands) наводит меня на мысль, что для того, чтобы включить запускатель oscript в пакет, нужно в package.json описывать блок `contributes.commands` и описать этот запускатель в `js`-файле внутри пакета.
@vsuh ничего не путаю?

**Comment by EvilBeaver** [comment]
@nixel2007 а причем тут REPL?

В oscript отладка не предусмотрена совсем. Ну т.е. можно попытаться поотлаживать псевдоассемблер байткода, но символьная отладка отсутствует, как класс. Давайте пока ограничимся просто запуском и просмотром результата. А про отладку пока просто поизучаем, как делать. Тогда вы сможете выработать требования к отладчику (что он должен предоставить) и на базе этих требований подумаем, как это реализовать в 1Script.

**Comment by nixel2007** [comment]
@EvilBeaver про REPL просто предположение. Слабо представляю, как взаимодействует отладчик редактора с интерпретатором. По VSC была вроде какая-то документация на эту тему.
> Давайте пока ограничимся просто запуском и просмотром результата.

Да, конечно. Это так, идеи на будущее.

**Comment by EvilBeaver** [comment]
В VSC есть даже функционал проверки синтаксиса скрипта "на лету"
Например, про php он вот что пишет:

>Cannot validate the php file. The php program was not found. Use the 'php.validate.executablePath' setting to configure the location of 'php'

Значит сам функционал есть. Неплохо бы нарыть что он делает.

**Comment by artbear** [comment]
А давайте поделимся плюшками и предпочтениями, кто и почему каким редактор
предпочитает
Мне пока Атом нравится, редактор markdown в первую очередь, vsc не юзал,
саблайм также не юзал и он типа платный
Предлагаю поделиться

чт, 10 Дек 2015, 12:58, Andrei Ovsiankin <notifications@github.com>:

**Comment by nixel2007** [comment]
@artbear а давайте поделимся предпочтениями не в рабочем issue? :)

**Comment by vsuh** [comment]
в `%appdata%\roaming\code\user\settings.json` 

    	// Points to the php exectuable.
	"php.validate.executablePath": "c:\\tools\\php\\php.exe",

	// Whether the linter is run on save or on type.
	"php.validate.run": "onSave",

только слово `bsl.validate.executablePath` там не ожидается и не обработается.

**Comment by vsuh** [comment]
@nixel2007 
>  что для того, чтобы включить запускатель oscript в пакет, нужно в package.json описывать блок contributes.commands и описать этот запускатель в js-файле внутри пакета.

оно жежь есть в репо и давно [описано](https://github.com/xDrivenDevelopment/1c-syntax/wiki/1.1.-Visual-Studio-Code)!

**Comment by nixel2007** [comment]
@vsuh это не то. Это ручная установка в рамках текущего рабочего каталога. А я имею ввиду типовую функциональность пакета без каких-либо ручной работы. Поставил пакет и забыл.

**Comment by nixel2007** [comment]
Информация по разработке собственного дебаггера для vsc - https://code.visualstudio.com/docs/extensions/example-debuggers
Документация по debug-api https://code.visualstudio.com/docs/extensionAPI/api-debugging

**Comment by nixel2007** [comment]
Сходу не получилось нагуглить пакета, позволяющего настроить запуск скрипта на выполнение с указанием параметров. Видимо, придется пилить что-то свое.

**Comment by nixel2007** [comment]
Разработка команд запуска отложена. Необходимо описать/проверить описание запуска через tasks.json от vsuh на wiki

**Comment by nixel2007** [comment]
Описана инструкция по созданию файла tasks.json.
Готово к релизу.
