### ISSUE TITLE
Группировка/сворачивание по произвольным текстовым блокам `//{` и `//}` и областям #Область

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/1c-syntax#30]
Хотелось бы получить группировку/сворачивание по произвольным текстовым блокам `//{` и `//}`

**Comment by artbear** [comment]
Также нужны группировка/сворачивание по произвольным текстовым областям `#Область`

**Comment by nixel2007** [comment]
Поддерживаю. Надо проверить, будут ли корректно обрабатываться области ключами foldingStartMarker и foldingStopMarker (не уверен, если честно). Если нет, то может быть привязываться к какому-то из плагинов и/или взаимодействовать с движком редакторов не на уровне грамматик, а на уровне определения сворачиваемых областей.

**Comment by nixel2007** [comment]
В ST и в Атом не обрабатываются теги foldingStartMarker и foldingStopMarker. В VSC, подозреваю, тоже. 
Нужно искать сторонний плагин для кастомизации сворачиваемых областей.

Схожая задача #5

**Comment by nixel2007** [comment]
Есть вот такой пример файла настроек TextMate:
https://github.com/textmate/css.tmbundle/blob/master/Preferences/Folding.tmPreferences

Проверить

**Comment by ebugusey** [comment]
> В VSC, подозреваю, тоже. 

В VSC пока поддержки свертки вообще нет. В планах на февраль.
Microsoft/vscode#105

**Comment by nixel2007** [comment]
@bambr1975 повесил на 1.10
