### ISSUE TITLE
Atom: Не подсвечивается ключевое слово Перем

### ISSUE THREAD

**Issue by EvilBeaver** [xDrivenDevelopment/1c-syntax#31]
![image](https://cloud.githubusercontent.com/assets/2657561/11871131/640c508e-a4de-11e5-8ad5-d2ccaf119d32.png)

**Comment by nixel2007** [comment]
Да, тоже это замечал. Видимо из-за того, что `Перем` и `Новый` объявлены как [keyword.operator.bsl](https://github.com/xDrivenDevelopment/1c-syntax/blob/master/1c.YAML-tmLanguage#L81), без указания класса оператора.  
Интересно, что в ST подсвечивается так же, как и все остальные операторы.

Надо отнести к каакому-либо классу.
