### ISSUE TITLE
Настройки блочного комментирования

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#33]
В Атоме точно есть настройка, каким образом комментировать блок выделенного текста через Ctrl-/

Сейчас Атом ставит стандартные /* ... */. В конфигах синтаксис-пакета можно переопределить.  

Проверить, что в остальных редакторах блочное комментирование работает корректно либо так же поправить.

**Comment by nixel2007** [comment]
В vsc за это отвечает свойство
`	"blockComment": [ "/*", "*/" ]` в файле bsl.configuration.json

**Comment by vsuh** [comment]
в `onescript` такие комментарии не допускаются, насколько я знаю.

**Comment by nixel2007** [comment]
Да и в 1с тоже. Надо каждую строку начинать со слешей. Только через блочное комментирование у меня это не получилось настроить, а построчное не заработало вообще.

**Comment by bambr1975** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Comments</string>
	<key>scope</key>
	<string>source.bsl</string>
	<key>settings</key>
	<dict>
		<key>shellVariables</key>
		<array>
			<dict>
				<key>name</key>
				<string>TM_COMMENT_START</string>
				<key>value</key>
				<string>// </string>
			</dict>
		</array>
	</dict>
	<key>uuid</key>
	<string>B79BDBCF-D0C9-468E-BE62-744074D7825F</string>
</dict>
</plist>
```
Файлик с таким содержимым надо положить в папку User и все получится)))

**Comment by nixel2007** [comment]
Даже это из коробки не работает? Ужос. 
По идее в configuration.json линейное комментирование тоже можно зашить. Хочется максимум настроек зашить в сам пакет.

**Comment by bambr1975** [comment]
Почему построчное не заработало?
Чтобы оно заработало для vcs надо поправить в package.json секцию contributes (добавить в нее строку  "configuration": "./bsl.configuration.json")
```
    "contributes": {
        "languages": [{
            "id": "bsl",
            "extensions": [ ".bsl", ".os" ],
            "aliases": [ "1C (BSL)", "BSL" ],
            "configuration": "./bsl.configuration.json"
        }],
```
и положить рядом с ним файлик bsl.configuration.json с таким содержимым:
```
{
	"comments": {
		"lineComment": "//"
	}
}
```

**Comment by nixel2007** [comment]
Да, делал именно так. 
Понял, в чем проблема: я давил неправильный шорткей. Надо ctrl-k ctrl-c, а я просто давил ctrl-k, думая, что в описании шорткеев после запятой идет алиас, а не последовательность клавиш -_-

**Comment by bambr1975** [comment]
ctrl-k ctrl-c только добавляет комментарий, чтобы его удалить, надо пользоваться другим шорткеем. Переключать удобнее - переключать с помощью ctrl-,

**Comment by bambr1975** [comment]
а для ST получилось?

**Comment by nixel2007** [comment]
@bambr1975 в процессе. Нашел доки, сейчас сделаю.

**Comment by nixel2007** [comment]
@bambr1975 ой, я только сейчас понял, что ты скидывала пример для ST, а не vsc. :)

**Comment by bambr1975** [comment]
а можешь удалить последний коммент?

**Comment by nixel2007** [comment]
Реализовано для всех редакторов.
