### ISSUE TITLE
Релизное управление

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/1c-syntax#35]
Сейчас есть набор проблем: 
- неудобно собирать изменения для формирования changelog
- В описании релиза непонятно, что входит в релизы для разных редакторов.
- непонятен roadmap или хотя бы ближайшие планы на реализацию.

Например, @nixel2007 выпустил релиз https://github.com/xDrivenDevelopment/sublime-language-1c-bsl/releases/tag/v1.0.3
Как узнать, что в него вошло, изучая страницу релиза?

Для решения этих проблем предлагаю перейти на релизное управление, предлагаемое Github.
Используем milestone для наименования релиза и включения всех issue в релиз.
Потом удобно собирать/изучать/публиковать изменения.

@xDrivenDevelopment/1c-syntax что скажете?

**Comment by nixel2007** [comment]
Отвечу по пунктам, как я это вижу.

> неудобно собирать изменения для формирования changelog

Напомню, что я стараюсь вести политику единовременного выпуска релизов для всех редакторов с одинаковым функционалом - [CONTRIBUTING.md#Общие-положения](https://github.com/xDrivenDevelopment/1c-syntax/blob/master/CONTRIBUTING.md#Общие-положения).
При добавлении/изменении общего функционала в рамках репо 1c-syntax изменения сразу фиксируются в Changelog.md с пометкой Unreleased. Например, https://github.com/xDrivenDevelopment/1c-syntax/commit/46cd58a18f54282c5436fe9973650257c83126b4  
Так как выпуск релиза начинается с головного репо, то и все изменения аккумулируются в нем же. Из специфичных вещей пока только oscript-запускатель, но он разрабатывается отдельно для каждого редактора. Однако в сводном чейнджлоге он так же появится одновременно.

> В описании релиза непонятно, что входит в релизы для разных редакторов.

Имеешь ввиду [эту страницу](https://github.com/xDrivenDevelopment/sublime-language-1c-bsl/releases)? Если да, то, опять же, во-первых, функционал пока общий и затрагивает все пакеты, во-вторых, я (пока) больше рассчитываю на changelog (он хотя бы в Атоме показывается).

> непонятен roadmap или хотя бы ближайшие планы на реализацию.

Глобально, в 1.1.0 войдет запускатель oscript. Фиксы грамматики не требуют длительной разработки, поэтому они выпускаются "on going". 

> Например, @nixel2007 выпустил релиз https://github.com/xDrivenDevelopment/sublime-language-1c-bsl/releases/tag/v1.0.3
Как узнать, что в него вошло, изучая страницу релиза?

Из релиза никак. Только Changelog. Ну или по коммитам через обычное сравнение https://github.com/xDrivenDevelopment/sublime-language-1c-bsl/compare/v1.0.2...xDrivenDevelopment:v1.0.3

Черт, видимо я потерял изменения грамматики, когда локально крутился с ветками... Спасибо, Артур!

Вот пример для репо Atom https://github.com/xDrivenDevelopment/atom-language-1c-bsl/compare/v1.0.2...xDrivenDevelopment:v1.0.3

> Для решения этих проблем предлагаю перейти на релизное управление, предлагаемое Github.
...
Потом удобно собирать/изучать/публиковать изменения.

Оно потом само слинкуется в красивое описание? Надо почитать доки, не пользовался этой возможностью.

**Comment by artbear** [comment]
>Оно потом само слинкуется в красивое описание? Надо почитать доки, не пользовался этой возможностью.

Такой возможности не видел.

Возможно, что есть какой-то скрипт, который собирает
В wincvs в свое время был удобный скрипт, который собирал changelog по всем коммитам.
Нужно поискать, наверняка либо скрипт есть либо сразу через git log можно получить инфу.

Хотя с задачей сделать `раздельный` changelog по редактором для исходного/сводного репозитария вряд ли можно обойтись без ручных правок :(

**Comment by artbear** [comment]
Добавил в пред.сообщение:
>Но зато очень удобно видеть сразу реальные ссылки и выполнять навигацию (issue, коммиты, обсуждение) по тем issue, которые вошли в релиз/milestone

**Comment by nixel2007** [comment]
*offtopic:*
> Черт, видимо я потерял изменения грамматики, когда локально крутился с ветками... Спасибо, Артур!

Пока никто не успел скачать релиз для ST, сделал перепубликацию. В течении пары минут должно дойти до packagecontrol.

**Comment by nixel2007** [comment]
@artbear Создал майлстоуны на предстоящие релизы (текущие задачи и планы на будущее).
Ты себе это как-то похоже представляешь?

И, видимо, ты хочешь, чтобы я начал заполнять страницы с релизами, правильно тебя понимаю? :)

**Comment by artbear** [comment]
Ага,по заполнению описания это минимальное пожелание

вс, 20 Дек 2015, 1:37, Nikita Gryzlov <notifications@github.com>:

**Comment by nixel2007** [comment]
@artbear описал изменения всех релизов (чейнджлог + дифф)

**Comment by artbear** [comment]
@nixel2007 
>Создал майлстоуны на предстоящие релизы (текущие задачи и планы на будущее).
Ты себе это как-то похоже представляешь?

Да, именно так

>описал изменения всех релизов (чейнджлог + дифф)

Отлично, спасибо.

**Comment by nixel2007** [comment]
Вроде приживается схема. Закрываю.
