### ISSUE TITLE
Нет подсветки для точки и для скобок

### ISSUE THREAD

**Issue by bambr1975** [xDrivenDevelopment/1c-syntax#36]
Расстроила подсветка https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2FxDrivenDevelopment%2Fvsc-language-1c-bsl%2Fblob%2Fmaster%2Fsyntaxes%2F1c.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2F1C-Company%2Fdt-demo-configuration%2Fblob%2Fmaster%2FDemoConfDT%2FCatalog.%25D0%2592%25D1%2585%25D0%25BE%25D0%25B4%25D1%258F%25D1%2589%25D0%25B8%25D0%25B5%25D0%259F%25D0%25B8%25D1%2581%25D1%258C%25D0%25BC%25D0%25B0.Form.%25D0%25A4%25D0%25BE%25D1%2580%25D0%25BC%25D0%25B0%25D0%25AD%25D0%25BB%25D0%25B5%25D0%25BC%25D0%25B5%25D0%25BD%25D1%2582%25D0%25B0.Form.Module.bsl&code=

Во-первых, сразу видно, что нет подсветки для точек и скобок. 
Во-вторых, почему-то не подсвечиваются конструкции, заданные с метасимволом \b - подсвечиваются только те, у которых этого метасимвола не задано. 

@nixel2007 , что думаешь по этому поводу?

**Comment by nixel2007** [comment]
1) а я вроде и не добавлял подсветку скобок и точек. Их изначально в грамматике не было. Для себя аргументировал это тем, что скобки не подсвечиваются в питоне. 
2) а вот это странно. Может в их парсере что-то некорректно работает? :( можно попробовать заменить \b на позитивный поиск вперёд/назад. Можешь попробовать на том сайте что-то поколдовать с этим? Там можно не только вставлять  ссылку на грамматику,  но и саму грамматику копипастить в поле.

**Comment by bambr1975** [comment]
видимо, не подсвечивает из-за этого http://javascript.ru/forum/misc/10146-javascript-regexp-i-russkijj.html
Получается, что действительно надо искать замену этому метасимволу. У меня мало идей, чем его можно полноценно заменить. Разве что что-то вроде (?&lt;=[^a-zа-я0-9_])  в начале и (?=[^a-zа-я0-9_]) в конце.

**Comment by bambr1975** [comment]
а точнее (?&lt;=[^\wа-яё]) в начале и (?=[^\wа-яё]) в конце

**Comment by nixel2007** [comment]
Проверил, действительно выделяется с заменой на такие конструкции. И обычную подсветку соответственно не ламает. Надо обновить грамматику.

**Comment by nixel2007** [comment]
@bambr1975 сломалось определение, если конструкция в начале строки. То есть, 
```
  - name: storage.type.bsl
    match: (?i:(?<=[^\wа-ё])(КонецПроцедуры|EndProcedure|КонецФункции|EndFunction)(?=[^\wа-ё]))
```
не подсвечивается, если `КонецПроцедуры` в начале строки (а оно естественно всегда так).

**Comment by bambr1975** [comment]
Значит, правильнее (?<=[^\wа-ё]|^) и соответственно (?=[^\wа-ё]|$)

**Comment by nixel2007** [comment]
@bambr1975 Блок по второй задаче выполнил. Если считаешь, что точки и скобки стоит дообсудить - переоткрой этот issue .
