### ISSUE TITLE
Баг в подсветке VSC

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#37]
by @vsuh 
Вот такая процедура у меня настрадалась:
![image](https://cloud.githubusercontent.com/assets/12156293/11949322/cd7a41f8-a88e-11e5-9ca9-3ef09743439c.png)

Переписал функцию, заменив все русские литералы на английские - подсветка стала кошерная.
А ломается она даже если в тесте блока есть хоть один русский литерал.
![image](https://cloud.githubusercontent.com/assets/12156293/11949853/765ce9a6-a894-11e5-8f1a-8dc94d0c0f4f.png)

by @bambr1975
[Воспроизвести не получилось](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2FxDrivenDevelopment%2Fsublime-language-1c-bsl%2Fblob%2Fmaster%2F1c.tmLanguage&grammar_text=&code_source=from-text&code_url=https%3A%2F%2Fgithub.com%2F1C-Company%2Fdt-demo-configuration%2Fblob%2Fmaster%2FDemoConfDT%2FCatalog.%25D0%2592%25D1%2585%25D0%25BE%25D0%25B4%25D1%258F%25D1%2589%25D0%25B8%25D0%25B5%25D0%259F%25D0%25B8%25D1%2581%25D1%258C%25D0%25BC%25D0%25B0.Form.%25D0%25A4%25D0%25BE%25D1%2580%25D0%25BC%25D0%25B0%25D0%25AD%25D0%25BB%25D0%25B5%25D0%25BC%25D0%25B5%25D0%25BD%25D1%2582%25D0%25B0.Form.Module.bsl&code=function+getErrorFullDescription%28%D0%9E%D1%88%29%0D%0A%D0%A2%D0%B5%D0%BA%D1%81%D1%82%D0%9E%D1%88%D0%B8%D0%B1%D0%BA%D0%B8+%3D+%22%22%3B%0D%0Awhile+%D0%9E%D1%88+%3C%3E+%D0%9D%D0%B5%D0%BE%D0%BF%D1%80%D0%B5%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%BE+do%0D%0A%D0%95%D1%81%D0%BB%D0%B8+%D0%9E%D1%88.%D0%9F%D1%80%D0%B8%D1%87%D0%B8%D0%BD%D0%B0+%3C%3E+%D0%9D%D0%B5%D0%BE%D0%BF%D1%80%D0%B5%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%BE+%D0%A2%D0%BE%D0%B3%D0%B4%D0%B0%0D%0A%D0%A2%D0%B5%D0%BA%D1%81%D1%82%D0%9E%D1%88%D0%B8%D0%B1%D0%BA%D0%B8+%3D+%D0%A2%D0%B5%D0%BA%D1%81%D1%82%D0%9E%D1%88%D0%B8%D0%B1%D0%BA%D0%B8+%2B%22+%2F%2F%D1%81%D1%82%D1%80.%22%2B%D0%9E%D1%88.%D0%98%D1%81%D1%85%D0%BE%D0%B4%D0%BD%D0%B0%D1%8F%D0%A1%D1%82%D1%80%D0%BE%D0%BA%D0%B0%2B%22+%3A+%2F%2F%22%2B%0D%0A%D0%9A%D0%BE%D0%BD%D0%B5%D1%86%D0%95%D1%81%D0%BB%D0%B8%3B%0D%0A%D0%9E%D1%88+%3D+%D0%9E%D1%88.%D0%9F%D1%80%D0%B8%D1%87%D0%B8%D0%BD%D0%B0%3B%0D%0Aenddo%3B%0D%0A%D0%92%D0%BE%D0%B7%D0%B2%D1%80%D0%B0%D1%82+%D0%A2%D0%B5%D0%BA%D1%81%D1%82%D0%9E%D1%88%D0%B8%D0%B1%D0%BA%D0%B8%3B)

by @nixel2007
Видимо, это проблемы именно VSC.
![st](https://cloud.githubusercontent.com/assets/1132840/11949968/76af0df2-a895-11e5-9e61-d61fc342f9fa.PNG)
![atom](https://cloud.githubusercontent.com/assets/1132840/11950064/144ab264-a896-11e5-8abb-e63da7a19736.PNG)
![vsc](https://cloud.githubusercontent.com/assets/1132840/11950066/1538c49a-a896-11e5-98f5-fc77297926c9.PNG)

VSC как-то странно и очень жадно определяет токены. Если в
```
Если Ош.Причина ...
```

перед `Ош` поставить несколько пробелов, то он перестает их подкрашивать.
Тоже самое с раскраской строковых констант и комментариев - добавить пробелы и все ок.

**Comment by bambr1975** [comment]
у меня на vsc не воспроизвелось. Что я делаю не так?
![2015-12-22_104140](https://cloud.githubusercontent.com/assets/9781644/11950351/c0110e20-a898-11e5-8523-e97b3eb298c7.jpg)

**Comment by nixel2007** [comment]
@bambr1975 Странно, у тебя и @vsuh имя функции подсвечивает, а у меня нет.
Версия пакета 1.0.4
Версия vsc 
![default](https://cloud.githubusercontent.com/assets/1132840/11950609/f39db002-a89a-11e5-8c1c-fcf3d3a7c6da.PNG)

**Comment by bambr1975** [comment]
Скриншот был сделан на версии пакета 1.0.4 и версии vsc:
![2015-12-22_105824](https://cloud.githubusercontent.com/assets/9781644/11950657/6b6a9a00-a89b-11e5-9c64-6ba9cc3957f8.jpg)
Используемая тема - dark
А теперь, для сравнения скриншот после обновления на 
![2015-12-22_110305](https://cloud.githubusercontent.com/assets/9781644/11950686/bb8e4982-a89b-11e5-8ef2-a2931113c3d2.jpg)

![2015-12-22_110214](https://cloud.githubusercontent.com/assets/9781644/11950683/b0222384-a89b-11e5-887a-f9b854e1ae4e.jpg)

**Comment by nixel2007** [comment]
@bambr1975 вот оно что... Надо смотреть чейнджлоги vsc. И баг-трекер заодно :D

**Comment by nixel2007** [comment]
Возможно, как-то связано с этим:
`https://github.com/atom/node-oniguruma/pull/46`

**Comment by bambr1975** [comment]
Была мысль, что это последние наши правки по части границ слов повлияли. Но вот как выглядит подсветка версии 1.0.3 (где использовался метасимвол /b)
![2015-12-22_130113](https://cloud.githubusercontent.com/assets/9781644/11952806/675cc576-a8ac-11e5-858c-33a4a0bfb062.jpg)
А ссылки интересные, конечно. Но атом вроде не сломался?

**Comment by nixel2007** [comment]
Изменения в библиотеку были влиты только вчера. Релиз атома был раньше. У меня дома бета атома, посмотрю, как он отреагирует после выхода новой беты

**Comment by bambr1975** [comment]
красное Ош.П - это то, что ты просил https://github.com/xDrivenDevelopment/1c-syntax/pull/9#issuecomment-161908300 если точку убрать - все станет красным. Именно после равно))) и именно если один пробел или нет пробела)))

**Comment by nixel2007** [comment]
@bambr1975 явно их парсер коряво работает. :/ оно должно так парситься только внутри объявления процедуры, в ее параметрах.

**Comment by bambr1975** [comment]
а как бы это им правильно сформулировать????

**Comment by nixel2007** [comment]
У них сейчас много issue на трекере с различными проблемами по подсветке, так что думаю, что они уже в курсе.
Можно конечно повесить еще одну с кодом, описанием, твоими скриншотами с 0.10.5 и 0.10.1 и с Atom и ST.

P.S. если переключиться в цветовую схему Monokai, то веселья еще больше.

**Comment by nixel2007** [comment]
Где-то в обсуждении проскакивала фраза, про проблему токенайзера при обработке "мультибайтных" символов. Похоже на правду, потому что VSC подсвечивает строку ровно в 2 раза превышающую исходную. А русские символы в юникоде как раз двумя байтами определяются.

**Comment by nixel2007** [comment]
О, до меня дошло, почему он параметры определяет неправильно:
Он начинает раскрашивать "Ош" в определении, отжирает 2*2 символа, не находит закрывающую скобку (потому что она пропущена внутри этих 4 символов) и начинает красить все как попало под грамматику из-за `include: self` в правилах.
Когда он находит равно, он считает, что по правилам это дефолтное значение переменной, подкрашивает `= Ош" (а точнее `СтрДлина(Ош) * 2` как `invalid`.

`Возврат ТекстОшибки;` по этой же причине - 5*2 символов.

**Comment by JohnyDeath** [comment]
Обновился VSC до версии
![image](https://cloud.githubusercontent.com/assets/5936030/12031022/1ed9672a-ae18-11e5-8a54-be25b27fa509.png)
Теперь подсветка вот такая:
![image](https://cloud.githubusercontent.com/assets/5936030/12031030/37126314-ae18-11e5-8540-604527f8c944.png)

Судя по вашей переписке - это баг новых версий VSC. Надо ждать от них изменений или что-то можно сделать на "нашей" стороне?

**Comment by nixel2007** [comment]
@JohnyDeath да, это баг в VSC. Надо ждать фиксов от них, причем, видимо, уже после праздников, потому что основная команда разработки VSCode ушла на рождественско-новогодние каникулы

Как временный обходной путь могу предложить писать латиницей :) Либо временно/постоянно перейти на Atom

**Comment by JohnyDeath** [comment]
@nixel2007 понял, спасибо.
У меня все три редактора стоят. Никак не могу определиться ) В каждом есть что-то свое вкусное.

**Comment by EvilBeaver** [comment]
@JohnyDeath 

> В каждом есть что-то свое вкусное.

И пока никак не перейти на что-то полностью... сижу в N++ :cry:

**Comment by nixel2007** [comment]
@EvilBeaver Чего не хватает, если не секрет? Запускатора или чего-то еще?

**Comment by EvilBeaver** [comment]
Не хватает запускатора и автодополнения в Atom (см. #50) И еще атом обрубает пустые строки с табами. Например:

    Если а = 1 Тогда
        
        Б = 1;
    КонецЕсли;

Пустая строка сразу после **Тогда** содержит 2 табуляции. Атом делает для нее СокрЛП, потом это в git diff вылезает.

**Comment by EvilBeaver** [comment]
Но я однозначно перейду на Атом, если будет запускалка. Также пробую ST, тоже нравится (с него-то, собственно, вся движуха по развитию редакторов и началась)

**Comment by nixel2007** [comment]
> И еще атом обрубает пустые строки с табами.

это настраивается в пакете Whitespace. Тоже думал, сделать настройку на уровне пакета.

**Comment by JohnyDeath** [comment]
@EvilBeaver неужели в этих редакторах нет запускалки? Для ST сходу ткнул в первый попавшийся пакет: https://packagecontrol.io/packages/Run%20Apps (вроде бы запустить скрипт сможет).
Сам еще, правда тоже с N++ не слез )

**Comment by nixel2007** [comment]
@JohnyDeath Есть https://github.com/xDrivenDevelopment/sublime-language-1c-bsl/pull/1
https://github.com/xDrivenDevelopment/atom-language-1c-bsl/pull/1

Остается проблема передачи параметров в скрипт, но это тоже решаемо.

**Comment by JohnyDeath** [comment]
@nixel2007 но мы же сейчас не про подсветку, а про выполнение скрипта (текущего файла). За это по идее должен отвечать другой пакет. Разве я не прав?

**Comment by artbear** [comment]
Помимо простого запуска скриптов с параметрами хочется большего удобства.
Например, в Н++ у меня настроены куча разных вызовов. Я просто выбираю
нужный вариант и запускаю его
Сейчас подобной фичи нет

вт, 29 Дек 2015, 18:19, Evgeny Martynenkov <notifications@github.com>:

**Comment by nixel2007** [comment]
@JohnyDeath необязательно. обычно тот же пакет, что дает описание грамматики, предоставляет сервисы по запуску файлов этого формата стандартным интерпретатором.

**Comment by nixel2007** [comment]
@artbear Ничто не мешает тебе настроить эти вызовы через кастомные билд-скрипты и в ST и в Atom уже сейчас, не дожидаясь принятия пулл-реквестов.  
Вот и еще один пункт, который надо отразить в ридми по пакетам :)

**Comment by artbear** [comment]
Насчет кастомизации билд-скриптов.
Есть возможность получать имя текущего файла, текущего каталога? Какие
параметры доступны билд-скрипту?

вт, 29 Дек 2015, 18:24, Nikita Gryzlov <notifications@github.com>:

**Comment by nixel2007** [comment]
Зависит от редактора и билд-системы.
Для ST - http://docs.sublimetext.info/en/latest/reference/build_systems.html
Для Atom - https://atom.io/packages/build и https://atom.io/packages/build и https://github.com/rgbkrk/atom-script

В ридмях указано, как настроить свой билд-скрипт.

**Comment by EvilBeaver** [comment]
Блин, вот зачем я VSC обновил. Теперь у меня та же хрень.

![image](https://cloud.githubusercontent.com/assets/2657561/12505101/f9fe45f2-c0f4-11e5-9b47-64f5f37d0985.png)

**Comment by nixel2007** [comment]
@EvilBeaver пока есть два способа - откатиться на прошлую версию редактора (до 0.10.5) или писать на английском :(

**Comment by bambr1975** [comment]
ты хотел сказать, до 0.10.1? в 0.10.5 уже была проблема

**Comment by EvilBeaver** [comment]
Давайте так - я с возрастом превращаюсь в ленивого ламера-домохозяйку. Я ничего не знаю, обновился и работать перестало. Какая там была версия до обновления - понятия не имею и не слежу :) Пойду, поставлю старую версию. А Issue в VSC есть по этому поводу?

**Comment by nixel2007** [comment]
@bambr1975 я имел ввиду на любую версию до 0.10.5) например, 0.10.3

**Comment by nixel2007** [comment]
@EvilBeaver ишу в репо vsc есть и много (пример с ссылками выше). много уже исправленных. но они еще не выпустили релиз, поэтому все ждем.

**Comment by EvilBeaver** [comment]
@nixel2007 там баги в библиотеке регекспов oniguruma. А это точно из-за нее? Может все-таки создать отдельную задачку?

**Comment by EvilBeaver** [comment]
Лучше перебдеть, чем недобдеть: https://github.com/Microsoft/vscode/issues/2170

**Comment by nixel2007** [comment]
@EvilBeaver у меня сложилось впечатление, что там наложилось куча всего. и изменение в онигуруме, и смена логики работы токенайзера.
Январский релиз скоро, посмотрим что там.

**Comment by nixel2007** [comment]
@EvilBeaver спасибо, дописал там свои наблюдения

**Comment by EvilBeaver** [comment]
strLen("Возврат") = 10 ? 
7 или 14 я пойму, а 10 откуда?

**Comment by nixel2007** [comment]
упс)

**Comment by nixel2007** [comment]
https://github.com/Microsoft/vscode/issues/2170

Вроде закрыли багу. Ждем январского релиза

**Comment by nixel2007** [comment]
Проверил подсветку на insider-билде. Работает.
Конечно же monokai:
![default](https://cloud.githubusercontent.com/assets/1132840/12827412/a9c56470-cb90-11e5-8eea-fb6d94958e6f.PNG)

**Comment by nixel2007** [comment]
Ошибка исправлена в VS Code версии 0.10.8
