### ISSUE TITLE
Учет ё

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#41]
Проверить все регулярки на попадание буквы "ё" - она не попадает в стандартный блок [а-я]. Точно надо добавить в определение параметра в процедуре

**Comment by artbear** [comment]
Не уверен, что правильно `[а-ё]`
Я всегда пользуюсь `[а-яё]`

вт, 22 дек. 2015 г. в 19:19, Nikita Gryzlov <notifications@github.com>:

**Comment by nixel2007** [comment]
Да, я уже тоже об этом подумал. Надо [а-яё] 

Отправлено с моего HTC

----- Reply message -----
От: "Artur Ayukhanov" <notifications@github.com>
Кому: "xDrivenDevelopment/1c-syntax" <1c-syntax@noreply.github.com>
Копия: "Nikita Gryzlov" <nixel2007@gmail.com>
Тема: [1c-syntax] Учет ё (#41)
Дата: вт, дек. 22, 2015 19:29

Не уверен, что правильно `[а-ё]`


Я всегда пользуюсь `[а-яё]`





вт, 22 дек. 2015 г. в 19:19, Nikita Gryzlov <notifications@github.com>:





> Проверить все регулярки на попадание буквы "ё" - она не попадает в


> стандартный блок [а-я], надо [а-ё] Точно надо добавить в определение


> параметра в процедуре


>


> —


> Reply to this email directly or view it on GitHub


> <https://github.com/xDrivenDevelopment/1c-syntax/issues/41>.


>




&mdash;

**Comment by bambr1975** [comment]
Да, правильнее [а-яё], потому что между я и ё один лишний символ http://www.wiwi.uni-frankfurt.de/~burman/unicode.php?text_size=15&tab_size=16&offset=1089 Его учитывать не нужно. Просто казалось, что так быстрее записывать регулярку.
