### ISSUE TITLE
Go to declaration

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#42]
В Атоме и в VSC не работает функция GoTo definition.
В ST все штатно, на основании грамматики.

**Comment by nixel2007** [comment]
В Атоме можно заставить работать через пакет https://atom.io/packages/goto

**Comment by artbear** [comment]
В Atome у пакета goto кнопка 'Goto to declaration' забиндена не на хоткей 'F12'
По умолчанию 'cmd-alt-down' - Goto Declaration

Возможно ли 'программно' установить на 'F12' ?
Хотелось бы, что хоткей автоматически ставился при установке нашего пакета

@nixel2007 Какие варианты возможны?

**Comment by nixel2007** [comment]
@artbear  хоткеи так же конфигурятся в cson-файле, в пакете ты можешь их объявить (правда не уверен, что можно переопределить чужой пакет). Но, имхо, переопределять стандартное поведение чужого пакета как-то некошерно. Лучше описать это в ридми/вики

**Comment by artbear** [comment]
В #47 и других issue у тебя указан хоткей `F12`, а по умолчанию хоткей другой.
Вот и возник мой вопрос.

ИМХО нужно:
- либо написать, что хоткеи для таких-то действий по умолчанию такие-то
- либо автоматически поставить нужные нам хоткеи (например, привычные из мира 1С и Снегопата)
- либо предоставить просто текст `keymap.cson` c нужными хоткеями с указанием, как и куда вставить текст из этого файла.

Возможно, последнего пункта будет достаточно

**Comment by nixel2007** [comment]
> В #47 и других issue у тебя указан хоткей F12, а по умолчанию хоткей другой.

Опечатался, да.

> ИМХО нужно:

либо написать, что хоткеи для таких-то действий по умолчанию такие-то
либо автоматически поставить нужные нам хоткеи (например, привычные из мира 1С и Снегопата)
либо предоставить просто текст keymap.cson c нужными хоткеями с указанием, как и куда вставить текст из этого файла.
Возможно, последнего пункта будет достаточно

Я тоже за последний пункт.

**Comment by nixel2007** [comment]
Поправил хоткей в описании. Меня больше напрягает то, что ctrl-alt-down помимо GoToDef так же является хоткеем переворачивания экрана на 180 градусов :D

**Comment by artbear** [comment]
:)

**Comment by artbear** [comment]
В Атоме для установки хоткея `F12` для действия `Goto Declaration` нужно выполнить следующее:
- убедиться, что установлен goto
- нажать `File`, далее `Open Your Keymap`
- в конец открывшегося файла вставить текст ниже
```
'.platform-win32 atom-workspace atom-text-editor':
  'F12': 'goto:declaration'
```
- сохранить файл
- проверить переход к определению на своем `os\bsl`-файле

**Comment by nixel2007** [comment]
@artbear Ты перезаходил в атом после этого?

Я делал такую настройку в пятницу, не работало. Сейчас ничего не менял, попробовал - заработало. Единственная разница - сегодня я перезапускал атом, а в пятницу просто жал ctrl-shift-r

**Comment by nixel2007** [comment]
> '.platform-win32 atom-workspace atom-text-editor':
  'F12': 'goto:declaration'

А вот тут может поджидать опасность - здесь явно прописана архитектура. Надо полную инструкцию - settings -> keybindings -> search goto -> click on copy button -> open keymap -> past

**Comment by artbear** [comment]
@nixel2007 только что проверял.
было странно, в первый раз сделал, не получилось, т.к. в keymap оказался хоткей от goto, а не f12
исправил вручную на f12, сохранил и не перезапуская Атом и даже не закрывая файл keymap, все заработало.

**Comment by artbear** [comment]
Про архитектуру согласен.
тогда такой вариант, также работающий

В Атоме для установки хоткея `F12` для действия `Goto Declaration` нужно выполнить следующее:
- убедиться, что установлен goto
- нажать `File`, далее `Open Your Keymap`
- в конец открывшегося файла вставить текст ниже
```
'atom-workspace atom-text-editor':
  'F12': 'goto:declaration'
```
- сохранить файл
- проверить переход к определению на своем `os\bsl`-файле

**Comment by nixel2007** [comment]
@artbear Если так тоже работает, то ок.

**Comment by artbear** [comment]
@nixel2007 да, я проверил, работает.

**Comment by artbear** [comment]
Куда бы теперь этот рецепт поместить?

**Comment by nixel2007** [comment]
Я вижу это примерно так:
в файле https://github.com/xDrivenDevelopment/atom-language-1c-bsl/README.md

Поддержка языка 1С:Предприятие 8 (BSL) в Atom

Добавляет подсветку синтаксиса файлам *.bsl и *.os в Atom.

Дополнительные возможности:
 * Запуск скриптов на oscript <линк на страницу wiki с инструкцией по настройке>
 * Список процедур и функций <линк>
 * Переход к определению (Go to declaration) <линк (возможно на ту же страницу, что и в пункте 2>
 * Другие фиче-пункты, когда они появятся :)

<прочий важный из readme>

**Comment by nixel2007** [comment]
@artbear хочу отметить, что фича
> Запуск скриптов на oscript <линк на страницу wiki с инструкцией по настройке>

еще не вошла в релиз.

**Comment by artbear** [comment]
@nixel2007 да, по запуску скриптов я все жду
по доке и ее размещению согласен

**Comment by nixel2007** [comment]
Инструкции для Atom и ST добавлены.

**Comment by nixel2007** [comment]
Обсуждение реализации для VSC перенесено в #60
