### ISSUE TITLE
Список процедур и функций

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#43]
Добавить возможность открывать список функций текущего файла или описать пакеты/настройки, которые позволят это сделать.

В Atom, например, при установке пакета https://atom.io/packages/goto и нажатии `ctrl-r` открывается список всех процедур и функций.
Помню, эту возможность хотел иметь @artbear

**Comment by EvilBeaver** [comment]
Плюсую!

**Comment by nixel2007** [comment]
В ST список процедур и функций доступен по сочетанию Ctrl+R

**Comment by nixel2007** [comment]
В VSC что-то с этим совсем тяжко. Надо описывать какой-то DocumentProvider, WorkspaceProvider прямо в js-файлах библиотеки...  
Как-то вообще все очень тяжко в vsc. Почти каждую фичу надо кодить с нуля.

**Comment by EvilBeaver** [comment]
А может объявить, что VSC пока не поддерживается?
И да, @nixel2007 не знаешь, случайно, почему у меня в Atom автодополнение не работает совсем? Оно там сразу должно работать, ничего отдельно включать не надо?

**Comment by nixel2007** [comment]
@EvilBeaver В смысле вообще не поддерживается или по данной фиче? :)

> И да, @nixel2007 не знаешь, случайно, почему у меня в Atom автодополнение не работает совсем?

Хм, действительно... Вообще по идее встроенный autocomplete+ должен обычный посимвольный автокомплит обеспечивать. Повесишь issue?

**Comment by EvilBeaver** [comment]
@nixel2007 добавил issue #50

**Comment by EvilBeaver** [comment]
@artbear а почему метка ST добавлена? В нем тоже у тебя не работает? У меня в Sublime все в порядке с этим.

**Comment by artbear** [comment]
Эту фичу где/как будем документировать?

**Comment by nixel2007** [comment]
@artbear пока это только идея, надо еще посмотреть, как с этим работает vsc. 
Думаю, что в 1c-syntax должна быть сводная табличка, как в https://github.com/xDrivenDevelopment/1c-syntax/issues/47, а в репо пакетов - ее кусочек по конкретному редактору. возможно, с более подробным описанием на вики, если требуется.

**Comment by artbear** [comment]
Ага, я пишу именно такую таблицу. ишью #47 заведена, достаточно
Спасибо за эту фичу, давно люблю подобный быстрый список

пн, 28 дек. 2015 г. в 13:25, Nikita Gryzlov <notifications@github.com>:

**Comment by artbear** [comment]
В Атоме с пакетом `goto` еще полезно `Ctrl+Shift+R` - если открыть папку как проект, то этот хоткей позволит получить список всех методов всех файлов в каталоге (и вложенных, если я не ошибаюсь) и найти/спозицинироваться на нужном методе в нужном файле. 
Довольно удобно.

**Comment by nixel2007** [comment]
В ST так же.

**Comment by JohnyDeath** [comment]
А можно ли сделать так, чтобы фильтр в списке процедур и функций был регистронезависимый? (Пока говорю про ST и его штатное ctrl+R)

**Comment by nixel2007** [comment]
Хм, не обращал внимания на такое поведение.
Вроде было какое-то обсуждение на [форму ST](https://www.sublimetext.com/forum/viewtopic.php?f=3&t=15427). Не знаю, добавили ли полностью такую поддержку.

**Comment by artbear** [comment]
В первую очередь на Атоме проверил регистронезависимость,все работает
правильно

вт, 29 Дек 2015, 11:12, Nikita Gryzlov <notifications@github.com>:

**Comment by kuntashov** [comment]
Подтверждаю @JohnyDeath - в SublimeText (использую 3.0) список методов регистрозависимый: 
1. Открываю файл src/json.os из библиотеки json и нажимаю Ctrl+R, открывается список методов
2. Начинаю набирать "прочитать" - позиционируется на функции "jsonЗаписатьСтроку", список становится пустым
3. Начинаю набирать "Прочитать" - в списке остаются только методы, у которых в названии есть Прочитать , в модуле позиционирование курсора осуществляется на первом таком методе - ПрочитатьJSON() - это правильно.

Ожидаю, что в случае 2 также будет позиционироваться на этом же методе.

**Comment by nixel2007** [comment]
Описано для ST и Atom.

**Comment by nixel2007** [comment]
Обсуждение vsc перенесено в #59
