### ISSUE TITLE
Точка с запятой в определении процедуры

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#45]
Если в определении процедуры/функции после скобок есть точка с запятой (а синтаксис это позволяет), то вся функция начинает подсвечиваться, кхм, странно :)
![default](https://cloud.githubusercontent.com/assets/1132840/11979864/b73a8ff0-a9a7-11e5-8899-cff2322aa0c2.PNG)

Если указан Экспорт без пробела, то так же рисуется некорректно
![default](https://cloud.githubusercontent.com/assets/1132840/11979920/14c2f0a4-a9a8-11e5-8c53-21fc38ba4b49.PNG)

**Comment by bambr1975** [comment]
Вроде достаточно поправить с + на *
(?i:\)\s*((Экспорт|Export)(?=[^\wа-яё]|$))?)

**Comment by nixel2007** [comment]
@bambr1975 похоже на то.
