### ISSUE TITLE
Сформировать таблицу фич и вставить в readme/wiki

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#47]
Типа вот такой

| Функционал | ST | Atom | VSC |
|-----------------------------------------|:------------------------------:|-----------------------------------------------------|---------------------------|
| Список процедур и функций | Встроенный, ctrl-r/ctrl-shif-r | Требуется установить пакет goto, ctrl-r/ctrl-shif-r | Не поддерживается |
| Перейти к определению (GoTo definition) | Встроенный, F12 | Требуется установить пакет goto, Ctrl-alt-down | Не поддерживается |
| Блочное комментирование | Встроенный, ctrl-/ | Встроенный, ctrl-/ | Встроенный, ctrl-K ctrl-C |

**Comment by artbear** [comment]
Не забыть, что хоткей F12 пока нужно настраивать вручную, более подробно разбираемся в https://github.com/xDrivenDevelopment/1c-syntax/issues/42#issuecomment-167547122
