### ISSUE TITLE
Перевод строки в многострочной строке

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#48]
Появилось пожелание от коллеги:

Если набирается, например:
```
Запрос.Текст =
"ВЫБРАТЬ
```

и нажимается Enter, то на следующую строку надо добавлять символ `|`. Говорят, когда это показали на презенташке EDT, народ был очень доволен.

**Comment by bambr1975** [comment]
В Sublime Text это делается очень просто. В пользовательских настройках горячих клавиш надо добавить
```
[
	{ "keys": ["enter"], "command": "run_macro_file", "args": {"file": "res://Packages/1c-syntax/AddPipe.sublime-macro"}, "context":
		[
			{ "key": "eol_selector", "operator": "equal", "operand": "string.interpolated.bsl", "match_all": true }
		]
	},
]
```
А в папку 1c-syntax положить файлик AddPipe.sublime-macro с текстом:
```
[
    {"command": "insert", "args": {"characters": "\n|"}}
]
```

**Comment by kuntashov** [comment]
> Говорят, когда это показали на презенташке EDT, народ был очень доволен
Не прошло и 10 лет ))))

**Comment by bambr1975** [comment]
Для Atom потруднее: там в свой init.coffee надо добавить:
```
atom.commands.add 'atom-text-editor',
  'user:addpipe': (event) ->
    editor = @getModel()
    editor.insertText('\n')
    scope = editor.getLastCursor().getScopeDescriptor().toString()
    if  scope==".source.bsl .string.interpolated.bsl"
      editor.insertText('|')
```
и для своего keymap.cson определить:
```
"atom-text-editor[data-grammar='source bsl']":
  'enter': 'user:addpipe'
```

**Comment by nixel2007** [comment]
@bambr1975 отлично, спасибо! 

Есть только вопрос по поводу перевода строки - может стоит его определять? В атоме есть настройка в каком стиле его вставлять (win или linux). Думаю, для ST это тоже может быть важно.

**Comment by nixel2007** [comment]
@bambr1975 можно тебя попросить заодно и под vsc посмотреть? ^_^

**Comment by bambr1975** [comment]
я пас... Попробуй найти здесь https://code.visualstudio.com/docs/extensionAPI/vscode-api хоть что-нибудь похожее на insert text))))) (кроме конструктора автокомплита)

**Comment by bambr1975** [comment]
Ну что, подходит?

**Comment by nixel2007** [comment]
@bambr1975 с виду подходит. На больших текстах не тормозит?

Спасибо!

**Comment by nixel2007** [comment]
@bambr1975 если я правильно понял код, ты берёшь весь текст с начала и до текущей позиции. В нем могут быть комментарии с непарными кавычками :/

**Comment by bambr1975** [comment]
ага)). Можно парсить регеэкспами (опыт есть), но тогда будет еще сложнее и дольше)))

**Comment by bambr1975** [comment]
Попытка №2:
```
var vscode = require('vscode');

function activate(context) {
	var disposable = vscode.commands.registerCommand('extension.addpipe', function () {
			var editor = vscode.window.activeTextEditor;
			if (editor != undefined) {
				var position = editor.selection.active;
				var textline = editor.document.getText(new vscode.Range(new vscode.Position(0, 0), position));
				var Regex = /(\/\/.*\n\r?)|("(""|[^"]*)*")|("[^"]*$)|([^"\/]+)/gm;
				while ((ArrStrings = Regex.exec(textline)) != null) {
					var match = ArrStrings[0];
					var stringmatsh = ArrStrings[4];
				}
				if (stringmatsh != undefined) {
					editor.edit(function (editBuilder) {
						editBuilder.insert(new vscode.Position(position.line, position.character), '\n|');
					});
				} else {
					editor.edit(function (editBuilder) {
						editBuilder.insert(new vscode.Position(position.line, position.character), '\n');
					});
				}
			}
		});
	context.subscriptions.push(disposable);
}
exports.activate = activate;
```

**Comment by nixel2007** [comment]
Брутально, но вроде логично. :)

**Comment by bambr1975** [comment]
https://ru.wiktionary.org/wiki/брутальный или https://ru.wiktionary.org/wiki/брутальность ?
поясни)

**Comment by nixel2007** [comment]
Как раз "жестоко", "жестко", в значении "в лоб",  "напрямик". :)  
Видимо, словечко, больше присущее моему кругу общения

**Comment by bambr1975** [comment]
О том, что получается коряво - я в курсе))) (см. https://github.com/xDrivenDevelopment/1c-syntax/issues/48#issuecomment-169009284) Было бы здорово, если бы нашелся более изящный способ.

**Comment by bambr1975** [comment]
Обнаружился случай неправильного определения. В регулярку внесены правки.

**Comment by nixel2007** [comment]
Готова реализация для всех пакетов. Добавлено описание в README.
@bambr1975 огромное спасибо за помощь!
