### ISSUE TITLE
Не работает автодополнение в Atom

### ISSUE THREAD

**Issue by EvilBeaver** [xDrivenDevelopment/1c-syntax#50]
По мотивам переписки в задаче #43. 

В Atom не срабатывает автодополнение (autocompletion) при вводе текста в файле *.os

**Comment by nixel2007** [comment]
В `bsl` тоже.

**Comment by nixel2007** [comment]
Опытным путем выяснено, что автодополнение работает на процедуры, функции и параметры функций, объявленные в этом же модуле.

Т.е. оно не такое "простое", как в ST, а подсвечивает именно токены, которые определились в тот или иной scope.

Есть два варианта решения.  
Первый - через грамматику. Стоит посмотреть другие пакеты с грамматикой.  
На вскидку нужно:
 * Определение токенов слева от равно как переменных (при этом надо отделить равно как сравнение)
 * Определение токенов, следующих до открывающей скобки как функции (но не support, а какой-то другой scope)

Второй вариант - написать свой провайдер для автодополнения.

Более подробно - https://github.com/atom/autocomplete-plus

**Comment by EvilBeaver** [comment]
А разве он не делает, как N++ и тот же Sublime? Просто подсказывает слова из тех, что уже есть в открытом файле?

**Comment by nixel2007** [comment]
@evilbeaver вот в том-то и дело, что нет :) он вытаскивает подсказки по данным токенайзера.

**Comment by bambr1975** [comment]
Мне удалось заставить заработать автодополнение только для англоязычных scope и терминов, добавив в файл settings - language-1c-bsl.cson секции autocomplete/symbols и editor/completions аналогично https://github.com/atom/language-php/blob/master/settings/language-php.cson и https://github.com/atom/language-sass/blob/master/settings/language-sass.cson . Но что делать с русскоязычными scope и терминами - я не знаю(((

**Comment by bambr1975** [comment]
У меня заработало русскоязычное дополнение!!!! Правда, пришлось распотрошить app.asar и в его папке node_modules/autocomplete-plus/lib поменять все регулярки, использующие конструкцию /w на /wа-яёА-ЯЁ (ну и немного поколдовать с /b) - всего три файла, где потребовалось такое исправление: autocomplete-manager.js, suggestion-list.js и symbol-provider.js. Но факт, оно работает!!!!!

**Comment by EvilBeaver** [comment]
@bambr1975 позволь поинтересоваться, а как ты находишь все эти места, где нужно правки внести?

-----Исходное сообщение-----
От: "bambr1975" <notifications@github.com>
Отправлено: ‎03.‎01.‎2016 9:11
Кому: "xDrivenDevelopment/1c-syntax" <1c-syntax@noreply.github.com>
Копия: "Andrei Ovsiankin" <ovsiankin.aa@gmail.com>
Тема: Re: [1c-syntax] Не работает автодополнение в Atom (#50)

У меня заработало русскоязычное дополнение!!!! Правда, пришлось распотрошить app.asar и в его папке node_modules/autocomplete-plus/lib поменять все регулярки, использующие конструкцию /w на /wа-яёА-ЯЁ (ну и немного поколдовать с /b) - всего три файла, где потребовалось такое исправление: autocomplete-manager.js, suggestion-list.js и symbol-provider.js. Но факт, оно работает!!!!!

**Comment by bambr1975** [comment]
Ну в settings есть autocomplete-plus, а в файлах на компьютере нет. Значит, надо искать по вхождению в файлы. По вхождению нашлось в app.asar. Google подсказал, что это архив и что его открывать нужно с помощью командной строки node.js. А дальше дело техники:
```
npm install asar -g
asar e "ПутьКapp.asar" aaa 
```
в папке пользователя в подпапке ааа будут развернутые архивы настроек их можно поправить и потом опять в командной строке node.js
```
asar p aaa "ПутьКapp.asar"
```

**Comment by nixel2007** [comment]
Может попробовать оформить пуллреквест?

**Comment by bambr1975** [comment]
там мест, где используется \w вообще-то больше, чем два (как минимум, для движка fuzzy надо по аналогии поправить fuzzy-provider.js в 18-й строке и тоже поменять кодировку на UTF-8 без BOM) . Просто этих двух мест достаточно, чтобы оно на движке Symbol нормально заработало. А чтобы оформлять пуллреквест надо еще и во всем остальном разбираться...

**Comment by nixel2007** [comment]
Хотя не думаю, что примут такие изменения... Все же помимо латиницы и кириллицы есть еще куча письменностей. На мой взгляд, стоит либо искать путь с каким-нибудь init-скриптом или все же описывать провайдер (может быть  по большей части копипастом)

**Comment by EvilBeaver** [comment]
@bambr1975 стоит ли говорить, что я впечатлен твоими детективными талантами?! Ты от меня это и так уже слышала не раз :+1: :smile:

**Comment by nixel2007** [comment]
Строки, которые нужно поменять для версии 1.3.3:  
autocomplete-manager.js - 61 строка:
```javascript
AutocompleteManager.prototype.prefixRegex = /(^|\s|['"~`!@#\$%^&*\(\)\{\}\[\]=\+,/\?>])(([\wа-яёА-ЯЁ]+[\wа-яёА-ЯЁ-]*)|([.:;[{(< ]+))$/;
```

symbol-provider.js - 18 строка:
```javascript
SymbolProvider.prototype.wordRegex = /(^|\s)\w*[a-zа-яёA-ZА-ЯЁ_-]+\w*(?=[^\wа-яёА-ЯЁ]|$)/g;
```

**Comment by EvilBeaver** [comment]
@nixel2007 это надо каждому пользователю поменять у себя или это языковой пакет сможет сделать?

**Comment by nixel2007** [comment]
@EvilBeaver Пока каждому пользователю, к сожалению. Надо писать свой провайдер для автокомплита.

**Comment by artbear** [comment]
Предлагаю выложить готовые файлы с исправлениями и немного описать, как их
установить

вт, 12 Янв 2016, 15:03, Nikita Gryzlov <notifications@github.com>:

**Comment by EvilBeaver** [comment]
@artbear можно не готовые файлы, а хотя бы сказать, где найти те, которые править :smile:

**Comment by nixel2007** [comment]
Так @bambr1975 же выше писала. Вот [здесь](https://github.com/xDrivenDevelopment/1c-syntax/issues/50#issuecomment-168484670)

**Comment by nixel2007** [comment]
В моем случае "ПутьКapp.asar" был вот таким: `C:\Users\na_gryzlov\AppData\Local\atom\app-1.3.3\resources\app.asar`

**Comment by artbear** [comment]
У нас уже куча инструкций в этом issue, сведите в одну сводную, пожалуйста

вт, 12 Янв 2016, 15:13, Nikita Gryzlov <notifications@github.com>:

**Comment by bambr1975** [comment]
у меня была идея предложить https://github.com/atom/autocomplete-plus добавить специальную настройку в пакет, аналогичную wordPattern в https://code.visualstudio.com/docs/extensionAPI/vscode-api#LanguageConfiguration, чтобы в эти регулярки каждый мог добавлять те диапазоны, которые соответствуют его письменности (для кириллицы это будет [а-яёА-ЯЁ], например). Только как бы это им правильно сформулировать? а сводная инструкция - это https://github.com/xDrivenDevelopment/1c-syntax/issues/50#issuecomment-168484670 плюс https://github.com/xDrivenDevelopment/1c-syntax/issues/50#issuecomment-170835438 . Вообще, @artbear , ты же любишь создавать issue, может, достучишься до https://github.com/atom/autocomplete-plus ?

**Comment by EvilBeaver** [comment]
Мы с @artbear уже старенькие и тупенькие. Мы без инструкции уже не могем :trollface:

**Comment by nixel2007** [comment]
Я понимаю, что я немного офигевшая моська, но я нашел и пинганул вот эту ишу - https://github.com/atom/autocomplete-plus/issues/76

**Comment by EvilBeaver** [comment]
А я там же и вот это нашел: https://github.com/richrace/highlight-selected/issues/105
Кто-то правит файлы 1С-ки в Атоме. И, кстати, ник этого товарища мне уже попадался на просторах гитхаба. По-моему, даже где-то в xDD сообществе или в silverbulleters.

**Comment by nixel2007** [comment]
Больше народу - веселее :) плюс в данном репо еще 18 issue, простора для творчества вагон :D

**Comment by nixel2007** [comment]
Строки, которые нужно поменять для версии 1.4.0 (не изменилось с 1.3.3):  

autocomplete-manager.js - 61 строка:
```javascript
AutocompleteManager.prototype.prefixRegex = /(^|\s|['"~`!@#\$%^&*\(\)\{\}\[\]=\+,/\?>])(([\wа-яёА-ЯЁ]+[\wа-яёА-ЯЁ-]*)|([.:;[{(< ]+))$/;
```

symbol-provider.js - 18 строка:
```javascript
SymbolProvider.prototype.wordRegex = /(^|\s)\w*[a-zа-яёA-ZА-ЯЁ_-]+\w*(?=[^\wа-яёА-ЯЁ]|$)/g;
```

**Comment by nixel2007** [comment]
Строки, которые нужно поменять для версии **1.4.1** (не изменилось с 1.3.3):  

autocomplete-manager.js - 61 строка:
```javascript
AutocompleteManager.prototype.prefixRegex = /(^|\s|['"~`!@#\$%^&*\(\)\{\}\[\]=\+,/\?>])(([\wа-яёА-ЯЁ]+[\wа-яёА-ЯЁ-]*)|([.:;[{(< ]+))$/;
```

symbol-provider.js - 18 строка:
```javascript
SymbolProvider.prototype.wordRegex = /(^|\s)\w*[a-zа-яёA-ZА-ЯЁ_-]+\w*(?=[^\wа-яёА-ЯЁ]|$)/g;

**Comment by nixel2007** [comment]
Строки, которые нужно поменять для версии **1.4.2** (не изменилось с 1.3.3):  

autocomplete-manager.js - 61 строка:
```javascript
AutocompleteManager.prototype.prefixRegex = /(^|\s|['"~`!@#\$%^&*\(\)\{\}\[\]=\+,/\?>])(([\wа-яёА-ЯЁ]+[\wа-яёА-ЯЁ-]*)|([.:;[{(< ]+))$/;
```

symbol-provider.js - 18 строка:
```javascript
SymbolProvider.prototype.wordRegex = /(^|\s)\w*[a-zа-яёA-ZА-ЯЁ_-]+\w*(?=[^\wа-яёА-ЯЁ]|$)/g;

**Comment by artbear** [comment]
@bambr1975 @nixel2007 
>В settings есть autocomplete-plus, а в файлах на компьютере нет. Значит, надо искать по вхождению в файлы. По вхождению нашлось в app.asar. Google подсказал, что это архив и что его нужно открывать с помощью командной строки node.js. А дальше дело техники:
```
npm install asar -g
asar e "ПутьКapp.asar" aaa 
```
В папке пользователя в подпапке ааа будут развернутые каталоги встроенных настроек атома. Их можно поправить, и потом опять в командной строке node.js написать:
```
asar p aaa "ПутьКapp.asar"
```

У меня файла npm нет, нужно еще отдельно что-то поставить чтоли?

**Comment by bambr1975** [comment]
node.js у тебя стоит? Можно зайти в программы и компоненты и в custom setup проверить, что стоит npm package manager и Add to PATH. И все действия делать из Node.js command prompt

**Comment by artbear** [comment]
>node.js у тебя стоит

конечно, нет :)
без него никак?

**Comment by bambr1975** [comment]
asar - это модуль node.js. Чтобы его запустить, node.js просто необходим)))

**Comment by EvilBeaver** [comment]
Вот поэтому, я присматриваюсь к устройству autocomplete-plus с целью сделать туда пулреквест. Без этого Атом у 1С-ников не поедет. Ставить Ноду и с каждым релизом править какие-то строки в архивах, безусловно увлекательно, но приедается быстро.

**Comment by artbear** [comment]
>Вот поэтому, я присматриваюсь к устройству autocomplete-plus с целью сделать туда пулреквест. Без этого Атом у 1С-ников не поедет. Ставить Ноду и с каждым релизом править какие-то строки в архивах, безусловно увлекательно, но приедается быстро.

+1

**Comment by nixel2007** [comment]
Можно попробовать оформить пулл-реквест по вот этой issue. https://github.com/atom/autocomplete-plus/issues/76

там в конце есть фикс, но он не оформлен как PR, а просто лежит в форке

**Comment by bambr1975** [comment]
единственное, что меня расстраивает в этом фиксе, что там не учтен fuzzyprovider, который также является частью autocomplete-plus. Если его учесть - должны принять (как мне кажется)

**Comment by nixel2007** [comment]
@bambr1975 там еще зависимость одна добавляется. но все равно, польза от этого будет огромная конечно

**Comment by bambr1975** [comment]
Кстати, видели попытку ```https://github.com/atom/autocomplete-plus/pull/607```

**Comment by nixel2007** [comment]
@bambr1975 видел. там еще где-то проскакивал вариант с регуляркой в два экрана со всеми юникодными нелатинскими символами. с внешней зависимостью, имхо лучше.

**Comment by bambr1975** [comment]
вот честно. у Атома есть "Atom have ```editor.nonWordCharacters```" В vs code проблема автодополнения была решена, как ```document.gettext().split(/[^а-яёА-ЯЁ_a-zA-Z]+/)```
Тут ведь тоже можно сделать ```document.gettext().split(editor.nonWordCharacters)``` (ну или что-то типа этого). Но предложенный в том фиксе вариант может быть тянет за собой меньше изменений.

**Comment by nixel2007** [comment]
Господи, два пива господину, который пофиксит эту хрень в Атоме

**Comment by nixel2007** [comment]
Строки, которые нужно поменять для версии **1.4.3** (не изменилось с 1.3.3):  

autocomplete-manager.js - 61 строка:
```javascript
AutocompleteManager.prototype.prefixRegex = /(^|\s|['"~`!@#\$%^&*\(\)\{\}\[\]=\+,/\?>])(([\wа-яёА-ЯЁ]+[\wа-яёА-ЯЁ-]*)|([.:;[{(< ]+))$/;
```

symbol-provider.js - 18 строка:
```javascript
SymbolProvider.prototype.wordRegex = /(^|\s)\w*[a-zа-яёA-ZА-ЯЁ_-]+\w*(?=[^\wа-яёА-ЯЁ]|$)/g;

**Comment by EvilBeaver** [comment]
@bambr1975 а правильно я тебя понял, что без wordRegex нет смысла реализовывать autocomplete provider, т.к. до провайдера даже не дойдут русские слова, их обрежет еще раньше?

**Comment by nixel2007** [comment]
@EvilBeaver на пиво что ли купился? :D

**Comment by EvilBeaver** [comment]
@nixel2007 а я и не сказал, что прям вот буду делать. Но погляжу одним глазом.

**Comment by EvilBeaver** [comment]
Уже есть пулреквест https://github.com/atom/autocomplete-plus/pull/607 но он не прошел автотест

**Comment by nixel2007** [comment]
он же только для немецкого языка.

2016-02-03 16:21 GMT+03:00 Andrei Ovsiankin <notifications@github.com>:

**Comment by EvilBeaver** [comment]
@nixel2007 вместе с @bambr1975 обсудили, что можно взять и сделать форк от репо i-flame (ты ему писал, чтобы он PR сделал, но он молчит) И самим сделать PR в атом по его изменениям.

**Comment by nixel2007** [comment]
@EvilBeaver Боюсь, надо будет именно повторить замены, которые делал i-flame, так как регулярки поменялись, значит и замены надо переделать. 
Плюс @bambr1975 еще говорила про fuzzy-provider, его тоже надо посмотреть.

Возьмется кто-нибудь или пока повисит?

**Comment by nixel2007** [comment]
Коллеги, особенно @bambr1975 и @EvilBeaver.
Поглядите, пожалуйста, мой коммит https://github.com/nixel2007/autocomplete-plus/commit/e0640e123bc1aa5fb613ae001f6426dab524b047

Если согласны, то оформлю PR.

PS. Чтобы протестировать надо:
* скачать репо
* открыть командную строку в папке репо
* `apm install`
* `apm link --dev`
* открыть атом в дев-режиме, например через `atom --dev .`

**Comment by nixel2007** [comment]
В текущем состоянии падают тесты. master-ветка не падает. надо разобраться.

PS. Запуск тестов через <kbd>Alt-Ctrl-P</kbd> в атоме

**Comment by nixel2007** [comment]
@bambr1975 @EvilBeaver начал делать переход на XRegExp. Есть некоторые проблемы.
1) начальный \b. Если его заменить на (?:\\s|^), например, вот здесь - https://github.com/nixel2007/autocomplete-plus/commit/afde0f66ba3e397a26f2ed73cce150139bf79cf8#diff-30766d99d786ae2649e27d8d0431a220R13 то тесты начинают падать. Такая же беда в autocomplete-manager.coffee и регулярке prefixRegex
2) Кто-нибудь может нормально заэкранировать все символы в prefixRegex в autocomplete-manager.coffee? :) я что-то совсем запутался

**Comment by nixel2007** [comment]
Тесты можно провести локально:
* скачав репо
* `apm install --dev
* `apm link --develop`
* `atom --dev .`
* <kbd>Alt-Ctrl-P</kbd>

**Comment by bambr1975** [comment]
>Кто-нибудь может нормально заэкранировать все символы в prefixRegex в autocomplete-manager.coffee?

Так у https://github.com/l-flame/autocomplete-plus/commit/7f986b7bf6ff7bf995e87bc776b174e107085f50 нормально заэкранировано. Проверено с помощью http://cidocs.ru/coffeescript/

**Comment by nixel2007** [comment]
> Так у l-flame/autocomplete-plus@7f986b7 нормально заэкранировано.

меня смущает, что какие-то слэши он экранировал, а какие-то нет. это нормально?

**Comment by bambr1975** [comment]
меня тоже смущало, но после преобразования в js все корректно получается

**Comment by nixel2007** [comment]
Да вот как-то нет.
```coffee
prefixRegex: RegExp '''(\\b|['"~`!@#\$%^&*\(\)\{\}\[\]=\+,/\?>])((\\w+[\\w-]*)|([.:;[{(< ]+))$'''
```
падает. Хотя заэкранировано точно так же, как у него. Специально проверил через обычный RegExp

**Comment by nixel2007** [comment]
Вот так не упало:
```coffee
prefixRegex: RegExp '''(\\b|['"~`!@#\$%^&*\\(\\)\\{\\}\\[\\]=\+,/\\?>])((\\w+[\\w-]*)|([.:;[{(< ]+))$'''
```

**Comment by nixel2007** [comment]
Если начальное `\\b` убрать или заменить на (?:\\s|^) оно падает.

**Comment by bambr1975** [comment]
убери начальное \\b, а после первых скобок поставь признак необязательных (вопрос). Примерно вот так:
```
prefixRegex: xregexp '''(['"~`!@#\$%^&*\\(\\)\\{\\}\\[\\]=\+,/\\?>])?((\\p{L}+[\\p{L}-]*)|([.:;[{(< ]+))$'''
```
У меня тесты прошли и автокомплит работает корректно

**Comment by nixel2007** [comment]
В общем как-то так:
`https://github.com/atom/autocomplete-plus/pull/667`

**Comment by nixel2007** [comment]
Кстати, внезапно появилась возможность не менять строчки вручную.
Для работы автодополнения нужно:
* `cd %userprofile%\.atom\packages`
* `git clone https://github.com/nixel2007/autocomplete-plus.git`
* `cd autocomplete-plus`
* `git checkout fix-76-unicode-support`
* `git pull`
* `apm install --dev`

После этого, если запускать Атом в дев-режиме, то автокомплит будет работать корректно по нашим правкам.

**Comment by artbear** [comment]
Ура, отличная новость. Завтра проверю, отпишусь.
Включу в свой developer.start.cmd

вт, 9 Фев 2016, 21:41, Nikita Gryzlov <notifications@github.com>:

**Comment by nixel2007** [comment]
@artbear это временное решение, ты же понимаешь, да? :)

**Comment by artbear** [comment]
@nixel2007 про временность я понимаю, меня как пользователя/разработчика такой вариант устраивает.
А ноду я так и не поставил :)

**Comment by artbear** [comment]
@nixel2007 Заценил работу автодополнения.
Очень удобно.
Спасибо за код скрипта, добавил его в ветку feature/developers.start.cmd

**Comment by nixel2007** [comment]
@artbear только что понял, что в инструкции я указываю установку пакета не в дев-окружение. посмотри, пожалуйста, может оно у тебя и без --dev работает?

**Comment by allustin** [comment]
@nixel2007 оно будет работать и без `--dev` - проверено.

@artbear develop.start.cmd ?

**Comment by nixel2007** [comment]
Шикарные новости для пользователей Атома! Смержили наш пулл-реквест https://github.com/atom/autocomplete-plus/pull/667 с поддержкой юникода в автокомплите. обещают добавить в Атом версии 1.7.0

**Comment by kuntashov** [comment]
@nixel2007 Круто!

**Comment by EvilBeaver** [comment]
@nixel2007 @bambr1975  поздравляю, это очень круто!!!

**Comment by EvilBeaver** [comment]
@nixel2007 а какая у них политика релизов? Сейчас актуальна версия 1.5. А когда ожидается 1.7?

**Comment by nixel2007** [comment]
Насчёт политики не знаю. Сейчас в бете 1.6-beta8. Для 1.5 было всего 5 бет, если не ошибаюсь. Так что думаю, что скоро выпустят 1.6.

Фичей уже можно пользоваться, если склонировать репо autocomplete-plus  в стандартный каталог пакетов атома. Причём даже в Master ветке, надо только галочку ткнуть в настройках. 

Отправлено с моего HTC

----- Ответное сообщение -----
От: "Andrei Ovsiankin" <notifications@github.com>
Кому: "xDrivenDevelopment/1c-syntax" <1c-syntax@noreply.github.com>
Копия: "Nikita Gryzlov" <nixel2007@gmail.com>
Тема: [1c-syntax] Не работает автодополнение в Atom (#50)
Дата: ср, марта 9, 2016 19:54

@nixel2007 а какая у них политика релизов? Сейчас актуальна версия 1.5. А когда ожидается 1.7?

&mdash;

**Comment by nixel2007** [comment]
Вышел стабильный релиз Atom 1.7, в который включены наши правки по поддержке Юникода при работе автодополнения.

Если вы по инструкции ставили пакет autocomplete-plus вручную, то крайне (очень-очень) рекомендуется его удалить. Напомню, что устанановлен он был сюда: %userprofiles%\.atom\packages\autocomplete-plus
