### ISSUE TITLE
Указать все функции глобального контекста

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#52]
Добавить в грамматику все функции из ветки глобального контекста.

**Comment by nixel2007** [comment]
Как же их много, божечки :)

**Comment by artbear** [comment]
А ты их как получаешь,добываешь?

пн, 28 Дек 2015, 19:23, Nikita Gryzlov <notifications@github.com>:

**Comment by nixel2007** [comment]
@artbear парсера синтаксис-помощника у меня под рукой нет, так что пока руками копипасчу. По идее можно написать что-нибудь на основе Инструментов Разработчика, например, но пока лень.

**Comment by bambr1975** [comment]
https://snegopat.ru/forum/viewtopic.php?f=1&t=51&start=40
начиная со строки 7256

**Comment by nixel2007** [comment]
@bambr1975 ох, какая прелесть, спасибо! 
@awa можно тебя попросить сгенерить новый файл под 8.3.7?

**Comment by nixel2007** [comment]
@awa15 можно тебя попросить сгенерить новый файл под 8.3.7?

**Comment by awa15** [comment]
@nixel2007 https://yadi.sk/d/pGuVZrkGmZFqC

**Comment by nixel2007** [comment]
@awa15 спасибо!

**Comment by awa15** [comment]
Только 1С, начиная с 8.3.6, убрала в синтакс-помощнике раздел "Встроенные функции" и засунула все функции оттуда в глобальный контекст.

**Comment by nixel2007** [comment]
@awa15 вот поэтому я на всякий случай сразу стал смотреть СП в 8.3.7 :)

**Comment by EvilBeaver** [comment]
А я вот хотел вам предложить ограничиться встроенными функциями. Зачем весь глКонтекст поддерживать, следить там за ним, актуализировать...

**Comment by awa15** [comment]
@EvilBeaver в том-то и дело, что встроенных функций больше как-бы не существует. Как всем объяснить, что функция СтрЗаменить встроенная, и поэтому выделяется цветом, а функция СтрНачинаетсяС не встроенная, и поэтому цветом не выделяется. Никому же не интересно, что для функции СтрЗаменить есть свой код в байт-коде виртуальной машины 1С, а для СтрНачинаетсяС нету.

**Comment by EvilBeaver** [comment]
> Никому же не интересно, что для функции СтрЗаменить есть свой код в байт-коде виртуальной машины 1С, а для СтрНачинаетсяС нету.

Как раз мне интересно. Встроенные функции (в моей терминологии и ранее, в терминологии 1С) - это байткоды. Они таки встроенные и ни от чего не зависят. Они имеют право на раскраску. Все остальное это динамически подключаемые контексты и лексер про них знать не обязан. Это дает право @nixel2007 не париться с раскраской вообще всех глобальных сущностей.

Это просто призыв экономить силы - подсветить весь глобальный контекст это во-первых сложно, во-вторых, весьма возможно, что редактор от такой здоровой регулярки тупить начнет.

**Comment by nixel2007** [comment]
@evilbeaver в целом ничего не мешает добавлять "динамически подключаемые контексты" в раскраску - support.function как раз и предназначена для функций, предоставляемых фреймворком.  
Я уже добавил все функции, разделив их на блоки, чтобы не было слишком большой регулярки. Тормозов в раскраске не заметил. 

По поводу поддержки - я так и так читаю все чейнджлоги 1с, в том числе блоки про добавленные и переименнованные функции, так что добавлять время от времени (раз в квартал, судя по выходу веток 8.3 в этом году)  десяток функций в грамматику мне не сложно. Более того, можно написать простенький парсер файла, который предоставил Валерий и вообще формировать эти блоки автоматически. 

Коллеги, если не затруднит, я прошу вас присоединиться к обсуждению соседней Issue про свойства глобального контекста :) планирую выпустить релиз сегодня и хочу, чтобы в него вошёл максимум фишек по грамматике.

**Comment by awa15** [comment]
@EvilBeaver я не проверял, но есть подозрение, что и классические встроенные функции теперь тоже реализованы в глобальном контексте. Из чего я делаю такой вывод. К 1С можно подсоединиться как к Automation-серверу через COM-соединение. В этом COM-соединении доступны свойства и методы глобального контекста, но, естественно, не доступны встроенные функции! Я думаю, что раз все встроенные функции в синтакс-помощнике перенесли в глобальный контекст, то они должны быть доступны в COM-соединении, а значит реально должны быть реализованы в глобальном контексте! И тогда поддержка этих функций в виртуальной машине 1С будет оставлена только для совместимости со старым байт-кодом.
Но, повторю, это мои непроверенные измышлизмы.
@nixel2007 сорри за оффтоп.

**Comment by nixel2007** [comment]
@awa15 что уж извиняться, наоборот, спасибо за информацию! Про com-соедиение интересная идея, кстати, надо проверить.

**Comment by EvilBeaver** [comment]
@awa15 я проверял. Новые функции - это контексты, старые по-прежнему байткоды.
