### ISSUE TITLE
Свойства глобального контекста

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#54]
Думаю, стоит ли добавлять *свойства* глобального контекста.
![default](https://cloud.githubusercontent.com/assets/1132840/12025670/3eee8d5c-adc2-11e5-9f07-a36a9ffe3826.PNG)

И если стоит, то все, или некоторые (например, не добавлять менеджеры)

Мысли? @xDrivenDevelopment/1c-syntax @bambr1975

**Comment by awa15** [comment]
@nixel2007 Зависит от конечной цели проекта. Если цель - раскрасить файлы *.os в редакторе, то  OneScript эти свойства глобального контекста не поддерживает. А если цель - раскрасить файлы *.bsl (т.е. модули, выгруженные из 1С), то, имхо, было бы неплохо раскрасить. И тогда уж еще системные перечисления и системные наборы значений тоже)))

**Comment by awa15** [comment]
Кстати, я тут https://yadi.sk/d/Yk8SX60QmZbaL выложил базу Типы1С, загруженную данными из синтакс-помощника 8.3.7.1831 и обработку ВыгрузкаV8Types.epf. Возможно, по аналогии, сделать обработку выгрузки в нужном для 1c-syntax формате?

**Comment by nixel2007** [comment]
@awa15 конечная цель - раскрасить bsl. Точнее, раскрасить в принципе 1с-синтаксис не зависимо от того, поддерживаются ли данные функции в onescript или нет.  
Еще раз спасибо за базу! Я думаю, что да, можно сделать и такую выгрузку.

**Comment by EvilBeaver** [comment]
В том-то и дело, что Конфигуратор НЕ красит глобальный контекст и системные перечисления:

![image](https://cloud.githubusercontent.com/assets/2657561/12031965/ff907b7c-ae23-11e5-9e6e-95d5c91e0055.png)

```Сообщить``` и ```СтатусСообщения``` не покрашены.

**Comment by nixel2007** [comment]
@EvilBeaver Конфигуратор-то вообще особо ничего не красит. Только ключевые слова и операторы красным, да директивы и инструкции коричневым.

На сколько я могу судить по грамматикам других языков, раскраска функций глобального контекста - это обычная практика. Взять ту же раскраску питона, например:
![default](https://cloud.githubusercontent.com/assets/1132840/12032039/cea0f37e-ae24-11e5-9281-bd5b96ff0813.PNG)

Или еще более colourful-пример: 
![default](https://cloud.githubusercontent.com/assets/1132840/12032055/f8cdd784-ae24-11e5-8715-cacdb1db99a7.PNG)

К чему-то я - я не пытаюсь повторить раскраску конфигуратора - за это отвечают syntax-themes в терминах Атома, а не syntaxes-packages, коими являются наши пакеты. Я пытаюсь сформировать более-менее адекватное описание языка и инструмент, который может упростить редактирование 1с-кода (в том числе и мне) в сторонних редакторах. Плюс я лелею идею элементарного IntelliSense, а там эти функции/свойства точно понадобятся.

**Comment by EvilBeaver** [comment]
@nixel2007 Если речь о выделении именованных scopes, то я не против. Назвать только надо как-то правильно.

P.S. а intellisense мне за глаза хватает штатного из N++ и ST. Но в Atom не работает для BSL почему-то..

**Comment by nixel2007** [comment]
@EvilBeaver Надо аккуратно раскидать все свойства:
```
support — things provided by a framework or library should be below support.
 * function — functions provided by the framework/library. For example NSLog in Objective-C is support.function.
 * class — when the framework/library provides classes.
 * type — types provided by the framework/library, this is probably only used for languages derived from C, which has typedef (and struct). Most other languages would introduce new types as classes.
 * constant — constants (magic values) provided by the framework/library.
 * variable — variables provided by the framework/library. For example NSApp in AppKit.
 * other — the above should be exhaustive, but for everything else use support.other.
```

Пока явно вижу `class` и может быть `variable`.

> Но в Atom не работает для BSL почему-то..

Да, неприятность :( Надо будет разобраться за праздники.

**Comment by nixel2007** [comment]
@awa15 Возможно ли в твоей базе получить данные по разделу справки, к которому относится то или иное свойство? Вижу ссылку на раздел справки, например, `v8help://SyntaxHelperContext/objects/Global context/methods/catalog4839/Exp1003.html`  
Как бы узнать, что это именно `Глобальный контекст - Функции работы со значениями типа Число` ?

**Comment by bambr1975** [comment]
>Плюс я лелею идею элементарного IntelliSense, а там эти функции/свойства точно понадобятся

просто интересуюсь... https://www.youtube.com/watch?v=vJnZPLe67Aw видел?

**Comment by nixel2007** [comment]
@bambr1975 нет, не видел. Выглядит интересно :) 
Я мельком глядел описание интеллисенса для  vsc и атома, в целом реально сделать. 

Предлагаешь совместить усилия или что-то другое?

**Comment by bambr1975** [comment]
Описание подключения интеллисенса в vcs согласно инструкции Снегопат Reborn:
Разработка скриптов на TypeScript
Это небольшая инструкция, которая поможет скриптописателям повысить удобство и скорость разработки скриптов для снегопата. Я предлагаю вам использовать для этих целей редактор Visual Studio Code и язык TypeScript. Этот язык - развитие языка JavaScript, к которому добавлена типизация переменных, классы и модули. Скрипт на языке TypeScript транслируется его компилятором в обычный JavaScript.

Благодаря возможности подключить к редактору файлы с описанием SnegAPI и типов 1С, при разработке скриптов для снегопата в редакторе отлично работает intellisense, что делает работу быстрой и комфортной.
Начать его использование для разработки помогут несколько простых шагов. 

Скачиваем и устанавливаем Visual Studio Code: https://code.visualstudio.com/ 
Скачиваем и устанавливаем TypeScript: http://www.typescriptlang.org/#Download
Я брал "TypeScript 1.6 in VS2015" 
В папке снегопата, рядом с папками addins и core - создаем папку custom. Снегопат там ищет дополнительные пользовательские аддины. 
Создаем папку для разработки, например "develop", можно тоже в папке снегопата, рядом с addins и custom. 
В этой папке создаём подпапку std. 
Копируем все *.ts файлы из core\scripts\src в папку develop\std. 
В папке develop запускаем команду tsc --init Она создаст файл проекта tsconfig.json 
В этом файле исправляем путь к каталогу сборки, параметр "outDir". Там надо прописать путь к каталогу custom. Если папка develop рядом с ним, просто укажите: "outDir": "../custom", И добавьте параметр "emitBOM": true Файл будет выглядеть примерно так
 {
     "compilerOptions": {
         "module": "commonjs",
         "target": "es3",
         "noImplicitAny": false,
         "outDir": "../custom",
         "rootDir": ".",
         "sourceMap": false,
         "emitBOM": true
     },
     "exclude": [
         "node_modules"
     ]
 }

Запускаем Visual Studio Code:

 code.exe "путь к папке develop"

Жмем Ctrl+Shift+P, набираем conf - выбираем "Task - configure task Runner" В открывшемся файле удаляем или комментируем первый пример (с HelloWorld.ts), и раскомментируем второй, который

// A task runner that calls the Typescript compiler (tsc) and
// compiles based on a tsconfig.json file that is present in
// the root of the folder open in VSCode

В окне снегопата в меню "Разработка" выбираем "Сдампить SnegAPI в snegopat.d.ts" и "Сдампить типы 1С в v8.d.ts". Файлы создадуться в каталоге снегопата. Перемещаем их в каталог разработки (develop).

В-принципе, это всё. Теперь можно в этом каталоге создавать файлы с расширением .ts, и по нажатию Ctrl+Shift+B они будут компилится в js файлы в каталог custom. Вместе с ними также скомпилятся еще и std скрипты в папку custom\std, но они не помешают. 
В начале своих скриптов пишем

    //engine: JScript
    //uname: уникальное имя
    //addin: global
    ... другие теги ...

Подключаем SnegAPI и типы 1С, файлы должны лежать в этом же каталоге:

    ...
    /// <reference path="./snegopat" />
    /// <reference path="./v8" />
    ...

Подключаем глобальные контексты 1С

    ...
    global.connectGlobals(SelfScript);
    ...

Подключаем нужные стандартные скрипты

    ...
    import * as stdlib from "./std/std";
    import * as stdcommands from "./std/commands";
    import * as hks from "./std/hotkeys";
    ...

и т.п., смотря какие скрипты нужны. В кавычках путь обязательно должен начинаться с точки, быть относительным каталога, где лежит скрипт, расширение ts не указываем. Также можно импортом подключать и другие свои скрипты, написанные на TypeScript. В таких скриптах обязательно что-то должно быть export, смотрите примеры в стандартных скриптах.

По самому TypeScript. Переменные типизируются или сами при объявлении присваиванием, если тип выводится из выражения, либо можно через двоеточие указать явно. Самый общий тип - any. Иногда TypeScript ругается на несовпадение типов - тогда приводите явно: <ИмяТипа> Смотрите примеры, читайте интернеты. Успехов!

По отладке скриптов - смотрите тему https://snegopat.ru/forum/viewtopic.php?f=7&t=419&start=10#p7192 Вкратце - необходимо установить один или несколько из перечисленных скриптовых отладчиков, в тексте скрипта в месте, где хочется подключить отладчик, написать debugger - и при выполнении этой строки всплывёт отладчик. Дальше в нём уже можно выполнять пошагово, ставить точки останова, просматривать переменные и т.д. и т.п.

**Comment by awa15** [comment]
> @awa15 Возможно ли в твоей базе получить данные по разделу справки, к которому относится то или иное свойство? Вижу ссылку на раздел справки, например, v8help://SyntaxHelperContext/objects/Global context/methods/catalog4839/Exp1003.html

> Как бы узнать, что это именно Глобальный контекст - Функции работы со значениями типа Число ?
В базе никак не сохраняются разделы справки, надобности в этом не было. А какая разница, относится функция глобального контекста к строковым или это функция форматирования?

**Comment by nixel2007** [comment]
@awa15 просто, чтобы визуально разделять регулярки на блоки при формировании грамматики. Хотя в целом можно и захардкодить, что справочник # 1 - это строковые функции.
