### ISSUE TITLE
[ST] Некорректно подсвечивает комментарий, если это последняя строка файла

### ISSUE THREAD

**Issue by kuntashov** [xDrivenDevelopment/1c-syntax#56]
Последний комментарий в файле, если это последняя строка, не подсвечивается как комментарий, а должен. 

Скриншот: https://yadi.sk/i/pwzfkTAlmdHUj

Если добавить еще одну строку (даже просто перевод строки), то комментарий подстветка комментария станет правильной.

**Comment by nixel2007** [comment]
Принято. Проблема в наличии символа переноса строки в регулярке.
