### ISSUE TITLE
[VSC] Список процедур и функций

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#59]
Для vsc, в отличии от Atom и ST, пока нет поддержки списка процедур текущего файла и/или проекта.
В продолжение #43

**Comment by bambr1975** [comment]
https://yadi.sk/i/osBCTfvgn5Gtz Может, подойдет

**Comment by nixel2007** [comment]
Список функций текущего файла реализован (спасибо @bambr1975 !).
Список функций текущего каталога еще не реализован.

**Comment by ebugusey** [comment]
У меня есть идея как выполнить эту задачу. Могу взяться.

**Comment by pumbaEO** [comment]
Уже реализовано, с показом обратных вызовов.

**Comment by nixel2007** [comment]
@ebugusey да, реализовано, но пока не в релизе

**Comment by nixel2007** [comment]
@pumbaEO Жень, по-моему я поторопился. Я не могу найти в твоей реализации workspaceSymbolProvider, отвечающий за список процедур в проекте.
Пропустил, или оно все же не реализовано?

**Comment by nixel2007** [comment]
Реализовано в ветке tsport
