### ISSUE TITLE
Английские ключевые слова

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#6]
На данный момент в грамматике только русские варианты операторов.
Необходимо добавить перевод.

**Comment by vsuh** [comment]
не подсвечивается `exception`
![image](https://cloud.githubusercontent.com/assets/12156293/11895184/83ea8c5e-a58d-11e5-8daf-7f3b778470d5.png)

**Comment by nixel2007** [comment]
Оно разве не except?

**Comment by EvilBeaver** [comment]
Except. А вообще, @vsuh все английские конструкции в стандартном 1С-овском синтакс-помощнике переведены, можно туда подсматривать.

**Comment by vsuh** [comment]
прикольно! `except` покрасилось, но `exception` синтаксических шибок не показало, и отрабатывает правильно )))

**Comment by vsuh** [comment]
АА! нет `exception`
`except` :

    running command> oscript.exe -encoding=utf-8 e:\_git_\ctrPhones\text.bsl
    {Модуль e:\_git_\ctrPhones\text.bsl / Ошибка в строке: 4 / Неизвестная операция}

**Comment by EvilBeaver** [comment]
@nixel2007 ну это, получается, баг в 1Script. В 1С правильно Except, а 1Script хочет Exception.

**Comment by nixel2007** [comment]
@evilbeaver я с СП списывал :) 
Поправишь у себя?

**Comment by vsuh** [comment]
@EvilBeaver   #$@#$%!!!
с`эст не очень комильфо
Андрей, надо, наверное, два варианта оставить, `except` и `exception`, разуж так получилось.
Представляете, 100500 людей вам ночью позвонят и спросят почему перестал работать скрипт.

**Comment by nixel2007** [comment]
При выходе 1.0.11 была описана смена поведения подключения библиотек по пути. В рамках выхода 1.0.12 это можно так же описать. И нет проблем.

**Comment by EvilBeaver** [comment]
Да уж получается что так :) Два варианта проживут пока бета.

-----Исходное сообщение-----
От: "vsuh" <notifications@github.com>
Отправлено: ‎19.‎12.‎2015 14:41
Кому: "xDrivenDevelopment/1c-syntax" <1c-syntax@noreply.github.com>
Копия: "Andrei Ovsiankin" <ovsiankin.aa@gmail.com>
Тема: Re: [1c-syntax] Английские ключевые слова (#6)

@EvilBeaver #$@#$%!!!
сэст не очень комильфо
Андрей, надо, наверное, два варианта оставить,exceptиexception`, разуж так получилось.
Представляете, 100500 людей вам ночью позвонят и спросят почему перестал работать скрипт.
