### ISSUE TITLE
Запуск скриптов в Sublime 3

### ISSUE THREAD

**Issue by JohnyDeath** [xDrivenDevelopment/1c-syntax#65]
У меня не получается запустить скрипты в ST 3
![image](https://cloud.githubusercontent.com/assets/5936030/12257345/dd254470-b916-11e5-9356-3a6452dedc8f.png)
Если в скрипте написать все что угодно, то ошибки не вывалит. Скорее всего oscript-у не передается файл в качестве параметра.
"Make" также создает пустой экзешник.

**Comment by nixel2007** [comment]
Хм. У меня все в порядке. И run и make
![default](https://cloud.githubusercontent.com/assets/1132840/12257572/ed341cd6-b918-11e5-957e-4e231ea25aac.PNG)

Сравним порядок действий:
* открыл ST
* выбрал грамматику 1C (BSL)
* создал новый файл
* написал туда Сообщить();
* сохранил как UTF-8 With BOM с расширением os.

Нажал ctrl-B (или ctrl-shift-b)

**Comment by JohnyDeath** [comment]
Сделал по твоей инструкции новый проект и там прописал пути жестко
```
{
	 "build_systems":
    [
        {
            "cmd":
            [
                "D:\\Progs\\OneScript\\bin\\oscript.exe",
                "-encoding=utf-8",
                "D:\\tmp\\message.os",
                "Аргумент1",
                "Аргумент2"
            ],
            "file_regex": "^ *\\{Модуль (.+) / Ошибка в строке: ([0-9]+) / ()(.*)$",
            "name": "1C (BSL) Run with args",
            "selector": "source.bsl",
            "working_dir": "${project_path:${folder}}"
        }
    ]
}
```
результат не поменялся

**Comment by nixel2007** [comment]
Хм. Версия ST?

**Comment by JohnyDeath** [comment]
build 3083

Сам oscript запускается, потому что если намеренно допустить ошибку в имени экзешника, то получаем:
>[WinError 2] Не удается найти указанный файл
[cmd: ['D:\\Progs\\OneScript\\bin\\oscript.exe_', 'd:\\tmp\\message.os']]
[dir: D:\tmp]
[path:

Но что именно на самом деле передается в oscript - не знаю, потому что если указать параметром несуществующий файл, то в окне результата появляется тоже сообщение, хотя должна вывалиться ошибка oscript

**Comment by JohnyDeath** [comment]
Если в свойствах ставлю так (вообще не передаю параметры):
```
"cmd":
            [                
                "D:\\Progs\\OneScript\\bin\\oscript.exe"
            ],
```
то вижу стандартный вывод сообщения от oscript, если его запускать без параметров.
Получается, что ему, когда стоят параметры, что-то передается.

**Comment by nixel2007** [comment]
Версия oscript?

**Comment by nixel2007** [comment]
D

**Comment by JohnyDeath** [comment]
1.0.11.53

**Comment by JohnyDeath** [comment]
Новый эксперимент.
Создал батник mesbat.bat с текстом
```
echo "HI"
oscript d:\tmp\message.os
```
В настройках прописал:
```
{
	 "build_systems":
    [
        {
            "cmd":
            [                
                "d:\\tmp\\mesbat.bat"
            ],
            "file_regex": "^ *\\{Модуль (.+) / Ошибка в строке: ([0-9]+) / ()(.*)$",
            "name": "1C (BSL) Run with args",
            "selector": "source.bsl",
            "working_dir": "${project_path:${folder}}"
        }
    ]
}
```
Выполняю
![image](https://cloud.githubusercontent.com/assets/5936030/12258629/1aa7de20-b921-11e5-8bfd-c6948b18fe39.png)

**Comment by JohnyDeath** [comment]
Оказывается все дело было в кодировке!
Первоначально файл сохранился БЕЗ BOM. Преобразовал в "UTF-8 With BOM" и все заработало.
Только вот почему ошибки от oscript не транслируются в консоль?

**Comment by nixel2007** [comment]
Вот оно. 1.0.11 при сохранении без BOM не выдает вообще ничего.
1.0.12 при сохранении без BOM выдает
```
{Модуль C:\Users\na_gryzlov\Desktop\test.os / Ошибка в строке: 1 / Неизвестный символ ±}
```

Видимо, @EvilBeaver что-то поменял с выводом ошибок в последней версии.

**Comment by JohnyDeath** [comment]
Точно! Поставил 1.0.12 и там инфа об ошибках в табло попадает!
Андрей, признавайся, что поменял?

**Comment by JohnyDeath** [comment]
Хотя не все ошибки доходят до ST. Например, если в настройки поставить:
```
"cmd":
            [                
                "D:\\Progs\\OneScript\\bin\\oscript.exe",
                "-encoding=utf-8",
                "все что угодно"
            ],
```
То в табло - пусто.
@EvilBeaver , можешь пояснить? Там по разному как-то поток выдается?

**Comment by JohnyDeath** [comment]
Что-то подобное припоминаю, когда писал скрипты на PowerShell. Там есть два метода: Write-Output (echo) и Write-Host . Нужно было использовать второй.

**Comment by EvilBeaver** [comment]
@JohnyDeath там два вида ошибок. Первый - когда до выполнения скрипта дело еще не дошло, второй, когда скрипт отдан на исполнение. До версии 12 первый вид ошибок игнорировал ключ ```-encoding``` и выводил ошибку в default кодировке. В 12 версии я поправил то, что теперь все ошибки  учитывают ключ ```-encoding```. Но на этом вроде бы все. Других правок не было. Пока не  понял, почему поведение разное между 11 и 12.

**Comment by JohnyDeath** [comment]
И первый вид ошибок не пробрасывается в редактор.
Не только у меня такое?

**Comment by EvilBeaver** [comment]
Они оба должны были пробрасываться. Понятно, что дело в потоках, я подумаю. Сейчас на v12 все устраивает?

**Comment by JohnyDeath** [comment]
Нет, первый вид ошибок на v12 так и не пробрасываются.
Починился только второй вид ошибок.
На битбакете задачу завести?

**Comment by EvilBeaver** [comment]
Заведи

**Comment by nixel2007** [comment]
@JohnyDeath я правильно понимаю, что текущую задачу можно закрывать?

**Comment by EvilBeaver** [comment]
Хз, подожди пока

**Comment by JohnyDeath** [comment]
Сделал: https://bitbucket.org/EvilBeaver/1script/issues/213/

**Comment by EvilBeaver** [comment]
@JohnyDeath забавная штука... ощущение, как будто sublime не читает выходной поток процесса oscript в каких-то случаях

**Comment by nixel2007** [comment]
/troll_mode on
Мысли ST:
Упал процесс? 
http://troll-face.ru/static/mememaker/6/e/3002-da-i-huj-s-nim.jpg

/troll_mode off

**Comment by EvilBeaver** [comment]
@nixel2007 не, он не падает просто так. Там на самом верху стоит try/catch и честно возвращается из main числовой код ошибки.

**Comment by nixel2007** [comment]
@EvilBeaver понимаю, что крайне маловероятно, но может он часть номеров ошибок игнорирует?

**Comment by EvilBeaver** [comment]
Процесс oscript возвращает 0, запуск в cmd показывает весь выхлоп. Sublime не показывает ничего. Сдается мне, это глюки sublime

**Comment by EvilBeaver** [comment]
Блин, я что-то запутался... Методом тыка правлю вывод в 1Script добавил диагностические сообщения перед запуском скрипта, после него, в глоб. выводе ошибки, перед выходом из процесса. Получаю следующее:

![image](https://cloud.githubusercontent.com/assets/2657561/12298004/f692fdf2-ba20-11e5-9982-8fa8c0ca889d.png)

Ситуация:

* В sublime выключен ключ -encoding и все, что выдает скрипт пишется так же, как и ошибки - через ```Console.WriteLine()``` - в системной кодировке.
* В sublime специально указан несуществующий файл скрипта, что выдает ошибку "Файл не найден".

Итак, красной рамкой выдано то, что я добавил перед началом запуска скрипта и перед выбросом исключения **Файл не найден**.

Зеленой рамкой выводится проблемный текст. Если было исключение, то стандартный Console.WriteLine уже sublime не увидит. Он будет видеть, только если напрямую в поток вывода stdout записать байты в кодировке UTF-8 (что и проделано на рисунке)

    using (var stdout = Console.OpenStandardOutput())
                {

                    var enc = Encoding.UTF8;
                    var bytes = enc.GetBytes(e.ToString());
                    stdout.Write(bytes, 0, bytes.Length);
                    stdout.WriteByte(0xA);
                    stdout.WriteByte(0xD);
                }

далее, желтой рамкой выведено сообщение которое написано перед самым выходом из процесса oscript. Это сообщение также выводится простым ```Console.WriteLine()```

Если я в обработчике исключения сделаю тоже ```Console.WriteLine()```, то и зеленая и желтая рамка выведены не будут. А красная - будет. Т.е. кодировка, в которой sublime читает выхлоп процесса зависит каким-то образом от того, было ли исключение внутри процесса. Хотя это исключение процессом успешно поймано и обработано.

Подозрительно похоже на trollface от @nixel2007 (процесс упал, а исключение не поймалось), но почему тогда в cmd тот же код работает - первое, и второе - если писать байты в stdout напрямую - то тоже работает.

@nixel2007 есть идеи?

**Comment by EvilBeaver** [comment]
Тот же EXE запущенный в Notepad++:

![image](https://cloud.githubusercontent.com/assets/2657561/12298362/b9ba8b50-ba22-11e5-857b-e05022ce27f8.png)

**Comment by nixel2007** [comment]
@EvilBeaver в стандартную консоль ST, случаем, ничего полезного не выводится?
`ctrl-~`

**Comment by nixel2007** [comment]
@EvilBeaver Знаешь, вообще чудеса какие-то.

Если я стоит флаг -encoding, то хеллоуворлд выводится. убираю - не выводится.

**Comment by nixel2007** [comment]
Есть подозрения, что в какой-то момент ST, как приложению, работающему в юникоде, становится плевать на весь неюникодный вывод.

**Comment by EvilBeaver** [comment]
Я кажется понял. Ты был похоже пока насчет падения. Только падает не процесс, а фоновый thread внутри sublime, который читает вывод процесса

**Comment by JohnyDeath** [comment]
А почему тогда у @nixel2007 на 1.0.12.28 все выводится? @EvilBeaver , ты внутри на этой версии что-то менял?

**Comment by EvilBeaver** [comment]
По моим наблюдениями выводится ровно до тех пор, пока не будет выведен русский символ. Ничего в этой версии не менял.

**Comment by nixel2007** [comment]
выводил "Пинг"

**Comment by nixel2007** [comment]
с включенным выводится, без включенного - не выводится.

**Comment by EvilBeaver** [comment]
Ну вот и я про то же. С включенным принудительно идет Юникод и все хорошо. А без него - кириллица роняет поток чтения внутри sublime. Как мне кажется. В люом случае, это надо починить. Ключ -encoding он как раз для таких случаев делался, когда приложение хочет особую кодировку. Но сейчас он влияет только на то, что сам скрипт выводит, а все, что до выполнения скрипта - ключ encoding игнорирует. @JohnyDeath задачу мне завел.

**Comment by nixel2007** [comment]
Если подытожить:
* это проблема oscript
* ST падает, потому что это для него - unexpected behavior
* задачку тебе повесили, когда-нибудь ты до нее доберешься.

В рамках 1.0.12 и флага encoding (а он по умолчанию есть) эта проблема вылезает только при каких-то системных ошибках - не найден/нет доступа к файлу, Луна в Юпитере; и в общем случае не мешает?

**Comment by JohnyDeath** [comment]
В общем - да.
Закрываем. Всем спасибо.

**Comment by EvilBeaver** [comment]
В oscript однозначно правим, т.к. ключ encoding работает не везде. Но и в саблайме проблема тоже есть. UB это кракозяблы, их все знают. Если бы он не падал, а вывел их, мы бы сразу разобрались и не дискутировали бы тут три дня.

**Comment by JohnyDeath** [comment]
Может кто-нибудь оформить баг в ST? Мой английский из вери бэд для таких сложных описаний.

**Comment by nixel2007** [comment]
Надо еще на дев-билде ST проверить, Может поправили уже.

**Comment by nixel2007** [comment]
На дев-билде поведение такое же.
@EvilBeaver Сможешь написать авторам ST по существу? Как я понял, ты локализовал место проблемы.
