### ISSUE TITLE
Подсветка синтаксиса языка запросов

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#66]
Стоит ли добавлять подсветку текста запроса?

Связанные проблемы - текст запроса внутри строки, ошибочное срабатывание.

**Comment by EvilBeaver** [comment]
Имхо, не нужно. Ну или с очень низким приоритетом

**Comment by nixel2007** [comment]
В рамках спиноффа начал потихонечку пилить.
https://github.com/nixel2007/1c-query-syntax

Как будет что-то более-менее приличное, можно попробовать слить с 1c-syntax

**Comment by nixel2007** [comment]
Первая версия:

Monokai:
![monokai](https://cloud.githubusercontent.com/assets/1132840/12895426/64219900-cead-11e5-9743-a62b56926418.PNG)

Atom dark:
![atom dark](https://cloud.githubusercontent.com/assets/1132840/12895431/6838ed2c-cead-11e5-814a-8ac30418e348.PNG)

**Comment by kuntashov** [comment]
Для завершенности надо и 1Совскую цветовую схему сделать, что нам эти монокаи, даешь ключевые слова красным! :)

**Comment by nixel2007** [comment]
@kuntashov ты наверное удивишься, но в тексте запроса ключевые слова синие...)

**Comment by kuntashov** [comment]
Я имел в виду для языка, но да, извини, в этой задаче мой предыдущий коммент скорее оффтопик :)

**Comment by nixel2007** [comment]
@kuntashov и в монокаи ключевые слова как раз красные :D

**Comment by nixel2007** [comment]
А, в этом плане) там в соседней ишу было обсуждение) решили отложить до того, как кто-нибудь не попросит и сам не сделает :D
