### ISSUE TITLE
ST: Автовставка символа | в строке и автокомплит внутри строк

### ISSUE THREAD

**Issue by EvilBeaver** [xDrivenDevelopment/1c-syntax#67]
Есть две хорошие фичи:

1. Автоматическая вставка символа | при редактировании строки и нажатии Enter
2. Автокомплит текста внутри строковых литералов

Если эти две фичи сложить, получается следующее:

* Открываю кавычку, пишу текст
* Одно из слов есть в словаре, открывается всплывающая подсказка
* Я, радостный, нажимаю Enter, чтобы слово вставилось в текст
* Слово исчезает, курсор переходит на следующую строку, подстанавливается символ |
* Воспользоваться подстановкой с клавиатуры не удается (но можно кликнуть мышкой в окошко autocomplete)

В моем случае, я бы удовлетворился возможностью отключения автовставки символа |. В идеале - не выполнять это поведение, если открыто окно автокомплита.

**Comment by nixel2007** [comment]
@bambr1975

**Comment by nixel2007** [comment]
Я бы даже сказал, что это баг :) надо поколдовать

**Comment by bambr1975** [comment]
Надо добавить строку
```
 { "key": "auto_complete_visible", "operator": "equal", "operand": false }
```

**Comment by nixel2007** [comment]
В https://github.com/xDrivenDevelopment/sublime-language-1c-bsl/blob/master/Default.sublime-keymap, правильно понимаю?

**Comment by bambr1975** [comment]
да, в 17-й строке надо поставить запятую, а следующей строкой вставить

**Comment by nixel2007** [comment]
Исправлено в баг-фикс релизе 1.1.2 для ST.
@EvilBeaver

**Comment by nixel2007** [comment]
@bambr1975 спасибо!
