### ISSUE TITLE
Не работает автодополнение в VSC

### ISSUE THREAD

**Issue by vsuh** [xDrivenDevelopment/1c-syntax#69]
1c-syntax ver. 1.1.0
![image](https://cloud.githubusercontent.com/assets/12156293/12318604/86c8b69c-baac-11e5-8a80-e2b417e14b59.png)
после нажатия `Enter` `Shift-Enter` `Ctrl-Enter`
![image](https://cloud.githubusercontent.com/assets/12156293/12318622/b13bb2ee-baac-11e5-9907-c34f8f0fadeb.png)

**Comment by nixel2007** [comment]
Охохох, повылезало.
https://github.com/xDrivenDevelopment/1c-syntax/issues/67

@bambr1975 FYI.

**Comment by bambr1975** [comment]
ага, вижу. Уже смотрю

**Comment by nixel2007** [comment]
Если что, в Атоме вроде все корректно.

**Comment by bambr1975** [comment]
Уф. Все просто тоже
```
"when" : "editorTextFocus && !suggestWidgetVisible && editorLangId == 'bsl'"
```

**Comment by nixel2007** [comment]
Вошло в 1.1.2 для VSC.
@bambr1975 @vsuh спасибо!
