### ISSUE TITLE
Добавить поддержку многострочных строк

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#7]
```
"Которые с кавычками
|и переносами строк"
```

**Comment by bambr1975** [comment]
Вроде у Андрея в https://github.com/EvilBeaver/bsl-textmate-package/blob/master/v8ent-syntax-YAML-tmLanguage это уже было:
- comment: string literal
  name: constant.character.bsl
  begin: \"
  end: \"
  patterns:
  - match: \"\"
  - name: constant.character.escape.bsl

**Comment by nixel2007** [comment]
Да, я видел этот кусок. Хотел его отдельно протестить на предмет работы с конкатенацией и двумя двойными кавычками

**Comment by nixel2007** [comment]
Хотя версия @EvilBeaver похожа на 
```
- name: string.quoted.double.1с
  match: ("[^"]*")
```
только не в одну строку.
Хотелось бы разделить `string.quoted.double` и `string.interpolated.1с`. Видимо, надо как-то анализировать символ `|`

**Comment by bambr1975** [comment]
ты их местами в этом файле поменяй)))

**Comment by nixel2007** [comment]
Перепроверил в атоме - не переопределяет. Порядок оказался верным :)
