### ISSUE TITLE
Не работает подсветка синтаксиса в VSC

### ISSUE THREAD

**Issue by vsuh** [xDrivenDevelopment/1c-syntax#70]
Чтож я такой невезучий то...
![image](https://cloud.githubusercontent.com/assets/12156293/12324121/912c1ad2-bad1-11e5-93ec-e70a8b658240.png)
вначале файла все вроде правильно, потом:
![image](https://cloud.githubusercontent.com/assets/12156293/12324088/5f8e315e-bad1-11e5-8b21-622e38944025.png)

**Comment by nixel2007** [comment]
Это все то же - https://github.com/xDrivenDevelopment/1c-syntax/issues/37
