### ISSUE TITLE
Определение строк в одинарных кавычках

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#71]

**Comment by bambr1975** [comment]
Хочешь разделить
```
 - name: constant.other.date.bsl
match: \'.+\'
```
на даты и строки?

**Comment by nixel2007** [comment]
Если синтаксис позволяет писать 'строки' вне "строк с двойными кавычками" (как в НСтр()), то да (до твоего вопроса я об этом вообще не подумал).
По идее, дата - это только `'\d{6}|\d{12}'`, все остальное - string.single.quoted или как оно там назвается.

**Comment by nixel2007** [comment]
Оказалось, что 1с все 'строки', неподходящие под формат даты, ругает вот таким сообщением:  
```
{ВнешняяОбработка.ВнешняяОбработка1.МодульОбъекта(2,16)}: Неправильная константа типа Дата
ДругаяСтрока = <<?>>'фывыфв'; (Проверка: Сервер)
```

Поэтому не стал ничего мудрить со строками в одинарных кавычках (это вообще illegal получается :) ) и просто подправил определение дат.
