### ISSUE TITLE
Падение производительности в функции addPipe

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#73]
Если внутри строкового литерала сделать большое количество переносов строк (в моем случае 10), то добавление каждого нового переноса происходит все дольше и дольше - от 5 секунд и выше (с прогрессией).

/cc @bambr1975

**Comment by bambr1975** [comment]
Поменяй регулярку на 
```var Regex = /(\/\/.*$)|(\/\/.*\r?\n)|("[^"]*$)|("(""|[^"]*)*")|([^"\/]+)/g;``` 
и 
```stringmatsh = ArrStrings[3]; ```
соответственно

**Comment by nixel2007** [comment]
Помогло, спасибо!

**Comment by nixel2007** [comment]
@bambr1975 а нам разве нужен кусок регулярки `("[^"]*$)`? с учетом того, что [убрал это определение](https://github.com/xDrivenDevelopment/1c-syntax/commit/ca7fe09aff343c620c30aba3259e1e55dbc6d33a) из грамматики?

**Comment by bambr1975** [comment]
))) именно этот кусок нам и нужен)))) - в нем незакрытая кавычка

**Comment by nixel2007** [comment]
ох, точно)
в очередной раз убеждаюсь, что регулярку проще написать, чем понять :D
