### ISSUE TITLE
Atom: не выполняется скрипт, если открыт как единственный файл

### ISSUE THREAD

**Issue by JohnyDeath** [xDrivenDevelopment/1c-syntax#74]
Если открываю файл скрипта из проводника или открываю из Атома в режиме "Открыть файл",
Тогда выполнение скрипта через пакет Script не происходит и выдается сообщение:
```
Unable to run

oscript
Did you start Atom from the command line?

  atom .
...
```

Если же открыть через меню Атома КАТАЛОГ, где расположен файл
Тогда скрипт запускается корректно

ИЛИ Если в конфигурации запускалки скриптов (ctrl+shift+alt+o) указать явно путь к каталогу скрипта
Тогда скрипт запускается корректно

**Comment by nixel2007** [comment]
@JohnyDeath кстати, пакетом build не пробовал?

**Comment by JohnyDeath** [comment]
Пока нет, но это по-моему плюшка самого Атома

**Comment by nixel2007** [comment]
@JohnyDeath я как-то через слово прочитал твою багу.
Да, у атома есть какие-то проблемы с получением переменных окружения при открытии без каталога. выход - либо open folder, либо через консоль `atom .`

**Comment by nixel2007** [comment]
мало того, это описано в readme ;) https://github.com/rgbkrk/atom-script#atom-cant-find-node--ruby--python--my-socks

**Comment by JohnyDeath** [comment]
Точно, в ридми и читал, но давно было

**Comment by nixel2007** [comment]
Закрываем?

**Comment by JohnyDeath** [comment]
Вообще конечно странная фишка редактора. Какие там могут быть проблемы - не понимаю.

**Comment by nixel2007** [comment]
Это может быть фишка пакета atom-script.
Потому и просил проверить на build :)

**Comment by artbear** [comment]
А почему закрыли? проблема-то есть!

**Comment by nixel2007** [comment]
ммм... тогда вот так.

**Comment by JohnyDeath** [comment]
@artbear  так проблема ж явно не в пакете подсветки синтаксиса.

**Comment by artbear** [comment]
Так мы в текущем репо уже давно решаем не только проблемы подсветки
синтаксиса :)

пт, 22 янв. 2016 г. в 15:54, Evgeny Martynenkov <notifications@github.com>:

**Comment by nixel2007** [comment]
@JohnyDeath @artbear поэтому пометил как wontfix. типа это не наша проблема :)

**Comment by nixel2007** [comment]
Смог локализовать проблему.
https://github.com/rgbkrk/atom-script/issues/833

Постараюсь пофиксить в ближайшие дни.

**Comment by nixel2007** [comment]
Так это опять все из-за Атома.
`https://github.com/atom/tree-view/issues/471`

**Comment by nixel2007** [comment]
Исправлено в релизе script 3.6.0
