### ISSUE TITLE
Добавить настройку отступов по умолчанию (не заменять табы на пробелы и размер табуляции)

### ISSUE THREAD

**Issue by kuntashov** [xDrivenDevelopment/1c-syntax#75]
Предлагаю добавить в пакет настройку табуляции по умолчанию, т.к. в мире 1С все привыкли к тому, что отступы табами, а не пробелами и ширина одной табуляции = 4 пробела.

В ST для этого надо добавить в пакет файл `1c.sublime-settings` следующие настройки:

```json
{
    "tab_size": 4,
    "translate_tabs_to_spaces": false
}
```

Насчет других редакторов пока не смотрел, поэтому пока в виде issue, а не PR.

p.s. Я по наивности просто уже лопухнулся: https://bitbucket.org/EvilBeaver/1script/pull-requests/33/http/diff#comment-13746488 :)

**Comment by kuntashov** [comment]
И да, если что: https://www.sublimetext.com/docs/3/indentation.html

**Comment by nixel2007** [comment]
Принято. Постараюсь впилить в 1.1.4

**Comment by nixel2007** [comment]
Насколько я понимаю, в vsc на уровне пакета сейчас это настроить невозможно.
Два варианта 
 - user settings - http://stackoverflow.com/questions/29972396/how-to-set-tab-space-style?lq=1
 - очередное костылестроение с обработкой нажатия enter.

**Comment by nixel2007** [comment]
Для Атома и ST реализовано, войдет в 1.1.4
