### ISSUE TITLE
VSC: Задвоение процедур при просмотре списка процедур и функций

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#76]
При просмотре списка процедур происходит задваивание имен.
Возможно это такая же проблема, как вот здесь:
https://github.com/Microsoft/TypeScript/issues/6566

Выглядит, по крайней мере, так же :)

**Comment by bambr1975** [comment]
текст, на котором это воспроизводится можешь куда-нибудь скинуть?

**Comment by nixel2007** [comment]
@bambr1975 
```
procedure my_proc(param)
    f = 0;
endprocedure

my_proc(0);

```

**Comment by bambr1975** [comment]
хи-хи)))
```
procedure|function)\s+([a-zа-яё_][a-zа-яё_0-9]*)
```
Будь добр, вставь в регулярку в самое начало ^|\s, пожалуйста

**Comment by nixel2007** [comment]
@bambr1975 спасибо! немного напильником допилил и заработало :)
