### ISSUE TITLE
VSC: Теряются отступы при переносе строки

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#77]
От @EvilBeaver 

> Кстати, коллеги, может кто-то знает почему в VSC у меня вдруг стало после нажатия Enter ставить курсор в начало следующей строки (с потерей текущего отступа)?
Т.е. я пишу Если бла-бла Тогда, нажимаю Enter добавляется строка, но курсор встает в самое начало, а не на ту колонку, на которой написано Если?

/cc @bambr1975

**Comment by nixel2007** [comment]
Подтверждаю, что это проблема пакета. Если сменить текущий scope на что-то другое, то перевод строки работает корректно.

**Comment by bambr1975** [comment]
Очередной костыль:
```
var editor = vscode.window.activeTextEditor;
if (editor != undefined) {
	var position = editor.selection.active;
	var textline = editor.document.getText(new vscode.Range(new vscode.Position(0, 0), position));
	var Regex = /(\/\/.*$)|(\/\/.*\r?\n)|("(""|[^"]*)*")|("[^"]*$)|([^"\/]+)/g;
	while ((ArrStrings = Regex.exec(textline)) != null) {
		var stringmatsh = ArrStrings[5];
	}
	var textLineAt = editor.document.lineAt(position.line).text;
	var RegexSpace = /(\s|\t)*.*$/;
	var IndentText = "";
	if (ArrSpace = RegexSpace.exec(textLineAt)) {
		IndentText = ArrSpace[1];
	};
	if (stringmatsh != undefined) {
		editor.edit(function (editBuilder) {
			editBuilder.insert(new vscode.Position(position.line, position.character), '\n' + IndentText + '|');
		});
	} else {
		editor.edit(function (editBuilder) {
			editBuilder.insert(new vscode.Position(position.line, position.character), '\n' + IndentText);
		});
	}
}
```

**Comment by bambr1975** [comment]
еще несколько правок

**Comment by JohnyDeath** [comment]
А это всё ради того, чтобы ставилась прямая черта в многострочных строках?

**Comment by nixel2007** [comment]
Да. 

Отправлено с моего HTC

----- Ответное сообщение -----
От: "Evgeny Martynenkov" <notifications@github.com>
Кому: "xDrivenDevelopment/1c-syntax" <1c-syntax@noreply.github.com>
Копия: "Nikita Gryzlov" <nixel2007@gmail.com>
Тема: [1c-syntax] VSC: Теряются отступы при переносе строки (#77)
Дата: пт, янв. 22, 2016 22:19

А это всё ради того, чтобы ставилась прямая черта в многострочных строках?

&mdash;

**Comment by bambr1975** [comment]
вообще у vs code есть специальное API для того, чтобы обрабатывать нажатие Enter в зависимости от соответствия строки регулярке (пример здесь - https://github.com/garethflowers/vscode-portable/blob/4bfd8b7094faccc2536bee5211a676127c6c721b/VSCodePortable/App/VSCode/resources/app/extensions/typescript/out/typescriptMain.js#L67), но от моих регулярок оно или зависает, или не срабатывает (мне кажется, что это проблема самого vs code, при работе вышеприведенного скрипта с теми же регулярками все работает нормально)

**Comment by bambr1975** [comment]
ой-ё. Мне очень-очень стыдно за свое "костылеписательство"(((
Прошу рассмотреть вариант вставки "|" через нормальное API vs code)))) (удалось найти регулярки, которые не зависают и срабатывают):
```
function activate(context) {
    vscode.languages.setLanguageConfiguration("bsl", {
        onEnterRules: [
            {
                beforeText: /^\s*\|[^\"]*$/,
                action: { indentAction: vscode.IndentAction.None, appendText: '|' }
            },
            {
                beforeText: /^([^\|\"]|"[^\"]*")*\"[^\"]*$/,
                action: { indentAction: vscode.IndentAction.None, appendText: '|' }
            }

        ]
    });
```
Это нужно вставить вместо context.subscriptions.push(vscode.commands.registerCommand('extension.addpipe', bslCommands.addPipe));
