### ISSUE TITLE
VSC: Настройка отступов по умолчанию (табы, 4 сивола)

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#79]
В продолжение https://github.com/xDrivenDevelopment/1c-syntax/issues/75

Насколько я понимаю, в vsc на уровне пакета сейчас это настроить невозможно.
Два варианта:
 - user settings - http://stackoverflow.com/questions/29972396/how-to-set-tab-space-style?lq=1
 - очередное костылестроение с обработкой нажатия enter.

**Comment by bambr1975** [comment]
можно сделать по аналогии с 
https://github.com/kasik96/VSCode-PHP-Format/blob/3f8a9076904c3b808557d80543c30c7944794355/extension.js

**Comment by nixel2007** [comment]
> А в качестве костылестроения ты имеешь в виду обработку нажатия tab?

Да, оговорился. 

> А вообще сами установки реализовываются просто. Нужно просто добавить в extention строки:

И проблема с этим методом описана - мы переопределим настройки всего редактора :) а надо-то только для source.bsl

Вот и получается, что либо ждать, либо обрабатывать таб. 

p.s. Сырой vsc, сырой...

**Comment by bambr1975** [comment]
Тем не менее - все решается вот так:
```
context.subscriptions.push(vscode.window.onDidChangeActiveTextEditor(function (textEditor) {
    var newOptions = {
      "insertSpaces" : false,
      "tabSize" : 4
    };
    var defaultOptions = {};
    defaultOptions.tabSize = vscode.workspace.getConfiguration("editor").get("tabSize");
    defaultOptions.insertSpaces = vscode.workspace.getConfiguration("editor").get("insertSpaces");
    if (textEditor.document.languageId == "bsl") {
      textEditor.options = newOptions;
    } else {
      textEditor.options = defaultOptions
    }
  }));
```

**Comment by nixel2007** [comment]
Ммм... я правильно понимаю, что табсайз вот здесь `vscode.workspace.getConfiguration("editor").get("tabSize")` и вот здесь `textEditor.options` хранится в разных местах?

Первое - с конфиг файла, а второе с каких-то пользовательских настроек текущего сеанса?

**Comment by bambr1975** [comment]
да

**Comment by nixel2007** [comment]
Как этот вариант работает с пользовательскими настройками через user config? допустим, там пользователь определил, что с source.bsl он хочет работать через двойные пробелы.

Что произойдет при перетыкивании вкладок?

**Comment by bambr1975** [comment]
все нормально - для не"bsl"-файлов подхватит именно пользовательские настройки

**Comment by bambr1975** [comment]
user config разве позволяет определять отступы для конкретных языков?

**Comment by nixel2007** [comment]
А для bsl? :)

**Comment by bambr1975** [comment]
ты имеешь в виду editorconfig?

**Comment by nixel2007** [comment]
Если ничего не путаю, то да, позволяет.

**Comment by nixel2007** [comment]
Затрудняюсь тебе сказать, нет vsc под рукой.

**Comment by bambr1975** [comment]
если ты все-таки имеешь в виду настройки editorconfig, то (поскольку он срабатывает раньше - у него обработчик события другой) можно просто проверять - если при переключении на вкладку настройки не совпадают ни с пользовательскими, ни с нашими  - наши не устанавливать.

**Comment by nixel2007** [comment]
@bambr1975 да, такой вариант, думаю, подойдет.

**Comment by bambr1975** [comment]
Тогда, наверное, должно быть так:
```
  context.subscriptions.push(vscode.window.onDidChangeActiveTextEditor(function (textEditor) {
    applyConfigToTextEditor(textEditor);
  }));
  applyConfigToTextEditor(vscode.window.activeTextEditor);
}
exports.activate = activate;

function applyConfigToTextEditor(textEditor) {
  var newOptions = {
    "insertSpaces" : false,
    "tabSize" : 4
  };
  var defaultOptions = {
    "insertSpaces" : vscode.workspace.getConfiguration("editor").get("insertSpaces"),
    "tabSize" : vscode.workspace.getConfiguration("editor").get("tabSize")
  };
  if (textEditor.document.languageId == "bsl") {

    if (textEditor.options == defaultOptions) {
      textEditor.options = newOptions;
    }
  } else {
    if (textEditor.options == newOptions) {
      textEditor.options = defaultOptions
    }
  }
}
```

**Comment by nixel2007** [comment]
@bambr1975 
Добавил настройку в скрипт.
Судя по содержанию переменных defaultOptions и textEditor.options, значения ключей в объектах одинаковые.
Однако же условие ` if (textEditor.options == defaultOptions)` возвращает ложь.
![default](https://cloud.githubusercontent.com/assets/1132840/12677417/f5820f76-c6a9-11e5-9d01-5961f345b1ef.PNG)

надо по ключам сравнивать? может есть какой-нибудь equal?

**Comment by bambr1975** [comment]
а где видно, что оно возвращает ложь? У меня такое сравнение работало корректно, честно.

**Comment by bambr1975** [comment]
По ключам у меня сравнивается в случае, если tabsize установлено, как auto

**Comment by nixel2007** [comment]
код не заходит внутрь и Evalute возвращает False

**Comment by nixel2007** [comment]
а вот по ключам вручную сравнило нормально. ща переделаю
