### ISSUE TITLE
Билдер из YAML-tmLanguage. Инфраструктура

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#8]
Я сейчас использую пакет https://github.com/SublimeText/AAAPackageDev для SublimeText, который по Ctrl+B из файла YAML-tmLanguage делает tmLanguage.

Появляется человеческий фактор - забыл сделать билд, отредактировал через сайт только один файл и все такое прочее.
Надо подумать над инфраструктурой репозитариев, созданием пакетов для разных редакторов.

**Comment by nixel2007** [comment]
Какая идея была изначально: 
xDrivenDevelopment/1c-syntax - это основной репозитарий с исходными кодами грамматики и неким билдером пакетов для отдельных редакторов.

Под редакторы выделяются отдельные репозитарии (пример для (Atom)[https://github.com/nixel2007/atom-language-1c]), где уже лежит корректно собранный пакет, доступный для распространения через пакетный менеджер каждого редактора:
* Sublime text - [Package Control](https://packagecontrol.io)
* Atom - раздел [Packages](https://atom.io/packages) официального сайта
* VSC - субдомен [Marketplace](https://marketplace.visualstudio.com) официального сайта

**Comment by nixel2007** [comment]
Документация по разработке пакетов:
* Sublime text - https://packagecontrol.io/docs/submitting_a_package
* Atom - https://atom.io/docs/v1.2.4/hacking-atom-package-word-count
* VSC - https://code.visualstudio.com/docs/tools/vscecli

**Comment by nixel2007** [comment]
AAAPackageDev умеет конвертить YAML в JSON.
А вот конвертер из JSON в CSON https://github.com/bevry/cson

**Comment by nixel2007** [comment]
@artbear Проверил работу https://github.com/bevry/cson - на выходе получил валидный cson, который Atom воспринял как грамматику без ошибок.
Последовательность моих действий:
* Установил npm
* Установил плагин cson `npm install -g cson`
* В Sublime text с установленным пакетом `AAAPackageDev` открыть файл '1c.YAML-tmLanguage'
* `Ctrl+Shift+B` - `Convert to ... - JSON`
* В командной строке выполнить `json2cson 1c.tmLanguage > 1c.cson`
* Полученный `1c.cson` положить в папку `grammars` пакета `atom-language-1c`

**Comment by artbear** [comment]
А без sublime text это можно сделать?в идеале хочется утилиту ком.строки
для конвертации

пт, 4 Дек 2015, 12:14, Nikita Gryzlov <notifications@github.com>:

**Comment by nixel2007** [comment]
Я дописал в то сообщение :)
> Как видно, простора для автоматизации вагон :D
Думаю, конвертер в json и в plist (оригинальный tmLanguage в виде xml) из командной строки тоже можно найти. Ну или написать на крайний случай.

Да, в идеале это утилита ком. строки. Пока не работал в этом направлении, в целом ищу инструменты.

**Comment by nixel2007** [comment]
А вот и конвертер из yaml в json - https://github.com/coolaj86/yaml2json
Таким образом, сейчас можно из консоли сконвертировать исходный `yaml` в `cson` для **Atom**.

**Comment by nixel2007** [comment]
Согласно документации http://www.sublimetext.com/docs/3/osx_command_line.html, у Sublime text есть интерфейс командной строки, из которого можно вызывать команды, объявленные в плагинах. Один из вариантов получения tmLanguage из yaml - использование этого `cli` и плагина AAAPackageDev из скрипта-билдера.

Второй вариант - поиск утилит командной строки, желательно так же на движке node.js (раз уж остальные конверторы нагуглились на node.js), например, вот этот https://www.npmjs.com/package/grunt-convert, судя по описанию, умеет конвертить из YAML в PLIST (формат tmLanguage). Необходимо проверить корректность конвертации, и если все успешно сконвертируется и в tmLanguage (формат, используемый **ST** и **VSC**) и в CSON (формат, используемый **Atom**), то у нас полный набор конвертеров на руках и можно начинать делать скрипт-билдер в 3 системы.

**Comment by nixel2007** [comment]
Скрипт для node.js и пакета `plist`, с помощью которого получилось построить валидный tmLanguage из json:
```javascript
var plist = require('plist');
var fs = require('fs');

var jsonString = fs.readFileSync('1c.json', 'utf8');
var jsonObject = JSON.parse(jsonString);
var plistString = plist.build(jsonObject);

fs.writeFileSync('1c.tmLanguage');
```

**Comment by vsuh** [comment]
А у нас есть синтаксис в json формате?

**Comment by nixel2007** [comment]
Его можно получить через `yaml2json 1c.YAML-tmLanguage > 1c.json`
Я сейчас готовлю скрипт-билдер.

@EvilBeaver В рамках оффтопа, можешь помочь? Есть бинарник в PATH (`npm` в частности). Из командной строки информацию выдает, из oscript - нет.
Запускаю вот таким образом:
```
Процесс = СоздатьПроцесс("npm -v", ТекущийКаталог(), Истина, , КодировкаТекста.UTF8);
Процесс.Запустить();
```

Ошибка:
```
{Модуль D:\git\1c-syntax\build.os / Ошибка в строке: 10 / Внешнее исключение: Не удается найти указанный файл}
```
Куда копать?

**Comment by nixel2007** [comment]
Причем если указать в качестве строки запуска `npm.cmd -v`, то получается возвращается КодВозврата = 1, ПотокВывода пуст.

**Comment by nixel2007** [comment]
Добавлен файл `build.os`, позволяющий на основании YAML-макета получить файлы в форматах `json`, `cson` и `tmLanguage`. Следующий шаг - помещение в дочерние репозитории.

**Comment by EvilBeaver** [comment]
Создать процесс работает только по имени файла или exe. Если npm это батник, то надо писать npm.bat

-----Исходное сообщение-----
От: "Nikita Gryzlov" <notifications@github.com>
Отправлено: ‎07.‎12.‎2015 16:38
Кому: "xDrivenDevelopment/1c-syntax" <1c-syntax@noreply.github.com>
Копия: "Andrei Ovsiankin" <ovsiankin.aa@gmail.com>
Тема: Re: [1c-syntax] Билдер из YAML-tmLanguage. Инфраструктура (#8)

Его можно получить через yaml2json 1c.YAML-tmLanguage > 1c.json
Я сейчас готовлю скрипт-билдер.
@EvilBeaver В рамках оффтопа, можешь помочь? Есть бинарник в PATH (npm в частности). Из командной строки информацию выдает, из oscript - нет.
Запускаю вот таким образом:
Процесс = СоздатьПроцесс("npm -v", ТекущийКаталог(), Истина, , КодировкаТекста.UTF8);
Процесс.Запустить();
Ошибка:
{Модуль D:\git\1c-syntax\build.os / Ошибка в строке: 10 / Внешнее исключение: Не удается найти указанный файл}
Куда копать?

**Comment by EvilBeaver** [comment]
@nixel2007 насколько я знаю, все эти редакторы понимают формат xml plist. AAAPackage умеет делать plist из yaml. Возможна ли схема:

yaml->AAAPackage->plist->все редакторы ?

**Comment by EvilBeaver** [comment]
И еще, @nixel2007, раз уж все равно используется node.js, то зачем нужен отдельно 1Script+build.os? Его вроде можно на JS переписать несложно?

**Comment by nixel2007** [comment]
@EvilBeaver 
> насколько я знаю, все эти редакторы понимают формат xml plist

Если честно, не видел в документации к Атому, что он понимает pliist. В мануалах по составлению language-пакетов было везде написано про cson. ST и VCS понимают plist из коробки.

> Да, и насколько я знаю, sublime 3 понимает json сразу же, без AAAPackage (возможно ошибаюсь)

Судя по докам, ST использует plist (tmLanguage) и некий новый формат .sublime-syntax (он так же в YAML). Про JSON упоминаний не видел.

> Возможна ли схема:
yaml->AAAPackage->plist->все редакторы ?

Возможна, если использовать для сбора движок ST и написать скрипт, который будет обращаться к его cli.

**Comment by nixel2007** [comment]
@EvilBeaver 
> И еще, @nixel2007, раз уж все равно используется node.js, то зачем нужен отдельно 1Script+build.os? Его вроде можно на JS переписать несложно?

Можно :) Просто черновую версию писать проще на языке, который знаешь хорошо (хотя js в данном плане будет довольно простым). Как будет готов функционал (хотя бы в виде прототипа), можно попробовать переписать.

**Comment by nixel2007** [comment]
@EvilBeaver В целом node.js был выбран потому, что у ST в его package control я не нашел каких-либо плагинов по конвертации в `cson`, для работы Atom. А использовать 2 системы (ST для получения plist и json, и Node.js для конвертации в cson) не хотелось. Поэтому реализовал все на node.js

**Comment by EvilBeaver** [comment]
node отличный выбор, раз под него все есть.

**Comment by nixel2007** [comment]
Добавлен билдер в подчиненные репозитарии пакетов.
https://github.com/nixel2007/sublime-language-1c-bsl
https://github.com/nixel2007/atom-language-1c-bsl
https://github.com/nixel2007/vsc-language-1c-bsl

Файлы грамматик в этих репозитариях сейчас получены автоматически на основании файла YAML в репозитарии `1c-syntax`

@artbear Просьба, форкни репозитарии в пространство `xDrivenDevelopment`

Комменты по коду и доработки приветствуются :)

**Comment by artbear** [comment]
@nixel2007 
>Просьба, форкни репозитарии в пространство xDrivenDevelopment

Сделано, права розданы.
