### ISSUE TITLE
Список функций для автодополнения

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#81]
Необходимо реализовать/описать список функций для формирования автодополнения в редакторах.
В автодополнение должны попадать все функции глобального контекста, описанные в грамматике.

**Comment by bambr1975** [comment]
для vs code https://yadi.sk/d/QjqgTKtdnsPn9

**Comment by nixel2007** [comment]
@bambr1975 даже с описаниями! шикарно!

**Comment by bambr1975** [comment]
```     
var RangeWord = vscode.window.activeTextEditor.getWordRangeAtPosition(position);
var currentWord = vscode.window.activeTextEditor.getText(RangeWord);
if (!added[word] && word.length > 5&&word!=currentWord) {
```
Чтобы не подсказывала то слово, которое пишется в данный момент надо вставить в 64 строке.

**Comment by artbear** [comment]
А для атома что-то есть?

чт, 28 Янв 2016, 17:14, bambr1975 <notifications@github.com>:

**Comment by bambr1975** [comment]
по поводу атома надо определиться с symbol-provider. Если он будет поддерживать русскоязычные символы - то у него есть свое API для добавления своих глобальных свойств и методов - аналогично https://github.com/atom/language-php/blob/master/settings/language-php.cson и https://github.com/atom/language-sass/blob/master/settings/language-sass.cson , а если нет - то дублировать symbol-provider у меня пока что желания нет

**Comment by bambr1975** [comment]
Для sublime text (если не заморачиваться на вывод параметров)
https://yadi.sk/d/VCwa5xkAnuqGH

**Comment by nixel2007** [comment]
@bambr1975 
> по поводу атома надо определиться с symbol-provider.

ты хочешь сказать, что стандартный символ-провайдер сейчас не схавает completions-список на кириллице? Оо

беда какая...

**Comment by bambr1975** [comment]
дело не в symbol-provider, дело в autocomplete-manager - те строки, которые надо править в нем, мешают

**Comment by nixel2007** [comment]
> Для sublime text (если не заморачиваться на вывод параметров)

Это же сгенеренное? Можно тебя попросить английские синонимы добавить?

**Comment by nixel2007** [comment]
> дело не в symbol-provider, дело в autocomplete-manager - те строки, которые надо править в нем, мешают

а, т.е. с ручными правками работает?
если да, то на первое время пойдет.

**Comment by bambr1975** [comment]
в том же файле?

**Comment by nixel2007** [comment]
> в том же файле?
да. можно новой ссылкой, можно туда же.

**Comment by nixel2007** [comment]
Тогда постараюсь это в 1.1.5 так же впилить.

**Comment by bambr1975** [comment]
https://yadi.sk/d/VCwa5xkAnuqGH (та же ссылка). Тогда для atom ты сам копипастом из этого файла в settings перетащи, пожалуйста, аналогично https://github.com/atom/language-php/blob/master/settings/language-php.cson (опять же, если не заморачиваться на подсказки по параметрам и описания)

**Comment by nixel2007** [comment]
> Тогда для atom ты сам копипастом из этого файла в settings перетащи, пожалуйста, аналогично

да, конечно. спасибо!

**Comment by bambr1975** [comment]
маленькая поправка для vs code - обязательно нужно включить в bslGlobals список ключевых слов, либо в строке if (!added[word] && word.length > 5) уменьшить length - потому что сейчас при попытке напечатать Если или Иначе (а у них длина слова меньше или равна 5) подставляются совсем другие слова из подсказки

**Comment by nixel2007** [comment]
я смотрю, у тебя даже заготовка какая-то была:
```js
// for (var name in bslGlobals.keywords) {
    //     if (bslGlobals.keywords.hasOwnProperty(name)) {
    //         added[name] = true;
    //         result.push(createNewProposal(vscode.CompletionItemKind.Keyword, name, bslGlobals.keywords[name]));
    //     }
    // }
```

Правильно понимаю, что ее нужно раскомментить и создать коллекцию keywords в globals?

**Comment by bambr1975** [comment]
Да, просто я не очень понимаю, что ты хочешь там видеть, тем более ключевых слов не так много)))

**Comment by nixel2007** [comment]
> потому что сейчас при попытке напечатать Если или Иначе (а у них длина слова меньше или равна 5) подставляются совсем другие слова из подсказки

мне главное вот этого избежать) есть же еще английский `if`, в нем вообще 2 символа.

**Comment by bambr1975** [comment]
поэтому правильнее будет сделать коллекцию keywords в globals, и тогда if (!added[word] && word.length > 5) можно не менять

**Comment by nixel2007** [comment]
и расскоментить этот кусок кода, да?
сделаю. :)

**Comment by bambr1975** [comment]
да. Еще по поводу списков для sublime text и atom - там надо дубли поубирать. Может, глянешь?

**Comment by nixel2007** [comment]
ок.
