### ISSUE TITLE
Сниппеты/шаблоны текста

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#82]
Подходим к задаче создания сниппетов для редакторов. 

Подзадачи:
* [x] Поиск документации
  * Atom - https://atom.io/docs/latest/using-atom-snippets
  * Sublime text - http://docs.sublimetext.info/en/latest/extensibility/snippets.html
  * VS Code - https://code.visualstudio.com/Docs/customization/userdefinedsnippets
* [x] Составление единого файла для всех поддерживаемых сниппетов
* [x] Добавление английских шаблонов текста
* [ ] Решение проблемы со сниппетами для Атом (только 1 сниппет на префикс)
* [x] Написание генератора сниппетов по единому описанию
* [x] Рассмотрение возможности использования файла стандартных шаблонов, как источника

**Comment by nixel2007** [comment]
Пример обработки сниппета "Для Каждого":

1C:
```
Для Каждого <?"Переменная"> Из <?"Коллекция"> Цикл

	<?>

КонецЦикла;
```

Atom:
```cson
'.source.bsl':
  'Для Каждого':
    'prefix': 'для каждого'
    'body': """
      Для Каждого ${1:Переменная} Из ${2:Коллекция} Цикл

      \t$0

      КонецЦикла;
    """
```

ST:
```xml
<snippet>
    <content><![CDATA[Для Каждого ${1:Переменная} Из ${2:Коллекция} Цикл

	$0

КонецЦикла;]]></content>
    <tabTrigger>для каждого</tabTrigger>
    <scope>source.bsl</scope>
    <description>Для Каждого</description>
</snippet>
```

VSC:
```json
  "Для Каждого": {
    "prefix": "для каждого",
    "body": [
      "Для Каждого ${1:Переменная} Из ${2:Коллекция} Цикл",
      "",
      "\t$0",
      "",
      "КонецЦикла;"
    ]
  }
```

Таким образом, имеются особенности:
Atom:
* позволяет писать многострочные строки через """
* для табуляции требуется знак `\t`

ST:
* для использования многострочных строк не требуется особой обработки
* Для символа табуляции требуется использовать именно TAB. Этот символ трансформируется в зависимости от настроек пользователя.

VSC:
* Многострочные строки должны быть разбиты на массив строк
* для табуляции требуется знак `\t`
* Не удалось вызвать сниппет при написании "для каждого".

Все редакторы требуют некоторого экранирования.

**Comment by ebugusey** [comment]
У мелкософта есть конвертер для снипетов TextMate и ST.
https://code.visualstudio.com/Docs/customization/userdefinedsnippets#_using-textmate-snippets
В ST, я так понял можно использовать формат TextMate.
Так же в формате tmSnippets content (или body для VCS) пишется одной строкой. (Пример: https://github.com/textmate/php.tmbundle/blob/master/Snippets/Include%20TextMate%20Support%20Script.tmSnippet). Т.е. не придется для VCS body тоже можно писать одной строкой, а не массивом, как показано в документации.

**Comment by ebugusey** [comment]
В итоге цепочка конвертации получается такая.
* Основной формат хранения снипетов - yaml, как и для подсветки.
* ST = yaml > xml 
* VSC = ST > json (через yocode)
* Atom = VSC > cson (опционально)

Главная мякотка для конвертации в json находится [здесь](https://github.com/Microsoft/vscode-generator-code/blob/master/generators/app/snippetConverter.js), если Вы вдруг не хотите использовать yocode по какой-то причине. Лицензия MIT.

**Comment by nixel2007** [comment]
Спасибо большое за исследование, @ebugusey 
Я сейчас подумываю над конвертером из стандартного файла шаблонов текста 1с в какое-то промежуточное удобное нам хранение. Судя по описанной цепочке, думаю, yaml как раз подойдет.
