### ISSUE TITLE
Вводить клавиши от другой раскладки - фича "Не переключайся!"

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/1c-syntax#84]
Сделать фичу ввода клавиш от другой раскладки, [как в Снегопате](https://snegopat.ru/main/wiki?name=%D0%92%D0%BE%D0%B7%D0%BC%D0%BE%D0%B6%D0%BD%D0%BE%D1%81%D1%82%D0%B8).
Как ?

> Теперь для вставки "неудобных" символов, сочетаний символов и некоторых слов, нет нужды переключаться с русского на английский язык. В поставке Снегопата идет набор макросов для вставки таких символов, автоматически "вешающихся" на хоткеи:
> 
> ```
> Символ    Хоткей
> <   Alt + Б
>   Alt + Ю
> ~   Alt + ~
> @   Alt + @
> #   Alt + 3
> $   Alt + 4
> ^   Alt + 6
> &   Alt + 7
> []  Alt + [
> {}  Alt + Shift + [
> ]   Alt + ]
> }   Alt + Shift + ]
> ''  Alt + Э
> ""  Alt + Shift + Э
> Null    Alt + N
> =   Alt + = (сделано для удобства набора сочетаний <= >=)
> ```

**Comment by nixel2007** [comment]
По идее все это добро можно посетить на стандартные макросы каждого из редакторов. Так же, как сделана вставка `|`

**Comment by nixel2007** [comment]
Только надо обязательно проверить комбинации с правым альтом на пересечение со стандартными клавишами. Я заметил, что у меня в атоме чистовская раскладка клавиатуры `<` ставит, а `>` - нет

**Comment by ngchvsky** [comment]
Посмотрел как сделали в снегопаде. ИМХО очень неудобно. Можно ли авто замену сделать наборам 
БЮ - <>
ТГДД - NULL
и т.д.

Все равно такие наборы навряд ли встречаются

**Comment by nixel2007** [comment]
Коля, бюджет же, ну) 
К правому альту быстро привыкаешь, серьёзно. 

Отправлено с моего HTC

----- Ответное сообщение -----
От: "ngchvsky" <notifications@github.com>
Кому: "xDrivenDevelopment/1c-syntax" <1c-syntax@noreply.github.com>
Копия: "Nikita Gryzlov" <nixel2007@gmail.com>
Тема: [1c-syntax] Вводить клавиши от другой раскладки - фича "Не переключайся!" (#84)
Дата: чт, февр. 4, 2016 12:43

Посмотрел как сделали в снегопаде. ИМХО очень неудобно. Можно ли авто замену сделать наборам 

БЮ - <>

ТГДД - NULL

и т.д.

Все равно такие наборы навряд ли встречаются 

&mdash;

**Comment by allustin** [comment]
@nixel2007 @ngchvsky "проверено:на себе" - правый мизинец" сразу начинает работать для правого альта. левый мизинец используется для ctrl.

**Comment by kuntashov** [comment]
У меня почему-то правый альт под правым большим пальцем (раскладка ноутбучная, но ноут большой 17" и она стандартная, даже NumPad есть), но благодаря этому `Alt+Б`, `Alt+Ю` удобно нажимать как раз одной правой рукой.

Для SublimeText давно сделал макросы для вставки a-la Снегопат, не писал об этом, т.к. думал это сугубо индивидуально и давно все настроили. На всякий случай делюсь своими настройками хоткеев. Сделано не все, как в Снегопате, но почти.

Также обращаю внимание, что комбинации `Alt+1,..., Alt+0` в Sublime Text как и, например, в браузерах, позволяют быстро переключаться между открытыми вкладками, и их переопределение лишит вас этой возможности. Я от этого не страдаю.

Также я на `Alt+1` повесил вызов списка процедур, т.к. мне так удобнее (не умею левый Ctrl нажимать мизинцем, дальше шифта тяжело тянуться, а двумя руками (правой рукой Ctrl, левой - R) нажимать никак не могу себя приучить. Снегопатовский `Ctrl+1` по этой же причине не очень люблю.

```json
[
	{ "keys": ["ctrl+t"], "command": "reveal_in_side_bar" },

	{"keys": ["alt+б"], "command": "insert", "args": {"characters": "<"}},
	{"keys": ["alt+,"], "command": "insert", "args": {"characters": "<"} },
	{"keys": ["alt+ю"], "command": "insert", "args": {"characters": ">"}},
	{"keys": ["alt+."], "command": "insert", "args": {"characters": ">"}},

	{"keys": ["alt+2"], "command": "insert", "args": {"characters": "@"}},
	{"keys": ["alt+3"], "command": "insert", "args": {"characters": "#"}},
	{"keys": ["alt+4"], "command": "insert", "args": {"characters": "$"}},
	{"keys": ["alt+5"], "command": "insert", "args": {"characters": "%"}},
	{"keys": ["alt+6"], "command": "insert", "args": {"characters": "^"}},
	{"keys": ["alt+7"], "command": "insert", "args": {"characters": "&"}},

	{"keys": ["alt+э"], "command": "insert", "args": {"characters": "''"}},
	{"keys": ["alt+shift+э"], "command": "insert", "args": {"characters": "\"\""}},

	{"keys": ["alt+1"], "command": "show_overlay", "args": {"overlay": "goto", "text": "@"} },
]
```

**Comment by nixel2007** [comment]
@kuntashov да, я тоже большим пальцем жмякаю)
скажи, а оно на левый альт срабатывает? Возможно ли добавить какой-либо модификатор, чтобы забиндить только правый альт?

**Comment by kuntashov** [comment]
@nixel2007 точно не знаю, не задавался вопросом, AltR, AltL не работают, но вот гуглится (правда для ST2) вот такое:

1. http://stackoverflow.com/questions/16989065/sublime-text-2-key-bindings-is-there-any-way-to-detect-left-right-modifier-key
2. http://superuser.com/questions/608225/sublime-text-2-key-bindings-is-there-any-way-to-detect-left-right-modifier-key

Но я бегло прочитал и не понял в итоге, как сделать.

**Comment by nixel2007** [comment]
@kuntashov вроде в доках написано про `rightalt`

**Comment by kuntashov** [comment]
@nixel2007 поменял `alt` на `rightalt`, хоткеи по прежнему работают, но без измеенний, т.е. при нажатии левого альта все также срабатывает как будт-то бы на него повешены те же хоткеи, что ии на правый, хотя в кеймапе написано все только для правого.

Написал в кеймапе вот так (не имеющие значения для примера определения хоткеев удалил):

```json
[
	{"keys": ["rightalt+1"], "command": "show_overlay", "args": {"overlay": "goto", "text": "@"} },
	{"keys": ["leftalt+1"], "command": "insert", "args": {"characters": "Hello, World!"} },
]
```
В итоге при нажатии на `Alt+1`  и слева и справа выводится всегда `"Hello, World!"`.

Поменял строчки местами (биндинг для правого альта теперь последней строкой - на нем вывод списка автодополнения), в итоге и при левом и при правом альте выводится список автодополнения.

Получается, что либо:

1. клавиши саблайм различает, но видимо на уровне ОС нет между ними различия 
2. в конфигах rightalt=leftalt=alt и по сути являются синонимами
3. у меня на аппаратном уровне в ноуте альты не отличаются на уровне кодов клавишь

Пока не знаю как проверить гипотезы. Проверишь под виндой поведение?

Я использую Linux Mint 17.3 LTS c оконным менеджером Xfce, соответственно все вышенаписанное поведение проверялось именно в этом окружении. В  Xfce есть глобальный перехват ряда хоткеев, не очень на мой вкус удачных, но я их поудалял. Там были в том числе с альтами, и там в конфигах правый и левый отличаются, но я не пользовался этими хоткеями, поэтому вообще удалил. Надо будет восстановить и посмотреть - работает ли различие (чтобы отмести 1 и 3 гипотезы).

**Comment by nixel2007** [comment]
@kuntashov проверил на ноуте под вин10 - поведение правого альта равно поведению левого альта.

Надо еще проверить на стационаре.

Что любопытно, чистовская клавиатура работает нормально, и всякие <> NULL COM и прочие набираются без проблем, чисто правым альтом.

**Comment by kuntashov** [comment]
@nixel2007 
> Что любопытно, чистовская клавиатура работает нормально, и всякие <> NULL COM и прочие набираются без проблем, чисто правым альтом.

Скорее всего тогда сам ST не различает их и как я написал, для него в конфигах rightalt/leftalt/alt являются просто синонимами.

**Comment by nixel2007** [comment]
что характерно, автор еще в 2009 году "в новой бете" обещал это пофиксить...

8 февраля 2016 г., 11:58 пользователь Alexander Kuntashov <
notifications@github.com> написал:

**Comment by kuntashov** [comment]
@nixel2007 кажется, просто маловосстребовано, вот он и подзабил

**Comment by awa15** [comment]
@nixel2007 , @kuntashov , а зачем вы хотите отключить левый Alt? Я в снегопате всегда пользуюсь именно левым альтом, а правым практически не пользуюсь. Имхо, все сочетания должны работать с любым альтом.

**Comment by kuntashov** [comment]
@awa15 не отключить, а сделать, кому надо, возможным, например, сохранить стандартную работу `Alt+1,...,Alt+9` (например, с левым альтом) для переключения между открытыми табами редактора, но при этом иметь возможность пользоваться снегопатовскими возможностями (используя комбинации правый аль + цифра).

Не обязательно это включать в дефолтную поставку, но по крайней мере возможность полезная для тех, кому надо, поэтому обсуждаем возможное решение.

**Comment by nixel2007** [comment]
@awa15 тогда ломается стандартное поведение по левому альту :) даже в конфигураторе по умолчанию используются такие бинды для переключения по окнам в редакторе форм, например.

**Comment by nixel2007** [comment]
Ставим клавиатуру от Чистова и вперед.
