### ISSUE TITLE
[ST] Перевод строки у последней строки, заканчивающейся на двойную кавычку приводит к вставке вертикальной черты

### ISSUE THREAD

**Issue by kuntashov** [xDrivenDevelopment/1c-syntax#85]
Обнаружил в SublimeText 3 следующий баг, приводящий к вставке вертикальной черты (pipe - `|`) там, где этого не должно происходить. Походу что-то с определением начала многострочной строки. Воспроизводится с использованием последней версии пакета `1c-syntax`, обновленного из Package Control.

Порядок воспроизведения:

1. Создаю и сохраняю новый os-файл.
2. В первой строке файла пишу `#Использовать "logos"` и после закрывающей двойной кавычки нажимаю `Enter`

Получаю результат:
```oscript
#Использовать "logos"
|
```
Т.е. вставляется символ  `|` в начале новой строки, курсор устанавливается сразу после него.

Ожидаю: в новой строке символа `|` не будет, курсор будет в начале новой строки.

Ошибка проявляется только после нажатия Enter в последней строке, оканчивающейся на двойную кавычку. Если строка не последняя, то вертикальная черта не вставляется.

**Comment by kuntashov** [comment]
Баг для работы совсем не критичный, обходится легко: просто добавить предварительно одну пустую строку в конец файла. В большинстве случаев мы работаем с непустыми файлами, поэтому возможно исправлять и не надо, если сложно.

**Comment by nixel2007** [comment]
@kuntashov если мне память не изменяет, я натыкался на похожее поведение, если сделать перевод сразу строки *перед* первым символом кавычки.

**Comment by kuntashov** [comment]
@nixel2007 да, и так тоже воспроизводится:

1. В строчке `#Использовать "logos"` ставлю курсор перед `"logos`
2. Нажимаю `Enter`

Получаю результат:

```oscript
#Использовать 
|"logos"
```

**Comment by bambr1975** [comment]
Значит, надо поменять в пакете настройки клавиш аналогично vs code:
```
[
	{ "keys": ["enter"], "command": "insert", "args": {"characters": "\n|"}, "context":
		[
			{ "key": "preceding_text", "operator": "regex_contains", "operand": "^\\s*\\|([^\"]|\"[^\"]*\")*$", "match_all": true }
		]
	},
	{ "keys": ["enter"], "command": "insert", "args": {"characters": "\n|"}, "context":
		[
			{ "key": "preceding_text", "operator": "regex_contains", "operand": "^([^\\|\"]|\"[^\"]*\")*\"[^\"]*$", "match_all": true }
		]
	}
]
```

**Comment by nixel2007** [comment]
@bambr1975 да, эту проблему оно решает, но получается некоторая смена поведения.
В старом варианте, если делаешь перевод строки *до* символа |, то вставляется `\n|`, так все это попадало все равно попадало в `string.quoted.double.bsl`
Теперь же вставляется только `\n`

@kuntashov (и кто еще здесь использует ST) Если это не критично, возьму новый вариант.

**Comment by kuntashov** [comment]
@nixel2007 для меня не критично ни то ни другое поведение на самом деле, поэтому просто предлагаю сделать/оставить так, чтобы во всех редакторах пакет одинаково работало.

@bambr1975 спасибо за исправление!

**Comment by nixel2007** [comment]
Забавно, но заметил, что в атоме сейчас есть такая же проблма.

**Comment by bambr1975** [comment]
костыль, наверное
```
    editor = atom.workspace.getActiveTextEditor()
    cursorPos = editor.getLastCursor().getBufferPosition()
    beginRow = cursorPos.translate([-1, 1])
    textRow = editor.getTextInBufferRange([beginRow, cursorPos])
    Reg1 = /^\s*\|([^\"]|\"[^\"]*\")*$/
    Reg2 = /^([^\|\"]|\"[^\"]*\")*\"[^\"]*$/
    if ((Reg1.exec(textRow) != null)||(Reg2.exec(textRow) != null))
      editor.insertText '\n'
      editor.insertText '|'
    else
      editor.insertText '\n'
```

**Comment by nixel2007** [comment]
можно как-нибудь попроще? чтобы без регулярок.
Условно:
```
Если ТекущийСкоуп = "string.quoted.double.bsl" И ТекущийСкоуп = СкоупНаПредыдущейПозиции Тогда
      editor.insertText '\n'
      editor.insertText '|'
```

**Comment by bambr1975** [comment]
В случае, если курсор стоит сразу после кавычек, тебе это поможет?

**Comment by nixel2007** [comment]
А после кавычек в атоме такой проблемы нет :D 
Но посыл понял :)

**Comment by nixel2007** [comment]
Исправлено в 1.1.7
