### ISSUE TITLE
Не отображается картинка в Вики

### ISSUE THREAD

**Issue by artbear** [xDrivenDevelopment/1c-syntax#87]
[Страница "Запуск скриптов .os .bsl с помощью OneScript", Раздел "Использование пакета build"](https://github.com/xDrivenDevelopment/atom-language-1c-bsl/wiki/%D0%97%D0%B0%D0%BF%D1%83%D1%81%D0%BA-%D1%81%D0%BA%D1%80%D0%B8%D0%BF%D1%82%D0%BE%D0%B2-.os-.bsl-%D1%81-%D0%BF%D0%BE%D0%BC%D0%BE%D1%89%D1%8C%D1%8E-OneScript#%D0%98%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BF%D0%B0%D0%BA%D0%B5%D1%82%D0%B0-build)

**Comment by nixel2007** [comment]
Какая? С телефона глянул, вроде все в по

**Comment by artbear** [comment]
Странно, пару раз обновил страницу и стало показываться.
Закрываю.
