### ISSUE TITLE
Поломалась подсветка в ST 3

### ISSUE THREAD

**Issue by JohnyDeath** [xDrivenDevelopment/1c-syntax#89]
![image](https://cloud.githubusercontent.com/assets/5936030/13036458/f473a10e-d378-11e5-87e2-89effcc486ab.png)
Версия пакета 1.2.0
Версия ST Build 3103

**Comment by nixel2007** [comment]
Грамматика верная выбрана? У меня с ST 3102 проблем не было.

**Comment by JohnyDeath** [comment]
Хм, пришел на работу, здесь всё нормально.
Дома грамматика называлась "1C:Enterprise", подумал, что вы ее переименовали. Странно, откуда она вообще у меня дома взялась.
Вечером все перепроверю

**Comment by nixel2007** [comment]
@JohnyDeath в 1.2.0 для ST единственное отличие от других редакторов - вместо 1c (bsl) теперь группа синтаксисов Language 1c (BSL), в которой теперь 2 синтаксиса: под встроенный язык и запросы.

**Comment by JohnyDeath** [comment]
Дома у меня оказывается есть вот такой отдельный язык.
![image](https://cloud.githubusercontent.com/assets/5936030/13087330/629ad7e4-d4f8-11e5-9550-c872e41db070.png)
Сначала я подумал, что ты так переименовал в новом 1.2.0 релизе текущую подсветку, но теперь понимаю, что это что-то иное. Откуда оно взялось - не знаю )

**Comment by nixel2007** [comment]
@JohnyDeath а можешь посмотреть, что у тебя установлено в пакетах или в папке user?
`%appdata%/Sublime text 3/Packages`

Может там будет что-то полезное в грамматике, что можно будет использовать у нас.

**Comment by JohnyDeath** [comment]
Там только файлик с его настройками:
```
{
	"extensions":
	[
		"os"
	]
}
```
и всё )
Возможно это я давно что-то сам пытался наваять и забыл почистить.
