### ISSUE TITLE
[VCS] Symbols provider

### ISSUE THREAD

**Issue by ebugusey** [xDrivenDevelopment/1c-syntax#96]
Когда используется перенос строки LF, SymbolsProvider неправильно выдает указатель на символы.
![screenshot 2016-02-24 11 58 22](https://cloud.githubusercontent.com/assets/8318227/13279025/154d7cc0-daee-11e5-867a-d7fd560ee82b.png)

**Comment by nixel2007** [comment]
Это как раз правильное место для репорта :)

**Comment by ebugusey** [comment]
Я сначала создал в vsc, а потом подумал, что надо бы было лучше создать в основной репе. Решил удалить баг из vsc, но Вы уже перенесли её сюда.
