### ISSUE TITLE
[Atom] Symbols provider

### ISSUE THREAD

**Issue by ebugusey** [xDrivenDevelopment/1c-syntax#98]
Атомовский плагин для отображения списка символов использует ctags. Естественно ctags не знает о 1С. Так что там эта фича не работает. Но в поддерживаемых фичах в ридми написано, что это есть.
Я имею ввиду строчку "Список процедур и функций текущего файла".

**Comment by nixel2007** [comment]
Для работы списка процедур функций используется пакет `goto`, определяющий процедуры на основе грамматики, а не не на основе ctags.
Возникают какие-то проблемы при работе?

**Comment by ebugusey** [comment]
Я не знал, что именно goto используется, а не "родной" плагин атома.

**Comment by nixel2007** [comment]
@ebugusey поддержка родного плагина в планах. Меня не устраивает скорость работы goto.
